[tool.poetry]
name = "pysciebo"
version = "1.0.0"
description = "A Python client for sciebo aka hochschulcloud.nrw"
authors = ["Nils Müller <nils.mueller@uni-bielefeld.de>"]

[tool.poetry.dependencies]
python = "^3.9"
pyocclient = "^0.6"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
flake8 = "^4.0.1"
ipython = "^7.28.0"
mypy = "^0.910"
pdbpp = "^0.10.3"
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
