[tool.poetry]
name = "zenml"
version = "0.5.1"
packages = [
    { include = "zenml", from = "src" },
]
description = "ZenML: Write production-ready ML code."
authors = ["ZenML GmbH <info@zenml.io>"]
readme = "README.md"
homepage = "https://zenml.io"
documentation = "https://docs.zenml.io"
repository = "https://github.com/zenml-io/zenml"
license = "Apache-2.0"
keywords = [
    "machine learning", "production", "pipeline", "mlops", "devops"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: System :: Distributed Computing",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
exclude = [
    "*.tests",
    "*.tests.*",
    "tests.*",
    "tests",
    "docs",
    "legacy",
    "examples",
    "playground"
]
include = [
    "src/zenml",
    "*.txt",
    "*.md",
    "*.sh"
]

[tool.poetry.scripts]
zenml = "zenml.cli.cli:cli"

[tool.poetry.dependencies]
python = ">=3.6.2,<3.9"
ml-pipelines-sdk = "^1.3.0"
panel = "^0.11.3"
pandas = "^1.1.5"
apache-beam = "^2.30.0"
pyyaml = "^5.4.1"
python-dateutil = "^2.8.1"
gitpython = "^3.1.18"
click = "^8.0.1"
pydantic = "^1.8.2"
analytics-python = "^1.4.0"
distro = "^1.6.0"
# A list of all of the optional dependencies, some of which are included in the
# below `extras`. They can be opted into by apps.
apache-airflow = {version = "^2.1.4", optional = true }
gcsfs = {version= "^2021.9.0", optional = true}
tabulate = "^0.8.9"

[tool.poetry.extras]
airflow = ["apache-airflow"]
gcp = ["gcsfs"]
# This should contain ALL of the above
all = ["apache-airflow", "gcsfs"]

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
mypy = "^0.910"
flake8 = "^3.9.2"
black = "^21.7b0"
interrogate = "^1.4.0"
coverage = { extras = ["toml"], version = "^5.5" }
isort = "^5.9.3"
pre-commit = "^2.14.0"
autoflake = "^1.4"
pyment = "^0.3.3"
tox = "^3.24.3"
hypothesis = "^6.23.0"
Sphinx = "^4.2.0"
sphinx-bootstrap-theme = "^0.8.0"
typing-extensions = ">=3.7.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-version-plugin]
source = "init"

[tool.tox]
name = "ZenML"
authors = ["Hamza Tahir <hamza@zenml.io>"]
legacy_tox_ini = """
[tox]
isolated_build = True
skipsdist = true
envlist = py36,py37,py38,py39

[testenv]
whitelist_externals = poetry
commands =
    poetry install -v --extras all
    poetry run pytest tests
    poetry run bash scripts/mypy.sh --install-types
"""

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
]
log_cli = true
log_cli_level = "INFO"
testpaths = "tests"

[tool.coverage.run]
parallel = true
source = [
    "src/zenml"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    'if __name__ == "__main__":',
    "if TYPE_CHECKING:",
]

[tool.isort]
profile = "black"
known_third_party = []
skip_glob = []
line_length = 80

[tool.mypy]
strict = true
namespace_packages = true
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "tensorflow.*",
    "apache_beam.*",
    "pyarrow.*",
    "pandas.*",
    "ml_metadata.*",
    "distro.*",
    "analytics.*",
    "absl.*",
    "gcsfs.*",
    "torch.*",
    "pytorch_lightning.*",
    "sklearn.*",
    "numpy.*",
]
ignore_missing_imports = true

[tool.black]
line-length = 80
include = '\.pyi?$'
exclude = '''
/(
	\.git
| \.hg
| \.mypy_cache
| \.tox
| \.venv
| _build
| buck-out
| build
)/
'''

[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = true
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = false
fail-under = 80
exclude = ["setup.py", "docs", "build"]
ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*"]
verbose = 1
quiet = false
whitelist-regex = []
color = true
