[tool.poetry]
name = "PyTerm1"
version = "1.1.0"
description = "Terminal on py3"
authors = ["layfikRus"]

[tool.poetry.dependencies]
python = "3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
