[project]
name = "soie"
version = "0.1.0"
description = "A simple async Python Web framework"
readme = "README.md"
dependencies = [ "typing-extensions~=3.10",]
requires-python = ">=3.8"
dynamic = [ "classifiers",]
[[project.authors]]
name = "Elliot"
email = "hack00mind@gmail.com"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project.license]
text = "\tApache-2.0"

[project.urls]
homepage = "https://github.com/Eliot00/soie"

[project.optional-dependencies]

[tool.pdm]
includes = [ "soie",]
source-includes = [ "tests",]

[tool.black]
line-length = 120
exclude = "/(\n    \\.eggs\n  | \\.git\n  | \\.hg\n  | \\.mypy_cache\n  | \\.tox\n  | \\.venv\n  | _build\n  | buck-out\n  | build\n  | dist\n  | tests/fixtures\n)/\n"

[tool.isort]
profile = "black"
atomic = true

[tool.pdm.scripts]
test = "pytest tests/"
lint = "pre-commit run --all-files"

[tool.pdm.dev-dependencies]
test = [ "pytest~=6.2", "pytest-asyncio~=0.15", "async-asgi-testclient~=1.4",]
