[tool.poetry]
name = "talerbank"
version = "0.8.2"
description = "Taler demo bank"
authors = ["Marcello Stanisci <ms@taler.net>", "Florian Dold <dold@taler.net"]
license = "GPL-3.0-or-later"
include = ["talerbank/app/locale/*/LC_MESSAGES/django.mo"]
exclude = ["talerbank/app/locale/*/LC_MESSAGES/django.po"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1.3"
taler-util = "^0.8.3"
lxml = "^4.6.1"
psycopg2 = "^2.8.6"
Jinja2 = "^3.0.0"
qrcode = "^6.1"
uWSGI = "^2.0.19"
requests = "^2.24.0"
click = "^7.1.2"
Babel = "^2.8.0"

[tool.poetry.dev-dependencies]
pylint = "^2.6.0"
django = "^3.1.3"
black = "^20.8b1"
mock = "^4.0.2"

[tool.poetry.scripts]
taler-bank-manage = 'talerbank.cli:run'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
