
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-20T12:00:49-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1510e6216ff086b498fb1d85d5b2386dca75c8b",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
