# coding: utf-8

"""
    Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference

    <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v6/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import yahoo_search_api
from yahoo_search_api.models.account_management import AccountManagement  # noqa: E501
from yahoo_search_api.rest import ApiException

class TestAccountManagement(unittest.TestCase):
    """AccountManagement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AccountManagement
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = yahoo_search_api.models.account_management.AccountManagement()  # noqa: E501
        if include_optional :
            return AccountManagement(
                account_id = 56, 
                account_name = '0', 
                account_payment = yahoo_search_api.models.account_management_service_payment.AccountManagementServicePayment(
                    invoice = yahoo_search_api.models.account_management_service_invoice.AccountManagementServiceInvoice(
                        budget_amount = 56, 
                        end_date = '0', 
                        start_date = '0', ), 
                    payment_type = 'PREPAY', ), 
                agency_person_name = '0', 
                agency_prefecture_code = 'HOKKAIDO', 
                auth_type = 'REFERABLE', 
                auto_tagging_enabled = 'FALSE', 
                client = yahoo_search_api.models.account_management_service_client.AccountManagementServiceClient(
                    building = '0', 
                    city = '0', 
                    client_person_name = '0', 
                    company_name = '0', 
                    company_name_kana = '0', 
                    enterprise_type = 'KABUSHIKI', 
                    enterprise_type_position = 'FRONT', 
                    phone_number = 'a', 
                    prefecture_code = 'HOKKAIDO', 
                    street1 = '0', 
                    street2 = '0', 
                    url = '0', 
                    url_type = 'PC', 
                    zip = 'a', ), 
                client_type = 'AGENT', 
                contact_biz_id = '0', 
                delivery_status = 'ACTIVE', 
                is_adult_account = 'TRUE', 
                is_test_account = 'TRUE', 
                status = 'INPROGRESS'
            )
        else :
            return AccountManagement(
        )

    def testAccountManagement(self):
        """Test AccountManagement"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
