# coding: utf-8

"""
    Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference

    <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v6/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import yahoo_search_api
from yahoo_search_api.api.ad_group_feed_service_api import AdGroupFeedServiceApi  # noqa: E501
from yahoo_search_api.rest import ApiException


class TestAdGroupFeedServiceApi(unittest.TestCase):
    """AdGroupFeedServiceApi unit test stubs"""

    def setUp(self):
        self.api = yahoo_search_api.api.ad_group_feed_service_api.AdGroupFeedServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ad_group_feed_service_get_post(self):
        """Test case for ad_group_feed_service_get_post

        """
        pass

    def test_ad_group_feed_service_set_post(self):
        """Test case for ad_group_feed_service_set_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
