[build-system]
requires = [
    "pip",
    "setuptools>=42",
    "numpy>=1.16.2",
    "scipy>=1.4.1",
    "pandas>=0.23.4",
    "requests>=2.24.0",
    "matplotlib",
    "beautifulsoup4>=4.9.3",
    "lxml",
]
build-backend = "setuptools.build_meta"
