[package]
name = "jsonschema"
version = "0.12.2"
authors = ["dmitry.dygalo <dadygalo@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "../README.md"
description = "A crate for performing JSON schema validation"
repository = "https://github.com/Stranger6667/jsonschema-rs"
keywords = ["jsonschema", "validation"]
exclude = ["tests", "python", "benches/data/*.json", ".github", ".yamllint", ".pre-commit-config.yaml", ".gitignore", ".gitmodules", "*.md"]

categories = ["web-programming"]

[[bin]]
name = "jsonschema"

[features]
default = ["reqwest", "cli"]
cli = ["structopt"]

[dependencies]
serde_json = "1"
url = "2"
lazy_static = "1"
percent-encoding = "2"
regex = "1"
fancy-regex = "^0.7.1"
base64 = ">= 0.2"
time = { version = ">= 0.3.3", features = ["parsing", "macros"] }
reqwest = { version = ">= 0.10", features = ["blocking", "json"], optional = true}
parking_lot = ">= 0.1"
num-cmp = ">= 0.1"
ahash = "0.7"
structopt = { version = ">= 0.3", optional = true }
itoa = "0.4"
fraction = { version = "0.8", default-features = false, features = ["with-bigint"] }

[dev-dependencies]
criterion = ">= 0.1"
mockito = ">= 0"
json_schema_test_suite = { version = ">= 0.3", path = "../jsonschema-test-suite"}
jsonschema-valid = "0.4.0"
bench_helpers = { path = "../bench_helpers" }
valico = "3.6.0"
test-case = "1"
paste = ">= 0.1"
reqwest = { version = ">= 0.10", features = ["blocking", "json"] }

# Benchmarks for `jsonschema`
[[bench]]
name = "jsonschema"
harness = false

# Benchmarks for `valico`
[[bench]]
name = "valico"
harness = false

# Benchmarks for `jsonschema_valid`
[[bench]]
name = "jsonschema_valid"
harness = false

[profile.release]
codegen-units = 1
lto = "on"
