# Generated by Django 3.1.6 on 2021-02-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0013_administrators_old_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrators',
            name='old_id',
        ),
    ]
