# Generated by Django 3.1.6 on 2021-03-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0014_remove_administrators_old_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrators_images',
        ),
    ]
