# Generated by Django 3.1.6 on 2021-03-03 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import isc_common.fields.description_field
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_ext', '0022_persons_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='description',
            field=isc_common.fields.description_field.DescriptionField(),
        ),
        migrations.AddField(
            model_name='persons',
            name='editor',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
