# Generated by Django 3.1.7 on 2021-03-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0036_auto_20210304_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='old_id',
        ),
    ]
