# Generated by Django 3.1.7 on 2021-03-09 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_ext', '0045_auto_20210309_0833'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users_images',
        ),
    ]
