# Generated by Django 3.1.7 on 2021-03-15 12:14

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_ext', '0049_auto_20210315_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts_e_mails',
            name='props',
            field=bitfield.models.BitField((('main', 'Главная'),), db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='contacts_phones',
            name='props',
            field=bitfield.models.BitField((('main', 'Главная'),), db_index=True, default=0),
        ),
    ]
