# Generated by Django 3.2 on 2021-04-11 23:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_ext', '0066_alter_contacts_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='old_id',
        ),
        migrations.AddField(
            model_name='contacts',
            name='old_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None, unique=True),
        ),
    ]
