# Generated by Django 3.2.4 on 2021-06-08 16:32

import bitfield.models
import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models

import isc_common.fields.description_field


class Migration(migrations.Migration):
    dependencies = [
        ('user_ext', '0071_alter_person_club_photos_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons_view',
            fields=[
                ('old_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('active', models.BooleanField()),
                ('archive', models.BooleanField()),
                ('description', isc_common.fields.description_field.DescriptionField()),
                ('props', bitfield.models.BitField((('active', 'active'), ('archive', 'archive')), db_index=True, default=1)),
            ],
            options={
                'verbose_name': 'Персоны',
                'db_table': 'user_ext_persons_view',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='persons',
            name='props',
            field=bitfield.models.BitField((('active', 'active'), ('archive', 'archive')), db_index=True, default=1),
        ),
    ]
