# Generated by Django 3.2.7 on 2021-09-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0079_alter_persons_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrators',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
