[tool.poetry]
name = "idict"
version = "0.211018.4"
description = "Lazy dict with universally unique identifier for values"
authors = ["davips <dpsabc@gmail.com>"]
license = "GPL"
readme = 'README.md'
packages = [
    { include = "idict", from = "src" }
]

# For more dependencies: poetry install -E full
[tool.poetry.extras]
full = ["pandas"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
orjson = "^3.5.0"
pdoc3 = "^0.10.0"
pandas = { version = "^1.3.3", optional = true }
lz4 = "^3.1.3"
ldict = "^3.211019.3"

[tool.poetry.dev-dependencies]
autoreadme = "^0.2102.20"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
black = "^21.7b0"
pypiserver = "^1.4.2"
passlib = "^1.7.4"
pylint = "^2.7.4"
ipython = "^7.26.0"
pandas = "^1.3.3"
numpy = "^1.21.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

#[[tool.poetry.source]]
#name = "dvpypi"
#url = "http://localhost:8080/simple"
#secondary = true
