# Generated by Django 3.1.6 on 2021-02-17 13:01

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0002_user_user_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_types',
            name='props',
            field=bitfield.models.BitField((('relevant', 'Актуальность'),), db_index=True, default=1),
        ),
    ]
