# Generated by Django 3.1.6 on 2021-03-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0016_users_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_images',
            old_name='user',
            new_name='main_model',
        ),
    ]
