# Generated by Django 3.1.7 on 2021-03-03 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_ext', '0028_auto_20210303_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
