# Generated by Django 3.1.7 on 2021-03-04 08:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0032_auto_20210303_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='old_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=None, size=None, unique=True),
        ),
    ]
