# Generated by Django 3.2 on 2021-04-09 06:36

import bitfield.models
import django.utils.timezone
from django.db import migrations, models

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0249_auto_20210409_0458'),
        ('isc_common', '0094_alter_debug_id'),
        ('user_ext', '0063_auto_20210406_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_club_photos',
            fields=[
                ('old_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('props', bitfield.models.BitField((('main', 'main'),), db_index=True, default=0)),
                ('club', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.clubs')),
                ('users_image', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.users_images')),
            ],
            options={
                'verbose_name': 'Кросс таблица',
            },
        ),
    ]
