[tool.poetry]
name = "jotdx"
version = "0.1.0"
description = "Get data"
authors = ["FangyangJz <fangyang.jing@hotmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.1"
pandas = "^1.3.4"
tqdm = "^4.62.3"
loguru = "^0.5.3"
httpx = "^0.20.0"
tenacity = "^8.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
