"""Autogenerated version information file.

Manual changes to this file will be overwritten.

The output of git describe was: ``2.0.2``

The derived version is: ``2.0.2``
"""
__version__ = '2.0.2'
DEV_CLASSIFIER = 'Development Status :: 5 - Production/Stable'
