#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='fastapi_rapidoc',
      version='0.1.1',
      description='Quickly add RapiDoc to FastAPI',
      author=None,
      author_email='Mawoka <mawoka-myblock@e.email>',
      url=None,
      py_modules=['fastapi_rapidoc'],
     )
