
# This file was generated by '_versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-19T16:57:15-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "6b4aa459b74288d7fc18cc3fc9fc86f393c339a2",
 "version": "1.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
