[tool.poetry]
name = "bracket-check"
version = "0.2.0"
description = ""
authors = ["skotwind <skotwind@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
python-shell = "^1.0.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
create = "create_util:run"