
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-24T16:31:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "77fcd891097b5cbc496dd4a226f3c1c6ff5b4a83",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
