# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

[tool.poetry]
name = "aws-service-catalog-factory"
version = "0.67.0"
description = "Making it easier to build ServiceCatalog products"
classifiers = ["Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "Programming Language :: Python :: 3", "License :: OSI Approved :: Apache Software License", "Operating System :: OS Independent", "Natural Language :: English"]
homepage = "https://service-catalog-tools-workshop.com/"
readme = "README.md"
repository = "https://github.com/awslabs/aws-service-catalog-factory-framework"
authors = ["Eamonn Faherty <aws-service-catalog-tools@amazon.com>"]
packages = [
    { include = "servicecatalog_factory", from = "." },
]
include = ["servicecatalog_factory"]

[tool.poetry.scripts]
servicecatalog-factory = "servicecatalog_factory.cli:cli"

[tool.poetry.urls]
issues = "https://github.com/awslabs/aws-service-catalog-factory-framework/issues"

[tool.poetry.dev-dependencies]
codecov = "==2.0.22"
pylint = "*"
black = "^19.10b0"
nose2 = "^0.10.0"

[tool.dephell.main]
versioning = "semver"
from = {format = "poetrylock", path = "poetry.lock"}
envs = ["main"]
to = {format = "poetry", path = "pyproject.toml"}

[tool.poetry.dependencies]
python = ">=3.7"
docutils = "0.14"
jinja2 = "==2.11.3"
click = "7.0"
boto3 = "1.14.33"
cfn-flip = "1.2.1"
terminaltables = "3.1.0"
luigi = "2.8.6"
requests = "2.22.0"
pylint = "2.5.0"
colorclass = "2.2.0"
colorama = "0.4.4"
troposphere = "3.1.0"
PyYAML = "5.4"
better-boto = "0.36.0"
deepmerge = "0.3.0"
yamale = "3.0.8"
awacs = "2.0.2"
astroid = "2.4.2"
botocore = "1.17.33"
certifi = "2020.6.20"
chardet = "3.0.4"
enum34 = "1.1.10"
idna = "2.8"
isort = "4.3.21"
Jinja2 = "2.11.3"
jmespath = "0.10.0"
lazy-object-proxy = "1.4.3"
lockfile = "0.12.2"
MarkupSafe = "1.1.1"
mccabe = "0.6.1"
python-daemon = "2.1.2"
python-dateutil = "2.8.1"
s3transfer = "0.3.3"
six = "1.15.0"
toml = "0.10.1"
tornado = "4.5.3"
typed-ast = "1.4.1"
typing-extensions = "3.10.0.2"
urllib3 = "1.22"
wrapt = "1.12.1"
