input: ["img"]
output: ["bboxes", "bbox_scores", "bbox_labels"]

weights_dir: ["../peekingduck_weights/mtcnn"]
blob_file: "mtcnn.zip"
graph_files: {
    mtcnn: ../peekingduck_weights/mtcnn/mtcnn.pb
}
mtcnn_min_size: 40
mtcnn_factor: 0.709
mtcnn_thresholds: [0.6, 0.7, 0.7]
mtcnn_score: 0.7
MODEL_NODES: {
    mtcnn: {
        inputs: [input:0, min_size:0, thresholds:0, factor:0],
        outputs: [prob:0, landmarks:0, box:0]
    }
}
