# Generated by Django 3.2.4 on 2021-06-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raiting_of_players',
            old_name='wins',
            new_name='kf_wins',
        ),
        migrations.AddField(
            model_name='raiting_of_players',
            name='win_cnt',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
    ]
