# Generated by Django 3.2.4 on 2021-06-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0006_rename_stand_off_cnt_raiting_of_players_standoff_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiting_of_players',
            name='not_wins',
        ),
        migrations.AlterField(
            model_name='raiting_of_players',
            name='not_win_cnt',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
