# Generated by Django 3.2.4 on 2021-06-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0017_import_command_stuctures_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import_command_stuctures',
            name='attfile',
        ),
        migrations.RemoveField(
            model_name='import_command_stuctures',
            name='file_store',
        ),
        migrations.RemoveField(
            model_name='import_command_stuctures',
            name='format',
        ),
        migrations.RemoveField(
            model_name='import_command_stuctures',
            name='key',
        ),
        migrations.RemoveField(
            model_name='import_command_stuctures',
            name='mime_type',
        ),
        migrations.RemoveField(
            model_name='import_command_stuctures',
            name='real_name',
        ),
        migrations.RemoveField(
            model_name='import_command_stuctures',
            name='size',
        ),
        migrations.AddField(
            model_name='import_command_stuctures',
            name='path',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
