[tool.poetry]
name = "openconnecter"
version = "0.0.1"
description = "Wrapper for initiating an openconnect session"
authors = ["Kamyab Taghizadeh <kamyab.zad@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/kamyabzad/openconnecter"
repository = "https://github.com/kamyabzad/openconnecter"
keywords = ["openconnect", "vpn", "automation"]

[tool.poetry.dependencies]
python = "^3.6"
pyotp = "^2.6.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
openconnecter = "openconnecter.__main__:main"

[tool.black]
line-length = 88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
