name: Build and Push AFQsi Docker Image

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 32768
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: nrdg
        password: ${{secrets.CR_PAT_NRDG}}

    - name: Build, test, and push AFQsi docker image
      run: sh ./afqsi_docker/docker-build.sh \
        "${{github.sha}}" \
        "nrdg"

    - name: Build and push a tagged image
      if: startsWith(github.event.ref, 'refs/tags')
      run: |
        sh ./afqsi_docker/docker-build.sh ${{ github.event.release.tag_name }} nrdg
