# Generated by Django 3.1.6 on 2021-02-18 12:53

import bitfield.models
import django.db.models.deletion
from django.db import migrations, models

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20210218_1253'),
        ('competitions', '0012_auto_20210218_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='club_id_now',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Players_club_id_now', to='competitions.clubs'),
        ),
        migrations.AddField(
            model_name='players',
            name='delayed_lockout_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='players',
            name='medical_admission_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='players',
            name='number',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='players',
            name='club',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Players_club', to='competitions.clubs'),
        ),
        migrations.AlterField(
            model_name='players',
            name='post',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='common.posts'),
        ),
        migrations.AlterField(
            model_name='players',
            name='props',
            field=bitfield.models.BitField((('active', 'active'), ('shadow', 'shadow'), ('blocked', 'blocked'), ('disqualification', 'disqualification'), ('lockout', 'lockout'), ('delayed_lockout', 'delayed_lockout'), ('medical_lockout', 'medical_lockout')), db_index=True, default=1),
        ),
    ]
