# Generated by Django 3.1.6 on 2021-02-18 12:53

import django.db.models.deletion
from django.db import migrations, models

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20210218_1253'),
        ('competitions', '0013_auto_20210218_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='club',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, related_name='Players_club', to='competitions.clubs'),
        ),
        migrations.AlterField(
            model_name='players',
            name='club_id_now',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, related_name='Players_club_id_now', to='competitions.clubs'),
        ),
        migrations.AlterField(
            model_name='players',
            name='delayed_lockout_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='players',
            name='medical_admission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='players',
            name='number',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='players',
            name='post',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='common.posts'),
        ),
    ]
