# Generated by Django 3.1.6 on 2021-02-18 16:07

import bitfield.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('region', '0011_region_text_informations_code'),
        ('isc_common', '0066_auditmodelex'),
        ('common', '0016_auto_20210218_1253'),
        ('competitions', '0028_auto_20210218_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referees',
            fields=[
                ('auditmodelex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='isc_common.auditmodelex')),
                ('props', bitfield.models.BitField((('active', 'active'),), db_index=True, default=1)),
                ('person', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('referee_post', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='common.posts')),
                ('region', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='region.regions')),
            ],
            options={
                'verbose_name': 'Судьи',
            },
            bases=('isc_common.auditmodelex',),
        ),
        migrations.AlterField(
            model_name='cards',
            name='referee',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.referees'),
        ),
    ]
