# Generated by Django 3.1.6 on 2021-03-01 17:28

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0031_auto_20210301_1552'),
        ('competitions', '0053_leagues_links_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagues',
            name='region',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='region.regions'),
        ),
    ]
