# Generated by Django 3.1.6 on 2021-03-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0058_auto_20210302_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_contacts',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
