# Generated by Django 3.1.7 on 2021-03-04 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0064_auto_20210303_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubs_images',
            old_name='club',
            new_name='main_model',
        ),
    ]
