# Generated by Django 3.1.7 on 2021-03-04 08:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0069_auto_20210304_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='old_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=None, size=None, unique=True),
        ),
    ]
