# Generated by Django 3.1.7 on 2021-03-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0073_auto_20210304_0917'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='club_contacts',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='club_contacts',
            constraint=models.UniqueConstraint(condition=models.Q(priority=None), fields=('club', 'person', 'post', 'props'), name='Club_contacts_unique_constraint_0'),
        ),
        migrations.AddConstraint(
            model_name='club_contacts',
            constraint=models.UniqueConstraint(fields=('club', 'person', 'post', 'priority', 'props'), name='Club_contacts_unique_constraint_1'),
        ),
    ]
