# Generated by Django 3.1.7 on 2021-03-05 05:54

import django.utils.timezone
from django.db import migrations, models

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0039_auto_20210304_1418'),
        ('common', '0023_auto_20210303_0942'),
        ('competitions', '0088_auto_20210304_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='referees',
            name='contact',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='user_ext.contacts'),
        ),
        migrations.AddField(
            model_name='referees',
            name='debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Referees_images',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('image', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='common.images')),
                ('main_model', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.referees')),
            ],
            options={
                'verbose_name': 'Кросс таблица',
                'unique_together': {('image', 'main_model')},
            },
        ),
    ]
