# Generated by Django 3.1.7 on 2021-03-05 05:54

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0039_auto_20210304_1418'),
        ('competitions', '0089_auto_20210305_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referees',
            name='contact',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='user_ext.contacts'),
        ),
    ]
