# Generated by Django 3.1.7 on 2021-03-06 14:24

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0117_auto_20210306_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_members',
            name='props',
            field=bitfield.models.BitField((('game_over', 'game_over'),), db_index=True, default=1),
        ),
    ]
