# Generated by Django 3.1.7 on 2021-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0126_auto_20210306_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='number_of_rounds',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='number_of_teams',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='number_of_tours',
            field=models.SmallIntegerField(default=None),
        ),
    ]
