# Generated by Django 3.1.7 on 2021-03-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0128_auto_20210306_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='referees_max',
            field=models.SmallIntegerField(default=None),
        ),
    ]
