# Generated by Django 3.1.7 on 2021-03-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0129_auto_20210306_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='disqualification_condition',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='division_priority',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='division_round',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='number_of_players',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='number_of_rounds',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='number_of_teams',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='number_of_tours',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='rating_rule',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='referees_max',
            field=models.SmallIntegerField(),
        ),
    ]
