# Generated by Django 3.1.7 on 2021-03-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0132_tournament_members_old_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament_members',
            name='tournament',
        ),
    ]
