# Generated by Django 3.1.7 on 2021-03-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0135_auto_20210306_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament_members',
            name='old_ids',
        ),
    ]
