# Generated by Django 3.1.7 on 2021-03-10 06:16

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0163_auto_20210310_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='checked',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='calendar',
            name='technical_defeat',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='props',
            field=bitfield.models.BitField((('protocol', 'protocol'), ('in_archive', 'in_archive'), ('show_stats', 'show_stats'), ('show_empty_cells', 'show_empty_cells')), db_index=True, default=1),
        ),
    ]
