# Generated by Django 3.1.7 on 2021-03-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0164_auto_20210310_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='checked',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='technical_defeat',
            field=models.SmallIntegerField(),
        ),
    ]
