# Generated by Django 3.1.7 on 2021-03-10 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0184_fines_kdk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar_links',
        ),
    ]
