# Generated by Django 3.1.7 on 2021-03-15 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0195_auto_20210315_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referees',
            name='old_ids',
        ),
    ]
