# Generated by Django 3.1.7 on 2021-03-25 09:45

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('isc_common', '0088_auto_20210323_0553'),
        ('competitions', '0207_auto_20210325_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players_text_informations',
            name='text',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.text_informations'),
        ),
    ]
