# Generated by Django 3.1.7 on 2021-03-26 08:49

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('constructions', '0017_auto_20210315_0922'),
        ('competitions', '0211_remove_referees_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='away_formation',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Calendar_away_formation', to='competitions.formation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='division',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='competitions.divisions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='home_formation',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Calendar_home_formation', to='competitions.formation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='referee',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='competitions.referees'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='stadium',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='constructions.stadiums'),
            preserve_default=False,
        ),
    ]
