# Generated by Django 3.1.7 on 2021-03-26 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0213_auto_20210326_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='checked',
        ),
    ]
