# Generated by Django 3.1.7 on 2021-03-30 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('isc_common', '0090_auto_20210326_0949'),
        ('competitions', '0227_auto_20210330_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fines',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='fines',
            name='deliting',
        ),
        migrations.RemoveField(
            model_name='fines',
            name='editing',
        ),
        migrations.RemoveField(
            model_name='fines',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='fines',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fines',
            name='lastmodified',
        ),
        migrations.RemoveField(
            model_name='fouls',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='fouls',
            name='deliting',
        ),
        migrations.RemoveField(
            model_name='fouls',
            name='editing',
        ),
        migrations.RemoveField(
            model_name='fouls',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='fouls',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fouls',
            name='lastmodified',
        ),
        migrations.RemoveField(
            model_name='keepers',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='keepers',
            name='deliting',
        ),
        migrations.RemoveField(
            model_name='keepers',
            name='editing',
        ),
        migrations.RemoveField(
            model_name='keepers',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='keepers',
            name='id',
        ),
        migrations.RemoveField(
            model_name='keepers',
            name='lastmodified',
        ),
        migrations.AddField(
            model_name='fines',
            name='auditmodelex_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='isc_common.auditmodelex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fouls',
            name='auditmodelex_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='isc_common.auditmodelex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keepers',
            name='auditmodelex_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='isc_common.auditmodelex'),
            preserve_default=False,
        ),
    ]
