# Generated by Django 3.2 on 2021-04-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0251_club_contacts_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisions',
            name='scheme',
            field=models.CharField(null=True, blank=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divisions',
            name='top_text',
            field=models.TextField(null=True, blank=True),
            preserve_default=False,
        ),
    ]
