# Generated by Django 3.2 on 2021-04-11 19:42

import django.db.models.deletion
import isc_common.fields.related
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0253_club_admins_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_contacts',
            name='club',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.clubs'),
        ),
    ]
