# Generated by Django 3.1.8 on 2021-04-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0274_auto_20210423_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_member_doubles',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
