# Generated by Django 3.2.4 on 2021-06-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0285_rename_club_id_now_players_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_histories',
            name='club_id_old',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='player_histories',
            name='match_id_old',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='player_histories',
            name='player_id_old',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
