# Generated by Django 3.2.4 on 2021-06-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0294_calendar_view_referees_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_histories',
            name='num',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
