# Generated by Django 3.2.4 on 2021-06-28 15:38

from django.db import migrations, models
import django.utils.timezone
import isc_common.fields.code_field
import isc_common.fields.name_field


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0296_auto_20210628_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command_structure_view',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('num', isc_common.fields.code_field.CodeField(blank=True, null=True)),
                ('photo_image_src', isc_common.fields.name_field.NameField(blank=True, null=True)),
                ('photo_real_name', isc_common.fields.name_field.NameField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Состав комманды',
                'db_table': 'competitions_command_structure_view',
                'managed': False,
            },
        ),
    ]
