# Generated by Django 3.2.4 on 2021-06-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0303_command_structure_tmp_player_histories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command_structure_tmp',
            name='active',
        ),
    ]
