# Generated by Django 3.2.4 on 2021-06-29 12:28

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0304_remove_command_structure_tmp_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='command_structure_tmp',
            name='props',
            field=bitfield.models.BitField((('game_started', 'game_started'), ('substituted', 'substituted'), ('keeper', 'keeper'), ('hidden', 'Скрывать ФИО')), db_index=True, default=0),
        ),
    ]
