# Generated by Django 3.2.6 on 2021-08-18 09:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import isc_common.fields.code_field
import isc_common.fields.description_field
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0316_alter_divisions_props'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments_division_view',
            fields=[
                ('old_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('code', isc_common.fields.code_field.CodeStrictField()),
                ('description', isc_common.fields.description_field.DescriptionField()),
                ('active', models.BooleanField()),
                ('favorites', models.BooleanField()),
                ('hidden', models.BooleanField()),
                ('is_division', models.BooleanField()),
                ('isFolder', models.BooleanField()),
                ('name', isc_common.fields.code_field.CodeField(blank=True, null=True)),
                ('number_of_rounds', models.SmallIntegerField()),
                ('number_of_teams', models.SmallIntegerField(blank=True, null=True)),
                ('priority', models.SmallIntegerField(blank=True, null=True)),
                ('real_id', models.BigIntegerField(db_index=True)),
            ],
            options={
                'verbose_name': 'Турниры объединенные с супе турнирами',
                'db_table': 'competitions_tournaments_division_view',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='division',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competitions.divisions'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='division_priority',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
