# Generated by Django 3.2.6 on 2021-08-19 13:49

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0324_rating_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='rating_rule1',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competitions.rating_rule'),
        ),
    ]
