# Generated by Django 3.2.6 on 2021-08-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0349_alter_divisions_disqualification_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='division_priority',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
