# Generated by Django 3.2.6 on 2021-08-31 14:21

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0358_auto_20210831_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagues',
            name='props',
            field=bitfield.models.BitField((('active', 'active'), ('parimatch', 'parimatch'), ('submenu', 'Убрать submenu'), ('nonphoto', 'Разрешить заявки без фото'), ('show_in_menu', 'Показывать в правом меню'), ('show_referee_photo_in_protocols', 'Показывать фото судей в протоколах'), ('show_stadium_photo_in_protocols', 'Показывать фото стадиона в протоколах'), ('show_shirt_in_protocols', 'Показывать майки в протоколах')), db_index=True, default=1),
        ),
    ]
