# Generated by Django 3.2.6 on 2021-09-01 16:36

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0372_alter_clubs_interregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='props',
            field=bitfield.models.BitField((('active', 'Блокировать клуб'), ('national', 'Сборная команда')), db_index=True, default=1),
        ),
    ]
