# Generated by Django 3.2.7 on 2021-09-10 19:14

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0382_alter_match_stats_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_stats',
            name='match',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='competitions.calendar'),
        ),
    ]
