# Generated by Django 3.2.7 on 2021-09-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0390_auto_20210914_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squads',
            name='old_id',
        ),
        migrations.AddField(
            model_name='squads',
            name='club_id_old',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='squads',
            name='player_id_old',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='squads',
            name='tournament_id_old',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
