[tool.poetry]
name = "mjms"
version = "0.1.1"
description = "A python client for mailsrv.marcusj.tech"
authors = ["Marcus Weinberger <marcus@marcusweinberger.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
