[tool.poetry]
name = "exiot"
version = "0.1.1"
description = "The 'exiot' is a testing tool to test the executable STDIN, STDOUT, STDERR, and many more."
authors = [
    "Peter Stanko <peter.stanko0@gmail.com>"
]
readme = 'README.md'
license = 'Apache-2.0'
repository = 'https://github.com/pestanko/exiot'
homepage = 'https://github.com/pestanko/exiot'
documentation = 'https://github.com/pestanko/exiot'

[tool.poetry.scripts]
exiot = "exiot:main"

[tool.poetry.dependencies]
python = "^3.8"
junitparser = "*"
PyYAML = "^5.4.1"

[tool.poetry.dev-dependencies]
pytest = "^6"
pytest-cov = "^2.12.1"
coverage = "^6.0.2"
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
