# Generated by Django 3.1.6 on 2021-02-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_lfl_images',
            name='path',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
