# Generated by Django 3.2.6 on 2021-08-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_delete_all_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_tables',
            fields=[
                ('table_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Все пользовательские таблицы',
                'db_table': 'all_tables',
                'managed': False,
            },
        ),
    ]
