SHOW DATABASES;
CREATE DATABASE cars;
USE cars;
CREATE TABLE customers (
id INT(11) AUTO_INCREMENT,
Name VARCHAR(50) NOT NULL,
Address VARCHAR(255) NULL,
Phone VARCHAR(10) NULL,
PRIMARY KEY(id)
) ENGINE = InnoDB
CHARACTER SET = utf8
COLLATE = utf8_unicode_ci ;