#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['aiohere']

package_data = \
{'': ['*']}

install_requires = \
['aiohttp>=3.7.4']

extras_require = \
{'test': ['aresponses==2.1.4',
          'pytest==6.2.3',
          'pytest-cov==2.11.1',
          'pytest-asyncio==0.14.0',
          'pylint==2.7.4',
          'tox==3.23.0',
          'codecov==2.1.11',
          'flake8==3.9.0',
          'mypy==0.812',
          'pre-commit==2.12.0',
          'black==20.8b1']}

setup(name='aiohere',
      version='1.3.0',
      description='Asynchronous Python client for the HERE API.',
      author='eifinger',
      author_email='kevin.stillhammer@gmail.com',
      url='http://github.com/eifinger/aiohere',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.8',
     )
