[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pylint_aiida"
authors = [{name = "Chris Sewell", email = "aiidateam@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dynamic = ["version", "description"]
requires-python = ">=3.7"
dependencies = ["astroid"]

[project.optional-dependencies]
test = ["pytest"]

[project.urls]
Home = "https://github.com/aiidateam/pylint-aiida"

[tool.flit.sdist]
include = ["LICENSE", "README.md"]
exclude = [".github/", "tests/"]

[tool.isort]
profile = "black"
