[tool.poetry]
name = "redasql"
version = "0.0.9"
description = "RedaSQL is query cli tool for redash."
authors = ["denzow <denzow@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"
prettytable = "^2.2.0"
prompt-toolkit = "^3.0.20"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
redasql = "redasql.command:main"
