[tool.poetry]
name = "rasa_extractors"
version = "0.1.1"
description = ""
authors = ["4thel00z <4thel00z@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/4thel00z/rasa_extractors"
packages = [
    { include = "rasa_extractors" }
]


[tool.poetry.dependencies]
python = ">=3.8,<3.9"
rasa = "2.8.8"
flashtext = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
