parameters:
  pysparkbundle:
    filesystem: dummy_filesystem

services:
  jupyterbundle.test.DummySparkFactory:

  pyspark.sql.session.SparkSession:
    factory: ['@jupyterbundle.test.DummySparkFactory', 'create']

  pysparkbundle.filesystem.DummyFilesystem:
    tags:
      - {name: 'pysparkbundle.filesystem', alias: dummy_filesystem}
