# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1132, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.kdialog = QtWidgets.QDialog(self.centralwidget)
        self.kdialog.setObjectName("kdialog")
        self.gridLayout.addWidget(self.kdialog, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_FS = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_FS.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_FS.setText("")
        self.lineEdit_FS.setObjectName("lineEdit_FS")
        self.horizontalLayout.addWidget(self.lineEdit_FS)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setWhatsThis("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_RS = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_RS.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_RS.setObjectName("lineEdit_RS")
        self.horizontalLayout.addWidget(self.lineEdit_RS)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.lineEditSearch = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSearch.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.horizontalLayout.addWidget(self.lineEditSearch)
        self.btnSearchClear = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme("edit-clear")
        self.btnSearchClear.setIcon(icon)
        self.btnSearchClear.setObjectName("btnSearchClear")
        self.horizontalLayout.addWidget(self.btnSearchClear)
        self.btnSearch = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme("search")
        self.btnSearch.setIcon(icon)
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout.addWidget(self.btnSearch)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.text = QtWidgets.QWidget()
        self.text.setObjectName("text")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.text)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.text)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.text, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_4.addWidget(self.listWidget, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_3.addWidget(self.textEdit, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCommands = QtWidgets.QMenu(self.menubar)
        self.menuCommands.setObjectName("menuCommands")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuStats = QtWidgets.QMenu(self.menubar)
        self.menuStats.setObjectName("menuStats")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(True)
        self.actionSave.setObjectName("actionSave")
        self.actionRawData = QtWidgets.QAction(MainWindow)
        self.actionRawData.setCheckable(True)
        self.actionRawData.setChecked(True)
        self.actionRawData.setObjectName("actionRawData")
        self.actionDailySum = QtWidgets.QAction(MainWindow)
        self.actionDailySum.setCheckable(True)
        self.actionDailySum.setObjectName("actionDailySum")
        self.actionEgrep = QtWidgets.QAction(MainWindow)
        self.actionEgrep.setObjectName("actionEgrep")
        self.actionHead = QtWidgets.QAction(MainWindow)
        self.actionHead.setObjectName("actionHead")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionTail = QtWidgets.QAction(MainWindow)
        self.actionTail.setObjectName("actionTail")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionKeepOneLine = QtWidgets.QAction(MainWindow)
        self.actionKeepOneLine.setObjectName("actionKeepOneLine")
        self.actionWhere = QtWidgets.QAction(MainWindow)
        self.actionWhere.setObjectName("actionWhere")
        self.actionSelectFields = QtWidgets.QAction(MainWindow)
        self.actionSelectFields.setObjectName("actionSelectFields")
        self.actionSubstitute = QtWidgets.QAction(MainWindow)
        self.actionSubstitute.setObjectName("actionSubstitute")
        self.actionSort = QtWidgets.QAction(MainWindow)
        self.actionSort.setObjectName("actionSort")
        self.actionCustom = QtWidgets.QAction(MainWindow)
        self.actionCustom.setObjectName("actionCustom")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionCount = QtWidgets.QAction(MainWindow)
        self.actionCount.setObjectName("actionCount")
        self.actionAppendField = QtWidgets.QAction(MainWindow)
        self.actionAppendField.setObjectName("actionAppendField")
        self.actionTranspose = QtWidgets.QAction(MainWindow)
        self.actionTranspose.setObjectName("actionTranspose")
        self.actionMean = QtWidgets.QAction(MainWindow)
        self.actionMean.setObjectName("actionMean")
        self.actionMax = QtWidgets.QAction(MainWindow)
        self.actionMax.setObjectName("actionMax")
        self.actionMin = QtWidgets.QAction(MainWindow)
        self.actionMin.setObjectName("actionMin")
        self.actionSum = QtWidgets.QAction(MainWindow)
        self.actionSum.setObjectName("actionSum")
        self.actionTable = QtWidgets.QAction(MainWindow)
        self.actionTable.setObjectName("actionTable")
        self.actionHistogram = QtWidgets.QAction(MainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.actionPadding = QtWidgets.QAction(MainWindow)
        self.actionPadding.setObjectName("actionPadding")
        self.actionAutoPadding = QtWidgets.QAction(MainWindow)
        self.actionAutoPadding.setObjectName("actionAutoPadding")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuCommands.addAction(self.actionEgrep)
        self.menuCommands.addAction(self.actionHead)
        self.menuCommands.addAction(self.actionTail)
        self.menuCommands.addAction(self.actionCut)
        self.menuCommands.addAction(self.actionSort)
        self.menuCommands.addAction(self.actionCustom)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuHelp.addAction(self.actionAbout)
        self.menuTools.addAction(self.actionAppendField)
        self.menuTools.addAction(self.actionSelectFields)
        self.menuTools.addAction(self.actionKeepOneLine)
        self.menuTools.addAction(self.actionWhere)
        self.menuTools.addAction(self.actionSubstitute)
        self.menuTools.addAction(self.actionTranspose)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionTable)
        self.menuTools.addAction(self.actionPadding)
        self.menuTools.addAction(self.actionAutoPadding)
        self.menuStats.addAction(self.actionCount)
        self.menuStats.addAction(self.actionMin)
        self.menuStats.addAction(self.actionMax)
        self.menuStats.addAction(self.actionMean)
        self.menuStats.addAction(self.actionSum)
        self.menuStats.addAction(self.actionHistogram)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuCommands.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuStats.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "qtawk"))
        self.label.setToolTip(_translate("MainWindow", "Field Separator"))
        self.label.setText(_translate("MainWindow", "FS"))
        self.label_2.setToolTip(_translate("MainWindow", "Record Separator"))
        self.label_2.setText(_translate("MainWindow", "RS"))
        self.lineEdit_RS.setText(_translate("MainWindow", "\\n"))
        self.btnSearchClear.setToolTip(_translate("MainWindow", "erase"))
        self.btnSearchClear.setText(_translate("MainWindow", "..."))
        self.btnSearch.setToolTip(_translate("MainWindow", "search/next"))
        self.btnSearch.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.text), _translate("MainWindow", "text"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Commands list"))
        self.groupBox.setTitle(_translate("MainWindow", "OneLiner"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "script"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuCommands.setTitle(_translate("MainWindow", "&Commands"))
        self.menuEdit.setTitle(_translate("MainWindow", "E&dit"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.menuTools.setTitle(_translate("MainWindow", "&Tools"))
        self.menuStats.setTitle(_translate("MainWindow", "&Stats"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save as..."))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionRawData.setText(_translate("MainWindow", "raw data"))
        self.actionDailySum.setText(_translate("MainWindow", "daily sum"))
        self.actionEgrep.setText(_translate("MainWindow", "egrep"))
        self.actionHead.setText(_translate("MainWindow", "head"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionExport.setText(_translate("MainWindow", "Export output as..."))
        self.actionExport.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionTail.setText(_translate("MainWindow", "tail"))
        self.actionCut.setText(_translate("MainWindow", "cut"))
        self.actionKeepOneLine.setText(_translate("MainWindow", "keep one line"))
        self.actionWhere.setText(_translate("MainWindow", "where"))
        self.actionSelectFields.setText(_translate("MainWindow", "select fields"))
        self.actionSubstitute.setText(_translate("MainWindow", "substitute"))
        self.actionSort.setText(_translate("MainWindow", "sort"))
        self.actionCustom.setText(_translate("MainWindow", "custom command"))
        self.actionImport.setText(_translate("MainWindow", "Import raw data"))
        self.actionImport.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionCount.setText(_translate("MainWindow", "count"))
        self.actionAppendField.setText(_translate("MainWindow", "append field"))
        self.actionTranspose.setText(_translate("MainWindow", "transpose"))
        self.actionMean.setText(_translate("MainWindow", "mean"))
        self.actionMax.setText(_translate("MainWindow", "max"))
        self.actionMin.setText(_translate("MainWindow", "min"))
        self.actionSum.setText(_translate("MainWindow", "sum"))
        self.actionTable.setText(_translate("MainWindow", "table"))
        self.actionHistogram.setText(_translate("MainWindow", "histogram"))
        self.actionPadding.setText(_translate("MainWindow", "padding"))
        self.actionAutoPadding.setText(_translate("MainWindow", "padding auto"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

