[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "fastapi_rapidoc"
authors = [{name = "Mawoka", email = "mawoka-myblock@e.email"}]
dynamic = ["version", "description"]
