
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-19T12:57:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2645cc51f84ad5eda43b9c673400aada8e1505a",
 "version": "v2.3.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
