VERSION_YEAR = 2021
VERSION_MONTH = int('10')
VERSION_DAY = int('25')
VERSION_HOUR = int('13')
VERSION_MINUTE = int('42')
MAJOR_VERSION = 2
MINOR_VERSION = 4
PATCH_VERSION = 202110251342
version_date = '2021/10/25 13:42'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
