[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "matplotlib",
    "wxpython",
    "pyopengl",
    "pandas",
    "scipy"
]
build-backend = "setuptools.build_meta"