[tool.poetry]
name = "miningpoolhub_py"
version = "0.1.11"
description = "A Python wrapper for the Mining Pool Hub REST API"
authors = ["CoryKrol <16892390+CoryKrol@users.noreply.github.com>"]
license = "Apache 2"
readme = "README.rst"
homepage = "https://github.com/CoryKrol/miningpoolhub_py"
repository = "https://github.com/CoryKrol/miningpoolhub_py"

include = [
    "LICENSE.md",
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"
python-dotenv = "^0.19.1"
Sphinx = { version = "^4.2.0", optional = true }
sphinx-rtd-theme = { version = "^1.0.0", optional = true }
sphinxcontrib-napoleon = { version = "^0.7", optional = true }
pytest-recording = "^0.12.0"

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-rtd-theme", "sphinxcontrib-napoleon"]

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-recording = "^0.12.0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
