
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-20T17:28:43+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "67671d615d9534ebc963afe33752a3e967170087",
 "version": "0.9.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
