[tool.poetry]
name = "circular-client"
version = "0.1.2"
description = ""
authors = ["CircularNetwork <info@circularnetwork.io>"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.23.0"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
