[tool.poetry]
name = "figur"
version = "0.1.0"
description = ""
authors = ["Neil Hansen <neil.hansen.31@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
hy = "^0.20.0"
rich = "^10.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
