# coding: utf-8

"""
    Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference

    <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v6/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v6
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from yahoo_display_api.configuration import Configuration


class GuaranteedSimulationServicePackage(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'package_id': 'int',
        'package_history_id': 'int',
        'package_name': 'str',
        'selling_start_date': 'str',
        'selling_end_date': 'str',
        'ad_delivery_duration_start_date': 'str',
        'reservation_start_date': 'str',
        'reservation_end_date': 'str',
        'ad_delivery_duration_end_date': 'str',
        'buying_term': 'GuaranteedSimulationServiceBuyingTerm',
        'pricing_package': 'GuaranteedSimulationServicePricingPackage',
        'package_public_level': 'GuaranteedSimulationServicePackagePublicLevel',
        'sales_document': 'GuaranteedSimulationServiceSalesDocument',
        'promotional_document': 'GuaranteedSimulationServicePromotionalDocument',
        'related_document': 'GuaranteedSimulationServiceRelatedDocument',
        'ad_requirements': 'list[GuaranteedSimulationServiceAdRequirement]',
        'action_after_video_ad_tap': 'GuaranteedSimulationServiceActionAfterVideoAdTap',
        'instream_duration_type': 'GuaranteedSimulationServiceInstreamDurationType',
        'remarks': 'str',
        'package_permitted_viewable_frequency_cap': 'GuaranteedSimulationServicePackagePermittedViewableFrequencyCap',
        'package_permitted_ad_place_types': 'GuaranteedSimulationServicePackagePermittedAdPlaceTypes',
        'package_permitted_gender_target': 'GuaranteedSimulationServicePackagePermittedGenderTarget',
        'package_permitted_age_target': 'GuaranteedSimulationServicePackagePermittedAgeTarget',
        'package_permitted_audience_category_target': 'GuaranteedSimulationServicePackagePermittedAudienceCategoryTarget',
        'package_permitted_geo_target': 'GuaranteedSimulationServicePackagePermittedGeoTarget',
        'package_permitted_ad_schedule_target': 'GuaranteedSimulationServicePackagePermittedAdScheduleTarget',
        'package_permitted_device_target': 'GuaranteedSimulationServicePackagePermittedDeviceTarget',
        'package_permitted_os_target': 'GuaranteedSimulationServicePackagePermittedOsTarget',
        'package_permitted_app_target': 'GuaranteedSimulationServicePackagePermittedAppTarget',
        'package_permitted_placement_category_target': 'GuaranteedSimulationServicePackagePermittedPlacementCategoryTarget',
        'package_permitted_position_target': 'GuaranteedSimulationServicePackagePermittedPositionTarget',
        'package_permitted_site_retargeting_target': 'GuaranteedSimulationServicePackagePermittedSiteRetargetingTarget'
    }

    attribute_map = {
        'package_id': 'packageId',
        'package_history_id': 'packageHistoryId',
        'package_name': 'packageName',
        'selling_start_date': 'sellingStartDate',
        'selling_end_date': 'sellingEndDate',
        'ad_delivery_duration_start_date': 'adDeliveryDurationStartDate',
        'reservation_start_date': 'reservationStartDate',
        'reservation_end_date': 'reservationEndDate',
        'ad_delivery_duration_end_date': 'adDeliveryDurationEndDate',
        'buying_term': 'buyingTerm',
        'pricing_package': 'pricingPackage',
        'package_public_level': 'packagePublicLevel',
        'sales_document': 'salesDocument',
        'promotional_document': 'promotionalDocument',
        'related_document': 'relatedDocument',
        'ad_requirements': 'adRequirements',
        'action_after_video_ad_tap': 'actionAfterVideoAdTap',
        'instream_duration_type': 'instreamDurationType',
        'remarks': 'remarks',
        'package_permitted_viewable_frequency_cap': 'packagePermittedViewableFrequencyCap',
        'package_permitted_ad_place_types': 'packagePermittedAdPlaceTypes',
        'package_permitted_gender_target': 'packagePermittedGenderTarget',
        'package_permitted_age_target': 'packagePermittedAgeTarget',
        'package_permitted_audience_category_target': 'packagePermittedAudienceCategoryTarget',
        'package_permitted_geo_target': 'packagePermittedGeoTarget',
        'package_permitted_ad_schedule_target': 'packagePermittedAdScheduleTarget',
        'package_permitted_device_target': 'packagePermittedDeviceTarget',
        'package_permitted_os_target': 'packagePermittedOsTarget',
        'package_permitted_app_target': 'packagePermittedAppTarget',
        'package_permitted_placement_category_target': 'packagePermittedPlacementCategoryTarget',
        'package_permitted_position_target': 'packagePermittedPositionTarget',
        'package_permitted_site_retargeting_target': 'packagePermittedSiteRetargetingTarget'
    }

    def __init__(self, package_id=None, package_history_id=None, package_name=None, selling_start_date=None, selling_end_date=None, ad_delivery_duration_start_date=None, reservation_start_date=None, reservation_end_date=None, ad_delivery_duration_end_date=None, buying_term=None, pricing_package=None, package_public_level=None, sales_document=None, promotional_document=None, related_document=None, ad_requirements=None, action_after_video_ad_tap=None, instream_duration_type=None, remarks=None, package_permitted_viewable_frequency_cap=None, package_permitted_ad_place_types=None, package_permitted_gender_target=None, package_permitted_age_target=None, package_permitted_audience_category_target=None, package_permitted_geo_target=None, package_permitted_ad_schedule_target=None, package_permitted_device_target=None, package_permitted_os_target=None, package_permitted_app_target=None, package_permitted_placement_category_target=None, package_permitted_position_target=None, package_permitted_site_retargeting_target=None, local_vars_configuration=None):  # noqa: E501
        """GuaranteedSimulationServicePackage - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._package_id = None
        self._package_history_id = None
        self._package_name = None
        self._selling_start_date = None
        self._selling_end_date = None
        self._ad_delivery_duration_start_date = None
        self._reservation_start_date = None
        self._reservation_end_date = None
        self._ad_delivery_duration_end_date = None
        self._buying_term = None
        self._pricing_package = None
        self._package_public_level = None
        self._sales_document = None
        self._promotional_document = None
        self._related_document = None
        self._ad_requirements = None
        self._action_after_video_ad_tap = None
        self._instream_duration_type = None
        self._remarks = None
        self._package_permitted_viewable_frequency_cap = None
        self._package_permitted_ad_place_types = None
        self._package_permitted_gender_target = None
        self._package_permitted_age_target = None
        self._package_permitted_audience_category_target = None
        self._package_permitted_geo_target = None
        self._package_permitted_ad_schedule_target = None
        self._package_permitted_device_target = None
        self._package_permitted_os_target = None
        self._package_permitted_app_target = None
        self._package_permitted_placement_category_target = None
        self._package_permitted_position_target = None
        self._package_permitted_site_retargeting_target = None
        self.discriminator = None

        if package_id is not None:
            self.package_id = package_id
        if package_history_id is not None:
            self.package_history_id = package_history_id
        if package_name is not None:
            self.package_name = package_name
        self.selling_start_date = selling_start_date
        self.selling_end_date = selling_end_date
        self.ad_delivery_duration_start_date = ad_delivery_duration_start_date
        self.reservation_start_date = reservation_start_date
        self.reservation_end_date = reservation_end_date
        self.ad_delivery_duration_end_date = ad_delivery_duration_end_date
        self.buying_term = buying_term
        self.pricing_package = pricing_package
        self.package_public_level = package_public_level
        self.sales_document = sales_document
        self.promotional_document = promotional_document
        self.related_document = related_document
        self.ad_requirements = ad_requirements
        self.action_after_video_ad_tap = action_after_video_ad_tap
        self.instream_duration_type = instream_duration_type
        if remarks is not None:
            self.remarks = remarks
        self.package_permitted_viewable_frequency_cap = package_permitted_viewable_frequency_cap
        self.package_permitted_ad_place_types = package_permitted_ad_place_types
        self.package_permitted_gender_target = package_permitted_gender_target
        self.package_permitted_age_target = package_permitted_age_target
        self.package_permitted_audience_category_target = package_permitted_audience_category_target
        self.package_permitted_geo_target = package_permitted_geo_target
        self.package_permitted_ad_schedule_target = package_permitted_ad_schedule_target
        self.package_permitted_device_target = package_permitted_device_target
        self.package_permitted_os_target = package_permitted_os_target
        self.package_permitted_app_target = package_permitted_app_target
        self.package_permitted_placement_category_target = package_permitted_placement_category_target
        self.package_permitted_position_target = package_permitted_position_target
        self.package_permitted_site_retargeting_target = package_permitted_site_retargeting_target

    @property
    def package_id(self):
        """Gets the package_id of this GuaranteedSimulationServicePackage.  # noqa: E501

        <div lang=\"ja\">商品IDです。</div> <div lang=\"en\">Package ID.</div>   # noqa: E501

        :return: The package_id of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: int
        """
        return self._package_id

    @package_id.setter
    def package_id(self, package_id):
        """Sets the package_id of this GuaranteedSimulationServicePackage.

        <div lang=\"ja\">商品IDです。</div> <div lang=\"en\">Package ID.</div>   # noqa: E501

        :param package_id: The package_id of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: int
        """

        self._package_id = package_id

    @property
    def package_history_id(self):
        """Gets the package_history_id of this GuaranteedSimulationServicePackage.  # noqa: E501

        <div lang=\"ja\">商品履歴IDです。</div> <div lang=\"en\">Package history ID.</div>   # noqa: E501

        :return: The package_history_id of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: int
        """
        return self._package_history_id

    @package_history_id.setter
    def package_history_id(self, package_history_id):
        """Sets the package_history_id of this GuaranteedSimulationServicePackage.

        <div lang=\"ja\">商品履歴IDです。</div> <div lang=\"en\">Package history ID.</div>   # noqa: E501

        :param package_history_id: The package_history_id of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: int
        """

        self._package_history_id = package_history_id

    @property
    def package_name(self):
        """Gets the package_name of this GuaranteedSimulationServicePackage.  # noqa: E501

        <div lang=\"ja\">商品名です。</div> <div lang=\"en\">Package name.</div>   # noqa: E501

        :return: The package_name of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: str
        """
        return self._package_name

    @package_name.setter
    def package_name(self, package_name):
        """Sets the package_name of this GuaranteedSimulationServicePackage.

        <div lang=\"ja\">商品名です。</div> <div lang=\"en\">Package name.</div>   # noqa: E501

        :param package_name: The package_name of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: str
        """

        self._package_name = package_name

    @property
    def selling_start_date(self):
        """Gets the selling_start_date of this GuaranteedSimulationServicePackage.  # noqa: E501

        <div lang=\"ja\">   商品開始日です。<br>   ※フォーマット：yyyyMMdd </div> <div lang=\"en\">   Start date of the package.<br>   Format: yyyyMMdd </div>   # noqa: E501

        :return: The selling_start_date of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: str
        """
        return self._selling_start_date

    @selling_start_date.setter
    def selling_start_date(self, selling_start_date):
        """Sets the selling_start_date of this GuaranteedSimulationServicePackage.

        <div lang=\"ja\">   商品開始日です。<br>   ※フォーマット：yyyyMMdd </div> <div lang=\"en\">   Start date of the package.<br>   Format: yyyyMMdd </div>   # noqa: E501

        :param selling_start_date: The selling_start_date of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: str
        """

        self._selling_start_date = selling_start_date

    @property
    def selling_end_date(self):
        """Gets the selling_end_date of this GuaranteedSimulationServicePackage.  # noqa: E501

        <div lang=\"ja\">   商品終了日です。<br>   ※フォーマット：yyyyMMdd </div> <div lang=\"en\">   End date of the package.<br>   Format: yyyyMMdd </div>   # noqa: E501

        :return: The selling_end_date of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: str
        """
        return self._selling_end_date

    @selling_end_date.setter
    def selling_end_date(self, selling_end_date):
        """Sets the selling_end_date of this GuaranteedSimulationServicePackage.

        <div lang=\"ja\">   商品終了日です。<br>   ※フォーマット：yyyyMMdd </div> <div lang=\"en\">   End date of the package.<br>   Format: yyyyMMdd </div>   # noqa: E501

        :param selling_end_date: The selling_end_date of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: str
        """

        self._selling_end_date = selling_end_date

    @property
    def ad_delivery_duration_start_date(self):
        """Gets the ad_delivery_duration_start_date of this GuaranteedSimulationServicePackage.  # noqa: E501

        <div lang=\"ja\">   広告の掲載有効期間の開始日です。<br>   ※フォーマット：yyyyMMdd </div> <div lang=\"en\">   Start date of the ad delivery validity period.<br>   Format: yyyyMMdd </div>   # noqa: E501

        :return: The ad_delivery_duration_start_date of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: str
        """
        return self._ad_delivery_duration_start_date

    @ad_delivery_duration_start_date.setter
    def ad_delivery_duration_start_date(self, ad_delivery_duration_start_date):
        """Sets the ad_delivery_duration_start_date of this GuaranteedSimulationServicePackage.

        <div lang=\"ja\">   広告の掲載有効期間の開始日です。<br>   ※フォーマット：yyyyMMdd </div> <div lang=\"en\">   Start date of the ad delivery validity period.<br>   Format: yyyyMMdd </div>   # noqa: E501

        :param ad_delivery_duration_start_date: The ad_delivery_duration_start_date of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: str
        """

        self._ad_delivery_duration_start_date = ad_delivery_duration_start_date

    @property
    def reservation_start_date(self):
        """Gets the reservation_start_date of this GuaranteedSimulationServicePackage.  # noqa: E501

        <div lang=\"ja\">   予約期間開始日です。<br>   ※フォーマット：yyyyMMdd </div> <div lang=\"en\">   Start date of reservation period.<br>   Format: yyyyMMdd </div>   # noqa: E501

        :return: The reservation_start_date of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: str
        """
        return self._reservation_start_date

    @reservation_start_date.setter
    def reservation_start_date(self, reservation_start_date):
        """Sets the reservation_start_date of this GuaranteedSimulationServicePackage.

        <div lang=\"ja\">   予約期間開始日です。<br>   ※フォーマット：yyyyMMdd </div> <div lang=\"en\">   Start date of reservation period.<br>   Format: yyyyMMdd </div>   # noqa: E501

        :param reservation_start_date: The reservation_start_date of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: str
        """

        self._reservation_start_date = reservation_start_date

    @property
    def reservation_end_date(self):
        """Gets the reservation_end_date of this GuaranteedSimulationServicePackage.  # noqa: E501

        <div lang=\"ja\">   予約期間終了日です。<br>   ※フォーマット：yyyyMMdd </div> <div lang=\"en\">   End date of reservation period.<br>   Format: yyyyMMdd </div>   # noqa: E501

        :return: The reservation_end_date of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: str
        """
        return self._reservation_end_date

    @reservation_end_date.setter
    def reservation_end_date(self, reservation_end_date):
        """Sets the reservation_end_date of this GuaranteedSimulationServicePackage.

        <div lang=\"ja\">   予約期間終了日です。<br>   ※フォーマット：yyyyMMdd </div> <div lang=\"en\">   End date of reservation period.<br>   Format: yyyyMMdd </div>   # noqa: E501

        :param reservation_end_date: The reservation_end_date of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: str
        """

        self._reservation_end_date = reservation_end_date

    @property
    def ad_delivery_duration_end_date(self):
        """Gets the ad_delivery_duration_end_date of this GuaranteedSimulationServicePackage.  # noqa: E501

        <div lang=\"ja\">   掲載有効期間の終了日です。<br>   ※フォーマット：yyyyMMdd </div> <div lang=\"en\">   End date of the ad delivery validity period.<br>   Format: yyyyMMdd </div>   # noqa: E501

        :return: The ad_delivery_duration_end_date of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: str
        """
        return self._ad_delivery_duration_end_date

    @ad_delivery_duration_end_date.setter
    def ad_delivery_duration_end_date(self, ad_delivery_duration_end_date):
        """Sets the ad_delivery_duration_end_date of this GuaranteedSimulationServicePackage.

        <div lang=\"ja\">   掲載有効期間の終了日です。<br>   ※フォーマット：yyyyMMdd </div> <div lang=\"en\">   End date of the ad delivery validity period.<br>   Format: yyyyMMdd </div>   # noqa: E501

        :param ad_delivery_duration_end_date: The ad_delivery_duration_end_date of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: str
        """

        self._ad_delivery_duration_end_date = ad_delivery_duration_end_date

    @property
    def buying_term(self):
        """Gets the buying_term of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The buying_term of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServiceBuyingTerm
        """
        return self._buying_term

    @buying_term.setter
    def buying_term(self, buying_term):
        """Sets the buying_term of this GuaranteedSimulationServicePackage.


        :param buying_term: The buying_term of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServiceBuyingTerm
        """

        self._buying_term = buying_term

    @property
    def pricing_package(self):
        """Gets the pricing_package of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The pricing_package of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePricingPackage
        """
        return self._pricing_package

    @pricing_package.setter
    def pricing_package(self, pricing_package):
        """Sets the pricing_package of this GuaranteedSimulationServicePackage.


        :param pricing_package: The pricing_package of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePricingPackage
        """

        self._pricing_package = pricing_package

    @property
    def package_public_level(self):
        """Gets the package_public_level of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The package_public_level of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePackagePublicLevel
        """
        return self._package_public_level

    @package_public_level.setter
    def package_public_level(self, package_public_level):
        """Sets the package_public_level of this GuaranteedSimulationServicePackage.


        :param package_public_level: The package_public_level of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePackagePublicLevel
        """

        self._package_public_level = package_public_level

    @property
    def sales_document(self):
        """Gets the sales_document of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The sales_document of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServiceSalesDocument
        """
        return self._sales_document

    @sales_document.setter
    def sales_document(self, sales_document):
        """Sets the sales_document of this GuaranteedSimulationServicePackage.


        :param sales_document: The sales_document of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServiceSalesDocument
        """

        self._sales_document = sales_document

    @property
    def promotional_document(self):
        """Gets the promotional_document of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The promotional_document of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePromotionalDocument
        """
        return self._promotional_document

    @promotional_document.setter
    def promotional_document(self, promotional_document):
        """Sets the promotional_document of this GuaranteedSimulationServicePackage.


        :param promotional_document: The promotional_document of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePromotionalDocument
        """

        self._promotional_document = promotional_document

    @property
    def related_document(self):
        """Gets the related_document of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The related_document of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServiceRelatedDocument
        """
        return self._related_document

    @related_document.setter
    def related_document(self, related_document):
        """Sets the related_document of this GuaranteedSimulationServicePackage.


        :param related_document: The related_document of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServiceRelatedDocument
        """

        self._related_document = related_document

    @property
    def ad_requirements(self):
        """Gets the ad_requirements of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The ad_requirements of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: list[GuaranteedSimulationServiceAdRequirement]
        """
        return self._ad_requirements

    @ad_requirements.setter
    def ad_requirements(self, ad_requirements):
        """Sets the ad_requirements of this GuaranteedSimulationServicePackage.


        :param ad_requirements: The ad_requirements of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: list[GuaranteedSimulationServiceAdRequirement]
        """

        self._ad_requirements = ad_requirements

    @property
    def action_after_video_ad_tap(self):
        """Gets the action_after_video_ad_tap of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The action_after_video_ad_tap of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServiceActionAfterVideoAdTap
        """
        return self._action_after_video_ad_tap

    @action_after_video_ad_tap.setter
    def action_after_video_ad_tap(self, action_after_video_ad_tap):
        """Sets the action_after_video_ad_tap of this GuaranteedSimulationServicePackage.


        :param action_after_video_ad_tap: The action_after_video_ad_tap of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServiceActionAfterVideoAdTap
        """

        self._action_after_video_ad_tap = action_after_video_ad_tap

    @property
    def instream_duration_type(self):
        """Gets the instream_duration_type of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The instream_duration_type of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServiceInstreamDurationType
        """
        return self._instream_duration_type

    @instream_duration_type.setter
    def instream_duration_type(self, instream_duration_type):
        """Sets the instream_duration_type of this GuaranteedSimulationServicePackage.


        :param instream_duration_type: The instream_duration_type of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServiceInstreamDurationType
        """

        self._instream_duration_type = instream_duration_type

    @property
    def remarks(self):
        """Gets the remarks of this GuaranteedSimulationServicePackage.  # noqa: E501

        <div lang=\"ja\">備考です。</div> <div lang=\"en\">Remarks.</div>   # noqa: E501

        :return: The remarks of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: str
        """
        return self._remarks

    @remarks.setter
    def remarks(self, remarks):
        """Sets the remarks of this GuaranteedSimulationServicePackage.

        <div lang=\"ja\">備考です。</div> <div lang=\"en\">Remarks.</div>   # noqa: E501

        :param remarks: The remarks of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: str
        """

        self._remarks = remarks

    @property
    def package_permitted_viewable_frequency_cap(self):
        """Gets the package_permitted_viewable_frequency_cap of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The package_permitted_viewable_frequency_cap of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePackagePermittedViewableFrequencyCap
        """
        return self._package_permitted_viewable_frequency_cap

    @package_permitted_viewable_frequency_cap.setter
    def package_permitted_viewable_frequency_cap(self, package_permitted_viewable_frequency_cap):
        """Sets the package_permitted_viewable_frequency_cap of this GuaranteedSimulationServicePackage.


        :param package_permitted_viewable_frequency_cap: The package_permitted_viewable_frequency_cap of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePackagePermittedViewableFrequencyCap
        """

        self._package_permitted_viewable_frequency_cap = package_permitted_viewable_frequency_cap

    @property
    def package_permitted_ad_place_types(self):
        """Gets the package_permitted_ad_place_types of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The package_permitted_ad_place_types of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePackagePermittedAdPlaceTypes
        """
        return self._package_permitted_ad_place_types

    @package_permitted_ad_place_types.setter
    def package_permitted_ad_place_types(self, package_permitted_ad_place_types):
        """Sets the package_permitted_ad_place_types of this GuaranteedSimulationServicePackage.


        :param package_permitted_ad_place_types: The package_permitted_ad_place_types of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePackagePermittedAdPlaceTypes
        """

        self._package_permitted_ad_place_types = package_permitted_ad_place_types

    @property
    def package_permitted_gender_target(self):
        """Gets the package_permitted_gender_target of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The package_permitted_gender_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePackagePermittedGenderTarget
        """
        return self._package_permitted_gender_target

    @package_permitted_gender_target.setter
    def package_permitted_gender_target(self, package_permitted_gender_target):
        """Sets the package_permitted_gender_target of this GuaranteedSimulationServicePackage.


        :param package_permitted_gender_target: The package_permitted_gender_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePackagePermittedGenderTarget
        """

        self._package_permitted_gender_target = package_permitted_gender_target

    @property
    def package_permitted_age_target(self):
        """Gets the package_permitted_age_target of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The package_permitted_age_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePackagePermittedAgeTarget
        """
        return self._package_permitted_age_target

    @package_permitted_age_target.setter
    def package_permitted_age_target(self, package_permitted_age_target):
        """Sets the package_permitted_age_target of this GuaranteedSimulationServicePackage.


        :param package_permitted_age_target: The package_permitted_age_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePackagePermittedAgeTarget
        """

        self._package_permitted_age_target = package_permitted_age_target

    @property
    def package_permitted_audience_category_target(self):
        """Gets the package_permitted_audience_category_target of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The package_permitted_audience_category_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePackagePermittedAudienceCategoryTarget
        """
        return self._package_permitted_audience_category_target

    @package_permitted_audience_category_target.setter
    def package_permitted_audience_category_target(self, package_permitted_audience_category_target):
        """Sets the package_permitted_audience_category_target of this GuaranteedSimulationServicePackage.


        :param package_permitted_audience_category_target: The package_permitted_audience_category_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePackagePermittedAudienceCategoryTarget
        """

        self._package_permitted_audience_category_target = package_permitted_audience_category_target

    @property
    def package_permitted_geo_target(self):
        """Gets the package_permitted_geo_target of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The package_permitted_geo_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePackagePermittedGeoTarget
        """
        return self._package_permitted_geo_target

    @package_permitted_geo_target.setter
    def package_permitted_geo_target(self, package_permitted_geo_target):
        """Sets the package_permitted_geo_target of this GuaranteedSimulationServicePackage.


        :param package_permitted_geo_target: The package_permitted_geo_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePackagePermittedGeoTarget
        """

        self._package_permitted_geo_target = package_permitted_geo_target

    @property
    def package_permitted_ad_schedule_target(self):
        """Gets the package_permitted_ad_schedule_target of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The package_permitted_ad_schedule_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePackagePermittedAdScheduleTarget
        """
        return self._package_permitted_ad_schedule_target

    @package_permitted_ad_schedule_target.setter
    def package_permitted_ad_schedule_target(self, package_permitted_ad_schedule_target):
        """Sets the package_permitted_ad_schedule_target of this GuaranteedSimulationServicePackage.


        :param package_permitted_ad_schedule_target: The package_permitted_ad_schedule_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePackagePermittedAdScheduleTarget
        """

        self._package_permitted_ad_schedule_target = package_permitted_ad_schedule_target

    @property
    def package_permitted_device_target(self):
        """Gets the package_permitted_device_target of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The package_permitted_device_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePackagePermittedDeviceTarget
        """
        return self._package_permitted_device_target

    @package_permitted_device_target.setter
    def package_permitted_device_target(self, package_permitted_device_target):
        """Sets the package_permitted_device_target of this GuaranteedSimulationServicePackage.


        :param package_permitted_device_target: The package_permitted_device_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePackagePermittedDeviceTarget
        """

        self._package_permitted_device_target = package_permitted_device_target

    @property
    def package_permitted_os_target(self):
        """Gets the package_permitted_os_target of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The package_permitted_os_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePackagePermittedOsTarget
        """
        return self._package_permitted_os_target

    @package_permitted_os_target.setter
    def package_permitted_os_target(self, package_permitted_os_target):
        """Sets the package_permitted_os_target of this GuaranteedSimulationServicePackage.


        :param package_permitted_os_target: The package_permitted_os_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePackagePermittedOsTarget
        """

        self._package_permitted_os_target = package_permitted_os_target

    @property
    def package_permitted_app_target(self):
        """Gets the package_permitted_app_target of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The package_permitted_app_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePackagePermittedAppTarget
        """
        return self._package_permitted_app_target

    @package_permitted_app_target.setter
    def package_permitted_app_target(self, package_permitted_app_target):
        """Sets the package_permitted_app_target of this GuaranteedSimulationServicePackage.


        :param package_permitted_app_target: The package_permitted_app_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePackagePermittedAppTarget
        """

        self._package_permitted_app_target = package_permitted_app_target

    @property
    def package_permitted_placement_category_target(self):
        """Gets the package_permitted_placement_category_target of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The package_permitted_placement_category_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePackagePermittedPlacementCategoryTarget
        """
        return self._package_permitted_placement_category_target

    @package_permitted_placement_category_target.setter
    def package_permitted_placement_category_target(self, package_permitted_placement_category_target):
        """Sets the package_permitted_placement_category_target of this GuaranteedSimulationServicePackage.


        :param package_permitted_placement_category_target: The package_permitted_placement_category_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePackagePermittedPlacementCategoryTarget
        """

        self._package_permitted_placement_category_target = package_permitted_placement_category_target

    @property
    def package_permitted_position_target(self):
        """Gets the package_permitted_position_target of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The package_permitted_position_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePackagePermittedPositionTarget
        """
        return self._package_permitted_position_target

    @package_permitted_position_target.setter
    def package_permitted_position_target(self, package_permitted_position_target):
        """Sets the package_permitted_position_target of this GuaranteedSimulationServicePackage.


        :param package_permitted_position_target: The package_permitted_position_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePackagePermittedPositionTarget
        """

        self._package_permitted_position_target = package_permitted_position_target

    @property
    def package_permitted_site_retargeting_target(self):
        """Gets the package_permitted_site_retargeting_target of this GuaranteedSimulationServicePackage.  # noqa: E501


        :return: The package_permitted_site_retargeting_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :rtype: GuaranteedSimulationServicePackagePermittedSiteRetargetingTarget
        """
        return self._package_permitted_site_retargeting_target

    @package_permitted_site_retargeting_target.setter
    def package_permitted_site_retargeting_target(self, package_permitted_site_retargeting_target):
        """Sets the package_permitted_site_retargeting_target of this GuaranteedSimulationServicePackage.


        :param package_permitted_site_retargeting_target: The package_permitted_site_retargeting_target of this GuaranteedSimulationServicePackage.  # noqa: E501
        :type: GuaranteedSimulationServicePackagePermittedSiteRetargetingTarget
        """

        self._package_permitted_site_retargeting_target = package_permitted_site_retargeting_target

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GuaranteedSimulationServicePackage):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GuaranteedSimulationServicePackage):
            return True

        return self.to_dict() != other.to_dict()
