# coding: utf-8

"""
    Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference

    <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v6/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v6
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from yahoo_display_api.configuration import Configuration


class GuaranteedSimulationServiceTarget(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ad_schedule_target': 'GuaranteedSimulationServiceAdScheduleTarget',
        'age_target': 'GuaranteedSimulationServiceAgeTarget',
        'app_target': 'GuaranteedSimulationServiceAppTarget',
        'audience_category_target': 'GuaranteedSimulationServiceAudienceCategoryTarget',
        'device_target': 'GuaranteedSimulationServiceDeviceTarget',
        'gender_target': 'GuaranteedSimulationServiceGenderTarget',
        'geo_target': 'GuaranteedSimulationServiceGeoTarget',
        'os_target': 'GuaranteedSimulationServiceOsTarget',
        'placement_category_target': 'GuaranteedSimulationServicePlacementCategoryTarget',
        'placement_category_detail_target': 'GuaranteedSimulationServicePlacementCategoryDetailTarget',
        'position_target': 'GuaranteedSimulationServicePositionTarget',
        'site_retargeting_target': 'GuaranteedSimulationServiceSiteRetargetingTarget',
        'target_id': 'str',
        'target_type': 'GuaranteedSimulationServiceTargetType'
    }

    attribute_map = {
        'ad_schedule_target': 'adScheduleTarget',
        'age_target': 'ageTarget',
        'app_target': 'appTarget',
        'audience_category_target': 'audienceCategoryTarget',
        'device_target': 'deviceTarget',
        'gender_target': 'genderTarget',
        'geo_target': 'geoTarget',
        'os_target': 'osTarget',
        'placement_category_target': 'placementCategoryTarget',
        'placement_category_detail_target': 'placementCategoryDetailTarget',
        'position_target': 'positionTarget',
        'site_retargeting_target': 'siteRetargetingTarget',
        'target_id': 'targetId',
        'target_type': 'targetType'
    }

    def __init__(self, ad_schedule_target=None, age_target=None, app_target=None, audience_category_target=None, device_target=None, gender_target=None, geo_target=None, os_target=None, placement_category_target=None, placement_category_detail_target=None, position_target=None, site_retargeting_target=None, target_id=None, target_type=None, local_vars_configuration=None):  # noqa: E501
        """GuaranteedSimulationServiceTarget - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._ad_schedule_target = None
        self._age_target = None
        self._app_target = None
        self._audience_category_target = None
        self._device_target = None
        self._gender_target = None
        self._geo_target = None
        self._os_target = None
        self._placement_category_target = None
        self._placement_category_detail_target = None
        self._position_target = None
        self._site_retargeting_target = None
        self._target_id = None
        self._target_type = None
        self.discriminator = None

        self.ad_schedule_target = ad_schedule_target
        self.age_target = age_target
        self.app_target = app_target
        self.audience_category_target = audience_category_target
        self.device_target = device_target
        self.gender_target = gender_target
        self.geo_target = geo_target
        self.os_target = os_target
        self.placement_category_target = placement_category_target
        self.placement_category_detail_target = placement_category_detail_target
        self.position_target = position_target
        self.site_retargeting_target = site_retargeting_target
        self.target_id = target_id
        self.target_type = target_type

    @property
    def ad_schedule_target(self):
        """Gets the ad_schedule_target of this GuaranteedSimulationServiceTarget.  # noqa: E501


        :return: The ad_schedule_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :rtype: GuaranteedSimulationServiceAdScheduleTarget
        """
        return self._ad_schedule_target

    @ad_schedule_target.setter
    def ad_schedule_target(self, ad_schedule_target):
        """Sets the ad_schedule_target of this GuaranteedSimulationServiceTarget.


        :param ad_schedule_target: The ad_schedule_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :type: GuaranteedSimulationServiceAdScheduleTarget
        """

        self._ad_schedule_target = ad_schedule_target

    @property
    def age_target(self):
        """Gets the age_target of this GuaranteedSimulationServiceTarget.  # noqa: E501


        :return: The age_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :rtype: GuaranteedSimulationServiceAgeTarget
        """
        return self._age_target

    @age_target.setter
    def age_target(self, age_target):
        """Sets the age_target of this GuaranteedSimulationServiceTarget.


        :param age_target: The age_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :type: GuaranteedSimulationServiceAgeTarget
        """

        self._age_target = age_target

    @property
    def app_target(self):
        """Gets the app_target of this GuaranteedSimulationServiceTarget.  # noqa: E501


        :return: The app_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :rtype: GuaranteedSimulationServiceAppTarget
        """
        return self._app_target

    @app_target.setter
    def app_target(self, app_target):
        """Sets the app_target of this GuaranteedSimulationServiceTarget.


        :param app_target: The app_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :type: GuaranteedSimulationServiceAppTarget
        """

        self._app_target = app_target

    @property
    def audience_category_target(self):
        """Gets the audience_category_target of this GuaranteedSimulationServiceTarget.  # noqa: E501


        :return: The audience_category_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :rtype: GuaranteedSimulationServiceAudienceCategoryTarget
        """
        return self._audience_category_target

    @audience_category_target.setter
    def audience_category_target(self, audience_category_target):
        """Sets the audience_category_target of this GuaranteedSimulationServiceTarget.


        :param audience_category_target: The audience_category_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :type: GuaranteedSimulationServiceAudienceCategoryTarget
        """

        self._audience_category_target = audience_category_target

    @property
    def device_target(self):
        """Gets the device_target of this GuaranteedSimulationServiceTarget.  # noqa: E501


        :return: The device_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :rtype: GuaranteedSimulationServiceDeviceTarget
        """
        return self._device_target

    @device_target.setter
    def device_target(self, device_target):
        """Sets the device_target of this GuaranteedSimulationServiceTarget.


        :param device_target: The device_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :type: GuaranteedSimulationServiceDeviceTarget
        """

        self._device_target = device_target

    @property
    def gender_target(self):
        """Gets the gender_target of this GuaranteedSimulationServiceTarget.  # noqa: E501


        :return: The gender_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :rtype: GuaranteedSimulationServiceGenderTarget
        """
        return self._gender_target

    @gender_target.setter
    def gender_target(self, gender_target):
        """Sets the gender_target of this GuaranteedSimulationServiceTarget.


        :param gender_target: The gender_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :type: GuaranteedSimulationServiceGenderTarget
        """

        self._gender_target = gender_target

    @property
    def geo_target(self):
        """Gets the geo_target of this GuaranteedSimulationServiceTarget.  # noqa: E501


        :return: The geo_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :rtype: GuaranteedSimulationServiceGeoTarget
        """
        return self._geo_target

    @geo_target.setter
    def geo_target(self, geo_target):
        """Sets the geo_target of this GuaranteedSimulationServiceTarget.


        :param geo_target: The geo_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :type: GuaranteedSimulationServiceGeoTarget
        """

        self._geo_target = geo_target

    @property
    def os_target(self):
        """Gets the os_target of this GuaranteedSimulationServiceTarget.  # noqa: E501


        :return: The os_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :rtype: GuaranteedSimulationServiceOsTarget
        """
        return self._os_target

    @os_target.setter
    def os_target(self, os_target):
        """Sets the os_target of this GuaranteedSimulationServiceTarget.


        :param os_target: The os_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :type: GuaranteedSimulationServiceOsTarget
        """

        self._os_target = os_target

    @property
    def placement_category_target(self):
        """Gets the placement_category_target of this GuaranteedSimulationServiceTarget.  # noqa: E501


        :return: The placement_category_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :rtype: GuaranteedSimulationServicePlacementCategoryTarget
        """
        return self._placement_category_target

    @placement_category_target.setter
    def placement_category_target(self, placement_category_target):
        """Sets the placement_category_target of this GuaranteedSimulationServiceTarget.


        :param placement_category_target: The placement_category_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :type: GuaranteedSimulationServicePlacementCategoryTarget
        """

        self._placement_category_target = placement_category_target

    @property
    def placement_category_detail_target(self):
        """Gets the placement_category_detail_target of this GuaranteedSimulationServiceTarget.  # noqa: E501


        :return: The placement_category_detail_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :rtype: GuaranteedSimulationServicePlacementCategoryDetailTarget
        """
        return self._placement_category_detail_target

    @placement_category_detail_target.setter
    def placement_category_detail_target(self, placement_category_detail_target):
        """Sets the placement_category_detail_target of this GuaranteedSimulationServiceTarget.


        :param placement_category_detail_target: The placement_category_detail_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :type: GuaranteedSimulationServicePlacementCategoryDetailTarget
        """

        self._placement_category_detail_target = placement_category_detail_target

    @property
    def position_target(self):
        """Gets the position_target of this GuaranteedSimulationServiceTarget.  # noqa: E501


        :return: The position_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :rtype: GuaranteedSimulationServicePositionTarget
        """
        return self._position_target

    @position_target.setter
    def position_target(self, position_target):
        """Sets the position_target of this GuaranteedSimulationServiceTarget.


        :param position_target: The position_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :type: GuaranteedSimulationServicePositionTarget
        """

        self._position_target = position_target

    @property
    def site_retargeting_target(self):
        """Gets the site_retargeting_target of this GuaranteedSimulationServiceTarget.  # noqa: E501


        :return: The site_retargeting_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :rtype: GuaranteedSimulationServiceSiteRetargetingTarget
        """
        return self._site_retargeting_target

    @site_retargeting_target.setter
    def site_retargeting_target(self, site_retargeting_target):
        """Sets the site_retargeting_target of this GuaranteedSimulationServiceTarget.


        :param site_retargeting_target: The site_retargeting_target of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :type: GuaranteedSimulationServiceSiteRetargetingTarget
        """

        self._site_retargeting_target = site_retargeting_target

    @property
    def target_id(self):
        """Gets the target_id of this GuaranteedSimulationServiceTarget.  # noqa: E501

        <div lang=\"ja\"> ターゲットIDです。<br> このフィールドは、ADD時は省略可能となります。 </div> <div lang=\"en\"> Target ID.<br> This field is optional in ADD operation. </div>   # noqa: E501

        :return: The target_id of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :rtype: str
        """
        return self._target_id

    @target_id.setter
    def target_id(self, target_id):
        """Sets the target_id of this GuaranteedSimulationServiceTarget.

        <div lang=\"ja\"> ターゲットIDです。<br> このフィールドは、ADD時は省略可能となります。 </div> <div lang=\"en\"> Target ID.<br> This field is optional in ADD operation. </div>   # noqa: E501

        :param target_id: The target_id of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :type: str
        """

        self._target_id = target_id

    @property
    def target_type(self):
        """Gets the target_type of this GuaranteedSimulationServiceTarget.  # noqa: E501


        :return: The target_type of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :rtype: GuaranteedSimulationServiceTargetType
        """
        return self._target_type

    @target_type.setter
    def target_type(self, target_type):
        """Sets the target_type of this GuaranteedSimulationServiceTarget.


        :param target_type: The target_type of this GuaranteedSimulationServiceTarget.  # noqa: E501
        :type: GuaranteedSimulationServiceTargetType
        """

        self._target_type = target_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GuaranteedSimulationServiceTarget):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GuaranteedSimulationServiceTarget):
            return True

        return self.to_dict() != other.to_dict()
