# coding: utf-8

"""
    Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference

    <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v6/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v6
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from yahoo_display_api.configuration import Configuration


class GuaranteedInventoryServiceInventory(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'account_id': 'int',
        'lifetime_budget': 'int',
        'reach': 'int',
        'v_imps': 'int',
        'sov_rate': 'int',
        'slots': 'int',
        'campaign_goal': 'str',
        'start_date': 'str',
        'end_date': 'str',
        'max_sellable_v_imps': 'int',
        'max_sellable_reach': 'int',
        'max_reservable_v_imps': 'int',
        'max_reservable_slots': 'int',
        'lower_budget_limit': 'int',
        'upper_budget_limit': 'int',
        'package_id': 'int',
        'package_name': 'str',
        'package_history_id': 'int',
        'ad_category_ids': 'list[int]',
        'promotion_url': 'str',
        'minimum_purchase_v_imps': 'int',
        'maximum_purchase_v_imps': 'int',
        'inventory_unit': 'GuaranteedInventoryServiceInventoryUnit',
        'campaign_bidding_strategy_type': 'GuaranteedInventoryServiceCampaignBiddingStrategyType',
        'viewable_frequency_cap': 'GuaranteedInventoryServiceViewableFrequencyCap',
        'reservation_status': 'GuaranteedInventoryServiceReservationStatus',
        'unreservable_reason': 'GuaranteedInventoryServiceUnreservableReason',
        'ad_requirements': 'list[GuaranteedInventoryServiceAdRequirement]',
        'inventory_detail_status': 'GuaranteedInventoryServiceInventoryDetailStatus',
        'action_after_video_ad_tap': 'GuaranteedInventoryServiceActionAfterVideoAdTap',
        'price_type': 'GuaranteedInventoryServicePriceType',
        'placement_monopoly_flg': 'GuaranteedInventoryServicePlacementMonopolyFlg',
        'prediction_results': 'list[GuaranteedInventoryServicePredictionResult]',
        'requested_condition_prediction_result': 'GuaranteedInventoryServicePredictionResult',
        'inventory_result': 'list[GuaranteedInventoryServiceInventoryResult]',
        'targets': 'list[GuaranteedInventoryServiceAdGroupTarget]'
    }

    attribute_map = {
        'account_id': 'accountId',
        'lifetime_budget': 'lifetimeBudget',
        'reach': 'reach',
        'v_imps': 'vImps',
        'sov_rate': 'sovRate',
        'slots': 'slots',
        'campaign_goal': 'campaignGoal',
        'start_date': 'startDate',
        'end_date': 'endDate',
        'max_sellable_v_imps': 'maxSellableVImps',
        'max_sellable_reach': 'maxSellableReach',
        'max_reservable_v_imps': 'maxReservableVImps',
        'max_reservable_slots': 'maxReservableSlots',
        'lower_budget_limit': 'lowerBudgetLimit',
        'upper_budget_limit': 'upperBudgetLimit',
        'package_id': 'packageId',
        'package_name': 'packageName',
        'package_history_id': 'packageHistoryId',
        'ad_category_ids': 'adCategoryIds',
        'promotion_url': 'promotionUrl',
        'minimum_purchase_v_imps': 'minimumPurchaseVImps',
        'maximum_purchase_v_imps': 'maximumPurchaseVImps',
        'inventory_unit': 'inventoryUnit',
        'campaign_bidding_strategy_type': 'campaignBiddingStrategyType',
        'viewable_frequency_cap': 'viewableFrequencyCap',
        'reservation_status': 'reservationStatus',
        'unreservable_reason': 'unreservableReason',
        'ad_requirements': 'adRequirements',
        'inventory_detail_status': 'inventoryDetailStatus',
        'action_after_video_ad_tap': 'actionAfterVideoAdTap',
        'price_type': 'priceType',
        'placement_monopoly_flg': 'placementMonopolyFlg',
        'prediction_results': 'predictionResults',
        'requested_condition_prediction_result': 'requestedConditionPredictionResult',
        'inventory_result': 'inventoryResult',
        'targets': 'targets'
    }

    def __init__(self, account_id=None, lifetime_budget=None, reach=None, v_imps=None, sov_rate=None, slots=None, campaign_goal=None, start_date=None, end_date=None, max_sellable_v_imps=None, max_sellable_reach=None, max_reservable_v_imps=None, max_reservable_slots=None, lower_budget_limit=None, upper_budget_limit=None, package_id=None, package_name=None, package_history_id=None, ad_category_ids=None, promotion_url=None, minimum_purchase_v_imps=None, maximum_purchase_v_imps=None, inventory_unit=None, campaign_bidding_strategy_type=None, viewable_frequency_cap=None, reservation_status=None, unreservable_reason=None, ad_requirements=None, inventory_detail_status=None, action_after_video_ad_tap=None, price_type=None, placement_monopoly_flg=None, prediction_results=None, requested_condition_prediction_result=None, inventory_result=None, targets=None, local_vars_configuration=None):  # noqa: E501
        """GuaranteedInventoryServiceInventory - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._account_id = None
        self._lifetime_budget = None
        self._reach = None
        self._v_imps = None
        self._sov_rate = None
        self._slots = None
        self._campaign_goal = None
        self._start_date = None
        self._end_date = None
        self._max_sellable_v_imps = None
        self._max_sellable_reach = None
        self._max_reservable_v_imps = None
        self._max_reservable_slots = None
        self._lower_budget_limit = None
        self._upper_budget_limit = None
        self._package_id = None
        self._package_name = None
        self._package_history_id = None
        self._ad_category_ids = None
        self._promotion_url = None
        self._minimum_purchase_v_imps = None
        self._maximum_purchase_v_imps = None
        self._inventory_unit = None
        self._campaign_bidding_strategy_type = None
        self._viewable_frequency_cap = None
        self._reservation_status = None
        self._unreservable_reason = None
        self._ad_requirements = None
        self._inventory_detail_status = None
        self._action_after_video_ad_tap = None
        self._price_type = None
        self._placement_monopoly_flg = None
        self._prediction_results = None
        self._requested_condition_prediction_result = None
        self._inventory_result = None
        self._targets = None
        self.discriminator = None

        self.account_id = account_id
        self.lifetime_budget = lifetime_budget
        self.reach = reach
        self.v_imps = v_imps
        self.sov_rate = sov_rate
        self.slots = slots
        self.campaign_goal = campaign_goal
        self.start_date = start_date
        self.end_date = end_date
        self.max_sellable_v_imps = max_sellable_v_imps
        self.max_sellable_reach = max_sellable_reach
        self.max_reservable_v_imps = max_reservable_v_imps
        self.max_reservable_slots = max_reservable_slots
        self.lower_budget_limit = lower_budget_limit
        self.upper_budget_limit = upper_budget_limit
        self.package_id = package_id
        self.package_name = package_name
        self.package_history_id = package_history_id
        self.ad_category_ids = ad_category_ids
        self.promotion_url = promotion_url
        self.minimum_purchase_v_imps = minimum_purchase_v_imps
        self.maximum_purchase_v_imps = maximum_purchase_v_imps
        self.inventory_unit = inventory_unit
        self.campaign_bidding_strategy_type = campaign_bidding_strategy_type
        self.viewable_frequency_cap = viewable_frequency_cap
        self.reservation_status = reservation_status
        self.unreservable_reason = unreservable_reason
        self.ad_requirements = ad_requirements
        self.inventory_detail_status = inventory_detail_status
        self.action_after_video_ad_tap = action_after_video_ad_tap
        self.price_type = price_type
        self.placement_monopoly_flg = placement_monopoly_flg
        self.prediction_results = prediction_results
        self.requested_condition_prediction_result = requested_condition_prediction_result
        self.inventory_result = inventory_result
        self.targets = targets

    @property
    def account_id(self):
        """Gets the account_id of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> アカウントIDです。<br> ADD時、このフィールドは省略可能となります。 </div> <div lang=\"en\"> Account ID.<br> This field is optional in ADD operation. </div>   # noqa: E501

        :return: The account_id of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> アカウントIDです。<br> ADD時、このフィールドは省略可能となります。 </div> <div lang=\"en\"> Account ID.<br> This field is optional in ADD operation. </div>   # noqa: E501

        :param account_id: The account_id of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._account_id = account_id

    @property
    def lifetime_budget(self):
        """Gets the lifetime_budget of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> キャンペーンの通期予算額です。<br> ※この「通期予算」は、キャンペーンの全期間を通じて消費される予算を意味します。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> An amount of campaign's lifetime budget.<br> * \"lifetime budget\" means the total budget that is spent throughout the entire duration of the campaign.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The lifetime_budget of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._lifetime_budget

    @lifetime_budget.setter
    def lifetime_budget(self, lifetime_budget):
        """Sets the lifetime_budget of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> キャンペーンの通期予算額です。<br> ※この「通期予算」は、キャンペーンの全期間を通じて消費される予算を意味します。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> An amount of campaign's lifetime budget.<br> * \"lifetime budget\" means the total budget that is spent throughout the entire duration of the campaign.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param lifetime_budget: The lifetime_budget of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._lifetime_budget = lifetime_budget

    @property
    def reach(self):
        """Gets the reach of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> リーチ数です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Number of reaches.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The reach of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._reach

    @reach.setter
    def reach(self, reach):
        """Sets the reach of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> リーチ数です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Number of reaches.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param reach: The reach of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._reach = reach

    @property
    def v_imps(self):
        """Gets the v_imps of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> ビューアブルインプレッションです。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Viewable impressions.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The v_imps of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._v_imps

    @v_imps.setter
    def v_imps(self, v_imps):
        """Sets the v_imps of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> ビューアブルインプレッションです。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Viewable impressions.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param v_imps: The v_imps of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._v_imps = v_imps

    @property
    def sov_rate(self):
        """Gets the sov_rate of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> SOV（1%〜100%）です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> SOV (1% to 100%).<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The sov_rate of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._sov_rate

    @sov_rate.setter
    def sov_rate(self, sov_rate):
        """Sets the sov_rate of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> SOV（1%〜100%）です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> SOV (1% to 100%).<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param sov_rate: The sov_rate of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._sov_rate = sov_rate

    @property
    def slots(self):
        """Gets the slots of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> 購入枠数です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Number of buying slots.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The slots of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._slots

    @slots.setter
    def slots(self, slots):
        """Sets the slots of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> 購入枠数です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Number of buying slots.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param slots: The slots of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._slots = slots

    @property
    def campaign_goal(self):
        """Gets the campaign_goal of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> キャンペーン目的です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Campaign goal.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The campaign_goal of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: str
        """
        return self._campaign_goal

    @campaign_goal.setter
    def campaign_goal(self, campaign_goal):
        """Sets the campaign_goal of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> キャンペーン目的です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Campaign goal.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param campaign_goal: The campaign_goal of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: str
        """

        self._campaign_goal = campaign_goal

    @property
    def start_date(self):
        """Gets the start_date of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> キャンペーンの開始日です。<br> ADD時、このフィールドは必須となります。 </div> <div lang=\"en\"> Start date of campaign. <br> This field is required in ADD operation. </div> Format: yyyyMMdd   # noqa: E501

        :return: The start_date of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> キャンペーンの開始日です。<br> ADD時、このフィールドは必須となります。 </div> <div lang=\"en\"> Start date of campaign. <br> This field is required in ADD operation. </div> Format: yyyyMMdd   # noqa: E501

        :param start_date: The start_date of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: str
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> キャンペーンの終了日です。<br> ADD時、このフィールドは必須となります。<br> </div> <div lang=\"en\"> End date of campaign. <br> This field is required in ADD operation.<br> </div> Format: yyyyMMdd   # noqa: E501

        :return: The end_date of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> キャンペーンの終了日です。<br> ADD時、このフィールドは必須となります。<br> </div> <div lang=\"en\"> End date of campaign. <br> This field is required in ADD operation.<br> </div> Format: yyyyMMdd   # noqa: E501

        :param end_date: The end_date of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: str
        """

        self._end_date = end_date

    @property
    def max_sellable_v_imps(self):
        """Gets the max_sellable_v_imps of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> 販売可能な最大ビューアブルインプレッション数です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Maximum number of viewable impression available for sale. <br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The max_sellable_v_imps of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._max_sellable_v_imps

    @max_sellable_v_imps.setter
    def max_sellable_v_imps(self, max_sellable_v_imps):
        """Sets the max_sellable_v_imps of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> 販売可能な最大ビューアブルインプレッション数です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Maximum number of viewable impression available for sale. <br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param max_sellable_v_imps: The max_sellable_v_imps of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._max_sellable_v_imps = max_sellable_v_imps

    @property
    def max_sellable_reach(self):
        """Gets the max_sellable_reach of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> 販売可能な最大リーチ数です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Maximum number of reach available for sale.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The max_sellable_reach of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._max_sellable_reach

    @max_sellable_reach.setter
    def max_sellable_reach(self, max_sellable_reach):
        """Sets the max_sellable_reach of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> 販売可能な最大リーチ数です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Maximum number of reach available for sale.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param max_sellable_reach: The max_sellable_reach of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._max_sellable_reach = max_sellable_reach

    @property
    def max_reservable_v_imps(self):
        """Gets the max_reservable_v_imps of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> 指定された条件で予約可能な最大配信量です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Maximum ad delivery amount that can be reserved under the specified conditions. <br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The max_reservable_v_imps of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._max_reservable_v_imps

    @max_reservable_v_imps.setter
    def max_reservable_v_imps(self, max_reservable_v_imps):
        """Sets the max_reservable_v_imps of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> 指定された条件で予約可能な最大配信量です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Maximum ad delivery amount that can be reserved under the specified conditions. <br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param max_reservable_v_imps: The max_reservable_v_imps of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._max_reservable_v_imps = max_reservable_v_imps

    @property
    def max_reservable_slots(self):
        """Gets the max_reservable_slots of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> 最大予約可能枠数です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Maximum number of reservable slots. <br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The max_reservable_slots of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._max_reservable_slots

    @max_reservable_slots.setter
    def max_reservable_slots(self, max_reservable_slots):
        """Sets the max_reservable_slots of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> 最大予約可能枠数です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Maximum number of reservable slots. <br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param max_reservable_slots: The max_reservable_slots of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._max_reservable_slots = max_reservable_slots

    @property
    def lower_budget_limit(self):
        """Gets the lower_budget_limit of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> 予約可能な下限通期予算です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Minimum reservable lifetime budget.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The lower_budget_limit of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._lower_budget_limit

    @lower_budget_limit.setter
    def lower_budget_limit(self, lower_budget_limit):
        """Sets the lower_budget_limit of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> 予約可能な下限通期予算です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Minimum reservable lifetime budget.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param lower_budget_limit: The lower_budget_limit of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._lower_budget_limit = lower_budget_limit

    @property
    def upper_budget_limit(self):
        """Gets the upper_budget_limit of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> 予約可能な上限通期予算です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Maximum reservable lifetime budget.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The upper_budget_limit of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._upper_budget_limit

    @upper_budget_limit.setter
    def upper_budget_limit(self, upper_budget_limit):
        """Sets the upper_budget_limit of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> 予約可能な上限通期予算です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Maximum reservable lifetime budget.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param upper_budget_limit: The upper_budget_limit of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._upper_budget_limit = upper_budget_limit

    @property
    def package_id(self):
        """Gets the package_id of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> 商品IDです。<br> ADD時、このフィールドは必須となります。 </div> <div lang=\"en\"> Package ID.<br> In ADD operation, this field will be required. </div>   # noqa: E501

        :return: The package_id of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._package_id

    @package_id.setter
    def package_id(self, package_id):
        """Sets the package_id of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> 商品IDです。<br> ADD時、このフィールドは必須となります。 </div> <div lang=\"en\"> Package ID.<br> In ADD operation, this field will be required. </div>   # noqa: E501

        :param package_id: The package_id of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._package_id = package_id

    @property
    def package_name(self):
        """Gets the package_name of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> 商品名です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Package name.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The package_name of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: str
        """
        return self._package_name

    @package_name.setter
    def package_name(self, package_name):
        """Sets the package_name of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> 商品名です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Package name.<br> Although this field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param package_name: The package_name of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: str
        """

        self._package_name = package_name

    @property
    def package_history_id(self):
        """Gets the package_history_id of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> 商品履歴IDです。<br> ADD時、このフィールドは必須となります。 </div> <div lang=\"en\"> Package history ID.<br> In ADD operation, this field will be required. </div>   # noqa: E501

        :return: The package_history_id of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._package_history_id

    @package_history_id.setter
    def package_history_id(self, package_history_id):
        """Sets the package_history_id of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> 商品履歴IDです。<br> ADD時、このフィールドは必須となります。 </div> <div lang=\"en\"> Package history ID.<br> In ADD operation, this field will be required. </div>   # noqa: E501

        :param package_history_id: The package_history_id of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._package_history_id = package_history_id

    @property
    def ad_category_ids(self):
        """Gets the ad_category_ids of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\"> 広告カテゴリーIDです。<br> 広告カテゴリーは、配信する広告内容に該当するものを正確に指定して下さい。内容に応じて広告掲載量が変わるため、正確なシミュレーション結果の算出に必要です。<br> 詳細は<a href=\"https://ads-help.yahoo.co.jp/yahooads/guideline/articledetail?lan=ja&aid=50308\" target=\"_blank\">ヘルプ</a>を参照してください。<br> なお、ここで指定した広告カテゴリーと異なる広告が入稿された場合は、入稿した広告内容の修正が必要な旨をメールでご連絡します。<br> ADD時、このフィールドは省略可能となります。 </div> <div lang=\"en\"> Ad category ID.<br> To get an accurate simulated result, specify the restricted contents correctly. The ad volume depends on the contents.<br> <a href=\"https://ads-help.yahoo.co.jp/yahooads/guideline/articledetail?lan=en&aid=28259\" target=\"_blank\">Learn more</a><br> If you add ads that have a content different from the one you specified, you will receive an email to fix them.<br> This field is optional in ADD operation. </div>   # noqa: E501

        :return: The ad_category_ids of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: list[int]
        """
        return self._ad_category_ids

    @ad_category_ids.setter
    def ad_category_ids(self, ad_category_ids):
        """Sets the ad_category_ids of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\"> 広告カテゴリーIDです。<br> 広告カテゴリーは、配信する広告内容に該当するものを正確に指定して下さい。内容に応じて広告掲載量が変わるため、正確なシミュレーション結果の算出に必要です。<br> 詳細は<a href=\"https://ads-help.yahoo.co.jp/yahooads/guideline/articledetail?lan=ja&aid=50308\" target=\"_blank\">ヘルプ</a>を参照してください。<br> なお、ここで指定した広告カテゴリーと異なる広告が入稿された場合は、入稿した広告内容の修正が必要な旨をメールでご連絡します。<br> ADD時、このフィールドは省略可能となります。 </div> <div lang=\"en\"> Ad category ID.<br> To get an accurate simulated result, specify the restricted contents correctly. The ad volume depends on the contents.<br> <a href=\"https://ads-help.yahoo.co.jp/yahooads/guideline/articledetail?lan=en&aid=28259\" target=\"_blank\">Learn more</a><br> If you add ads that have a content different from the one you specified, you will receive an email to fix them.<br> This field is optional in ADD operation. </div>   # noqa: E501

        :param ad_category_ids: The ad_category_ids of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: list[int]
        """

        self._ad_category_ids = ad_category_ids

    @property
    def promotion_url(self):
        """Gets the promotion_url of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\">表示URLです。<br> ADD時、このフィールドは省略可能となります。</div> <div lang=\"en\">Promotion url.<br> This field is optional in ADD operation.</div>   # noqa: E501

        :return: The promotion_url of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: str
        """
        return self._promotion_url

    @promotion_url.setter
    def promotion_url(self, promotion_url):
        """Sets the promotion_url of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\">表示URLです。<br> ADD時、このフィールドは省略可能となります。</div> <div lang=\"en\">Promotion url.<br> This field is optional in ADD operation.</div>   # noqa: E501

        :param promotion_url: The promotion_url of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: str
        """

        self._promotion_url = promotion_url

    @property
    def minimum_purchase_v_imps(self):
        """Gets the minimum_purchase_v_imps of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\">最低購入ビューアブルインプレッション数を表します。</div> <div lang=\"en\">Minimum purchase viewable impression.</div>   # noqa: E501

        :return: The minimum_purchase_v_imps of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._minimum_purchase_v_imps

    @minimum_purchase_v_imps.setter
    def minimum_purchase_v_imps(self, minimum_purchase_v_imps):
        """Sets the minimum_purchase_v_imps of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\">最低購入ビューアブルインプレッション数を表します。</div> <div lang=\"en\">Minimum purchase viewable impression.</div>   # noqa: E501

        :param minimum_purchase_v_imps: The minimum_purchase_v_imps of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._minimum_purchase_v_imps = minimum_purchase_v_imps

    @property
    def maximum_purchase_v_imps(self):
        """Gets the maximum_purchase_v_imps of this GuaranteedInventoryServiceInventory.  # noqa: E501

        <div lang=\"ja\">最大購入ビューアブルインプレッション数を表します。</div> <div lang=\"en\">Maximum purchase viewable impression.</div>   # noqa: E501

        :return: The maximum_purchase_v_imps of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: int
        """
        return self._maximum_purchase_v_imps

    @maximum_purchase_v_imps.setter
    def maximum_purchase_v_imps(self, maximum_purchase_v_imps):
        """Sets the maximum_purchase_v_imps of this GuaranteedInventoryServiceInventory.

        <div lang=\"ja\">最大購入ビューアブルインプレッション数を表します。</div> <div lang=\"en\">Maximum purchase viewable impression.</div>   # noqa: E501

        :param maximum_purchase_v_imps: The maximum_purchase_v_imps of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: int
        """

        self._maximum_purchase_v_imps = maximum_purchase_v_imps

    @property
    def inventory_unit(self):
        """Gets the inventory_unit of this GuaranteedInventoryServiceInventory.  # noqa: E501


        :return: The inventory_unit of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: GuaranteedInventoryServiceInventoryUnit
        """
        return self._inventory_unit

    @inventory_unit.setter
    def inventory_unit(self, inventory_unit):
        """Sets the inventory_unit of this GuaranteedInventoryServiceInventory.


        :param inventory_unit: The inventory_unit of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: GuaranteedInventoryServiceInventoryUnit
        """

        self._inventory_unit = inventory_unit

    @property
    def campaign_bidding_strategy_type(self):
        """Gets the campaign_bidding_strategy_type of this GuaranteedInventoryServiceInventory.  # noqa: E501


        :return: The campaign_bidding_strategy_type of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: GuaranteedInventoryServiceCampaignBiddingStrategyType
        """
        return self._campaign_bidding_strategy_type

    @campaign_bidding_strategy_type.setter
    def campaign_bidding_strategy_type(self, campaign_bidding_strategy_type):
        """Sets the campaign_bidding_strategy_type of this GuaranteedInventoryServiceInventory.


        :param campaign_bidding_strategy_type: The campaign_bidding_strategy_type of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: GuaranteedInventoryServiceCampaignBiddingStrategyType
        """

        self._campaign_bidding_strategy_type = campaign_bidding_strategy_type

    @property
    def viewable_frequency_cap(self):
        """Gets the viewable_frequency_cap of this GuaranteedInventoryServiceInventory.  # noqa: E501


        :return: The viewable_frequency_cap of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: GuaranteedInventoryServiceViewableFrequencyCap
        """
        return self._viewable_frequency_cap

    @viewable_frequency_cap.setter
    def viewable_frequency_cap(self, viewable_frequency_cap):
        """Sets the viewable_frequency_cap of this GuaranteedInventoryServiceInventory.


        :param viewable_frequency_cap: The viewable_frequency_cap of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: GuaranteedInventoryServiceViewableFrequencyCap
        """

        self._viewable_frequency_cap = viewable_frequency_cap

    @property
    def reservation_status(self):
        """Gets the reservation_status of this GuaranteedInventoryServiceInventory.  # noqa: E501


        :return: The reservation_status of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: GuaranteedInventoryServiceReservationStatus
        """
        return self._reservation_status

    @reservation_status.setter
    def reservation_status(self, reservation_status):
        """Sets the reservation_status of this GuaranteedInventoryServiceInventory.


        :param reservation_status: The reservation_status of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: GuaranteedInventoryServiceReservationStatus
        """

        self._reservation_status = reservation_status

    @property
    def unreservable_reason(self):
        """Gets the unreservable_reason of this GuaranteedInventoryServiceInventory.  # noqa: E501


        :return: The unreservable_reason of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: GuaranteedInventoryServiceUnreservableReason
        """
        return self._unreservable_reason

    @unreservable_reason.setter
    def unreservable_reason(self, unreservable_reason):
        """Sets the unreservable_reason of this GuaranteedInventoryServiceInventory.


        :param unreservable_reason: The unreservable_reason of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: GuaranteedInventoryServiceUnreservableReason
        """

        self._unreservable_reason = unreservable_reason

    @property
    def ad_requirements(self):
        """Gets the ad_requirements of this GuaranteedInventoryServiceInventory.  # noqa: E501


        :return: The ad_requirements of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: list[GuaranteedInventoryServiceAdRequirement]
        """
        return self._ad_requirements

    @ad_requirements.setter
    def ad_requirements(self, ad_requirements):
        """Sets the ad_requirements of this GuaranteedInventoryServiceInventory.


        :param ad_requirements: The ad_requirements of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: list[GuaranteedInventoryServiceAdRequirement]
        """

        self._ad_requirements = ad_requirements

    @property
    def inventory_detail_status(self):
        """Gets the inventory_detail_status of this GuaranteedInventoryServiceInventory.  # noqa: E501


        :return: The inventory_detail_status of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: GuaranteedInventoryServiceInventoryDetailStatus
        """
        return self._inventory_detail_status

    @inventory_detail_status.setter
    def inventory_detail_status(self, inventory_detail_status):
        """Sets the inventory_detail_status of this GuaranteedInventoryServiceInventory.


        :param inventory_detail_status: The inventory_detail_status of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: GuaranteedInventoryServiceInventoryDetailStatus
        """

        self._inventory_detail_status = inventory_detail_status

    @property
    def action_after_video_ad_tap(self):
        """Gets the action_after_video_ad_tap of this GuaranteedInventoryServiceInventory.  # noqa: E501


        :return: The action_after_video_ad_tap of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: GuaranteedInventoryServiceActionAfterVideoAdTap
        """
        return self._action_after_video_ad_tap

    @action_after_video_ad_tap.setter
    def action_after_video_ad_tap(self, action_after_video_ad_tap):
        """Sets the action_after_video_ad_tap of this GuaranteedInventoryServiceInventory.


        :param action_after_video_ad_tap: The action_after_video_ad_tap of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: GuaranteedInventoryServiceActionAfterVideoAdTap
        """

        self._action_after_video_ad_tap = action_after_video_ad_tap

    @property
    def price_type(self):
        """Gets the price_type of this GuaranteedInventoryServiceInventory.  # noqa: E501


        :return: The price_type of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: GuaranteedInventoryServicePriceType
        """
        return self._price_type

    @price_type.setter
    def price_type(self, price_type):
        """Sets the price_type of this GuaranteedInventoryServiceInventory.


        :param price_type: The price_type of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: GuaranteedInventoryServicePriceType
        """

        self._price_type = price_type

    @property
    def placement_monopoly_flg(self):
        """Gets the placement_monopoly_flg of this GuaranteedInventoryServiceInventory.  # noqa: E501


        :return: The placement_monopoly_flg of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: GuaranteedInventoryServicePlacementMonopolyFlg
        """
        return self._placement_monopoly_flg

    @placement_monopoly_flg.setter
    def placement_monopoly_flg(self, placement_monopoly_flg):
        """Sets the placement_monopoly_flg of this GuaranteedInventoryServiceInventory.


        :param placement_monopoly_flg: The placement_monopoly_flg of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: GuaranteedInventoryServicePlacementMonopolyFlg
        """

        self._placement_monopoly_flg = placement_monopoly_flg

    @property
    def prediction_results(self):
        """Gets the prediction_results of this GuaranteedInventoryServiceInventory.  # noqa: E501


        :return: The prediction_results of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: list[GuaranteedInventoryServicePredictionResult]
        """
        return self._prediction_results

    @prediction_results.setter
    def prediction_results(self, prediction_results):
        """Sets the prediction_results of this GuaranteedInventoryServiceInventory.


        :param prediction_results: The prediction_results of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: list[GuaranteedInventoryServicePredictionResult]
        """

        self._prediction_results = prediction_results

    @property
    def requested_condition_prediction_result(self):
        """Gets the requested_condition_prediction_result of this GuaranteedInventoryServiceInventory.  # noqa: E501


        :return: The requested_condition_prediction_result of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: GuaranteedInventoryServicePredictionResult
        """
        return self._requested_condition_prediction_result

    @requested_condition_prediction_result.setter
    def requested_condition_prediction_result(self, requested_condition_prediction_result):
        """Sets the requested_condition_prediction_result of this GuaranteedInventoryServiceInventory.


        :param requested_condition_prediction_result: The requested_condition_prediction_result of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: GuaranteedInventoryServicePredictionResult
        """

        self._requested_condition_prediction_result = requested_condition_prediction_result

    @property
    def inventory_result(self):
        """Gets the inventory_result of this GuaranteedInventoryServiceInventory.  # noqa: E501


        :return: The inventory_result of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: list[GuaranteedInventoryServiceInventoryResult]
        """
        return self._inventory_result

    @inventory_result.setter
    def inventory_result(self, inventory_result):
        """Sets the inventory_result of this GuaranteedInventoryServiceInventory.


        :param inventory_result: The inventory_result of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: list[GuaranteedInventoryServiceInventoryResult]
        """

        self._inventory_result = inventory_result

    @property
    def targets(self):
        """Gets the targets of this GuaranteedInventoryServiceInventory.  # noqa: E501


        :return: The targets of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :rtype: list[GuaranteedInventoryServiceAdGroupTarget]
        """
        return self._targets

    @targets.setter
    def targets(self, targets):
        """Sets the targets of this GuaranteedInventoryServiceInventory.


        :param targets: The targets of this GuaranteedInventoryServiceInventory.  # noqa: E501
        :type: list[GuaranteedInventoryServiceAdGroupTarget]
        """

        self._targets = targets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GuaranteedInventoryServiceInventory):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GuaranteedInventoryServiceInventory):
            return True

        return self.to_dict() != other.to_dict()
