[project]
name = "orjson-pydantic"
repository = "https://github.com/aviramha/orjson-pydantic"

[build-system]
build-backend = "maturin"
requires = ["maturin>=0.11.4,<0.12"]

[tool.maturin]
sdist-include = ["Cargo.lock"]
strip = true

[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39']
include = '\.pyi?$'
