
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-24T15:32:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1cc8b3dad834583908396d220a99f0e72255fea",
 "version": "2021.10.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
