input: ["img"]
output: ["bboxes", "bbox_labels", "bbox_scores"]

model_type: v4 # v4 or v4tiny
classes: ../peekingduck_weights/yolo_license_plate/classes.names
weights_dir: ["../peekingduck_weights/yolo_license_plate"]
model_weights_dir: {
    v4: ../peekingduck_weights/yolo_license_plate/LPyolov4,
    v4tiny: ../peekingduck_weights/yolo_license_plate/LPyolov4tiny,
}
blob_file: "yolo_license_plate.zip"

size: 416
max_output_size_per_class: 50
max_total_size: 50
yolo_score_threshold: 0.1
yolo_iou_threshold: 0.3
