[tool.poetry]
name = "datahints"
version = "0.1.1"
description = "Type hinting for pandas DataFrame"
authors = ["Ketil Albertsen"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/litek/datahints"
repository = "https://github.com/litek/datahints"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pandas = "^1.3.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
