from .cosleep import CoSleep
from .cpc import CPC
from .dpc import DPC
from .dpcm import DPCMemory
from .moco import Moco
from .rp import RelativePosition
from .simclr import SimCLR
from .tcl import TimeContrastiveLearning
from .tloss import TripletLoss
from .tnc import TNC
from .ts import TemporalShuffling
from .tstcc import TSTCC
