[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "gptsum"
version = "0.1.0"
description = "A tool to make disk images using GPT partitions self-verifiable"
authors = [
    "Nicolas Trangez <ikke@nicolast.be>",
]
license = "Apache-2.0"
readme = "README.rst"
homepage = "https://github.com/NicolasT/gptsum"
repository = "https://github.com/NicolasT/gptsum.git"
keywords = ["gpt", "diskimage", "checksum"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: System",
    "Topic :: System :: Software Distribution",
    "Typing :: Typed",
]

include = [
    { path = "tests/", format = "sdist" },
    { path = "docs/", format = "sdist" },
    { path = "poetry.lock", format = "sdist" },
]

[tool.poetry.urls]
Homepage = "https://github.com/NicolasT/gptsum"
Documentation = "https://nicolast.github.io/gptsum/"
Changelog = "https://github.com/NicolasT/gptsum/releases"
Issues = "https://github.com/NicolasT/gptsum/issues"
"Pull Requests" = "https://github.com/NicolasT/gptsum/pulls"

[tool.poetry.scripts]
gptsum = "gptsum.cli:main"

[tool.poetry.dependencies]
python = "^3.6.1"
importlib-metadata = {version = ">=3.7.3,<5.0.0", python = "< 3.8"}
dataclasses = {version = ">=0.6,<0.9", python = "< 3.7"}

[tool.poetry.dev-dependencies]
mypy = "^0.910"
flake8 = "^3.9.2"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^21.9.2"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.3"
pep8-naming = "^0.12.1"
darglint = "^1.8.0"
black = "^20.8b1"
flake8-black = "^0.2.3"
safety = "^1.10.3"
Sphinx = "^4.2.0"
furo = "^2021.10.9"
sphinx-argparse = "^0.3.1"
coverage = {version = "^6.0", extras = ["toml"]}
pygments = "^2.10.0"
pytest = "^6.2.5"
typeguard = "^2.13.0"
xdoctest = {version = "^0.15.10", extras = ["colors"]}
flake8-pytest-style = "^1.5.0"
flake8-pytest = "^1.3"
flake8-builtins = "^1.5.3"
flake8-isort = "^4.0.0"
flake8-return = "^1.1.3"
flake8-expression-complexity = "^0.0.9"
pytest-mock = "^3.6.1"
pytest-benchmark = "^3.4.1"
types-dataclasses = {version = "^0.6.0", python = "< 3.7"}

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["gptsum", "tests"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[tool.mypy]
strict = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
