input: ["none"]
output: ["img", "pipeline_end", "filename", "saved_video_fps"]

fps_saved_output_video: 10   #may need to change depending on user machine performance
filename: webcamfeed.mp4
resize: {
            do_resizing: False,
            width: 1280,
            height: 720
        }
input_source: 0    # 0 for webcam, rtsp URL for CCTV
mirror_image: False
frames_log_freq: 100    # Logs frequency of frames passed in cli
threading: False    # Enable to speed up FPS. Currently unsupported for Linux.
