[tool.poetry]
name = "antiword"
version = "0.1.0"
description = "Spew anything out as text to stdout"
authors = ["John Maximilian <2e0byo@gmail.com>"]
license = "MIT"
repository = "https://github.com/2e0byo/antiword"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
antiword = "antiword:main"
