# pyproject.toml

[build-system]
requires = ["setuptools>=44", "wheel", "setuptools_scm>=5.0.2"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
skip-string-normalization = true

[tool.isort]
profile = "black"

[tool.setuptools_scm]
