# Generated by Django 3.1.6 on 2021-03-02 13:21

import django.utils.timezone
from django.db import migrations, models

import isc_common.fields.code_field
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20210301_1433'),
        ('decor', '0010_auto_20210302_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus_links',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('code', isc_common.fields.code_field.CodeStrictField()),
                ('link', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='common.links')),
                ('menu', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='decor.menus')),
            ],
            options={
                'verbose_name': 'Кросс таблица',
                'unique_together': {('link', 'menu')},
            },
        ),
    ]
