# Generated by Django 3.2.7 on 2021-09-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0035_auto_20210922_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottom_menu',
            fields=[
                ('menus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='decor.menus')),
            ],
            options={
                'verbose_name': 'Нижнее меню Меню',
            },
            bases=('decor.menus',),
        ),
    ]
