# Generated by Django 3.2.7 on 2021-09-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0047_news_attache_dir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='parent',
            new_name='en',
        ),
    ]
