# Generated by Django 3.2.7 on 2021-09-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0049_news_icon_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='icon',
        ),
    ]
