# Generated by Django 3.2.7 on 2021-09-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0056_news_actions_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_favorites',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
