# https://python-poetry.org/docs/pyproject/
# https://www.python.org/dev/peps/pep-0621/
[tool.poetry]
name = "aucampia.rdflib-xtl"
version = "0.6.0"
description = "Extra tools for rdflib"
authors = ["Iwan Aucamp <aucampia@gmail.com>"]
license = "CC0-1.0"
readme = "README.md"
homepage = "https://gitlab.com/aucampia/project/rdflib-xtl"
packages = [
    { include = "aucampia", from = "src" }
]

[tool.poetry.scripts]
"rdflib-xtl" = "aucampia.rdflib_xtl.cli:main"

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.1"
rdflib = "^5.0.0"
owlrl = "^5.2.1"
rdflib-jsonld = "^0.6.0"
pyyaml = "^5.3.1"
requests = "^2.26.0"
click-option-group = "^0.5.3"
typer = "^0.4.0"
PyYAML = "^5.4.1"
pyparsing = "^2.0.0"

[tool.poetry.dev-dependencies]
black = "^21.8b0"
codespell = "^2.1.0"
flake8 = "^3.9.2"
flake8-black = "^0.2.3"
flake8-bugbear = "^21.4.3"
flake8-isort = "^4.0.0"
flake8-requirements = "^1.5.1"
isort = "^5.9.3"
mypy = "^0.910"
pylint = "^2.10.2"
pytest = "^6.2.5"
pytest-cov = "^2.12.1"
pytest-subtests = "^0.5.0"
safety = "^1.10.3"
types-PyYAML = "^5.4.10"
typing-extensions = "^3.10.0"
[tool.coverage.report]
# https://coverage.readthedocs.io/en/coverage-5.0/config.html
show_missing = true

[tool.isort]
# https://pycqa.github.io/isort/docs/configuration/config_files.html
profile = "black"

[tool.pytest.ini_options]
# https://docs.pytest.org/en/stable/customize.html
# https://docs.pytest.org/en/stable/reference.html#configuration-options
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s %(process)d %(thread)d %(levelno)03d:%(levelname)-8s %(name)-12s %(module)s:%(lineno)s:%(funcName)s %(message)s"
log_cli_date_format = "%Y-%m-%dT%H:%M:%S"

[tool.poetry-dynamic-versioning]
enable = false
vcs = "git"
style = "pep440"

[tool.poetry-dynamic-versioning.substitution]
files=["src/**/_version.py"]

[build-system]
requires = ["setuptools","poetry-core>=1.0.0","poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"
