# Generated by Django 3.2.6 on 2021-09-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0373_alter_clubs_props'),
        ('inventory', '0024_auto_20210831_2237'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clothes_clubs',
            unique_together={('club', 'cloth')},
        ),
        migrations.RemoveField(
            model_name='clothes_clubs',
            name='code',
        ),
    ]
