# Generated by Django 3.1.6 on 2021-02-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0005_region_text_informations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regions',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='middle_text',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='text',
        ),
    ]
