# Generated by Django 3.1.6 on 2021-03-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20210301_1433'),
        ('region', '0033_auto_20210302_0631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='region_images',
            unique_together={('main_model', 'image')},
        ),
        migrations.AlterUniqueTogether(
            name='region_zone_images',
            unique_together={('main_model', 'image')},
        ),
    ]
