# Generated by Django 3.1.6 on 2021-03-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0037_auto_20210302_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='region',
        ),
    ]
