# Generated by Django 3.1.7 on 2021-03-15 11:00

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('isc_common', '0083_remove_users_images_club'),
        ('region', '0040_auto_20210309_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='color',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='isc_common.standard_colors'),
        ),
    ]
