# Generated by Django 3.2.6 on 2021-08-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0107_alter_users_images_unique_together'),
        ('region', '0055_auto_20210823_0736'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='city_images',
        #     unique_together={('main_model', 'image', 'type', 'lastmodified')},
        # ),
    ]
