# Generated by Django 3.2.6 on 2021-08-23 12:53

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0114_auto_20210823_1253'),
        ('decor', '0028_alter_news_images_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_images',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.image_types'),
            preserve_default=False,
        ),
    ]
