# Generated by Django 3.1.6 on 2021-02-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes_type',
            old_name='clubs',
            new_name='club',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='league',
        ),
    ]
