# Generated by Django 3.1.6 on 2021-03-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210302_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='parent',
        ),
    ]
