from typing import TypeVar

from .EventContainer import EventContainer
from .BaseEvent import BaseEvent
from .Draw3D_Box import Draw3D_Box
from .History import History
from .OptionsField import OptionsField
from .RenderCommon_Rect import RenderCommon_Rect
from .LongField import LongField
from .IRecipeBookResults import IRecipeBookResults
from .Button import Button
from .IDraw2D import IDraw2D
from .DefaultCodeCompiler import DefaultCodeCompiler
from .TextInput import TextInput
from .Prism_typescript import Prism_typescript
from .DoubleField import DoubleField
from .HTTPRequest import HTTPRequest
from .ClientConfigV2 import ClientConfigV2
from .ISignEditScreen import ISignEditScreen
from .FileField import FileField
from .ColorMapSetting import ColorMapSetting
from .RenderCommon import RenderCommon
from .ColorMapSetting_ColorEntry import ColorMapSetting_ColorEntry
from .PlayerInput import PlayerInput
from .IFontManager import IFontManager
from .IBeaconScreen import IBeaconScreen
from .IRecipeBookWidget import IRecipeBookWidget
from .LibraryRegistry import LibraryRegistry
from .ILoomScreen import ILoomScreen
from .IHorseScreen import IHorseScreen
from .TickBasedEvents import TickBasedEvents
from .FWrapper_WrappedThread import FWrapper_WrappedThread
from .SettingsOverlay import SettingsOverlay
from .RenderCommon_Item import RenderCommon_Item
from .BaseWrappedException_SourceLocation import BaseWrappedException_SourceLocation
from .HTTPRequest_Response import HTTPRequest_Response
from .Prism_python import Prism_python
from .ChatHistoryManager import ChatHistoryManager
from .Inventory import Inventory
from .MacroScreen import MacroScreen
from .Sorting_SortByTriggerName import Sorting_SortByTriggerName
from .BaseWrappedException_HostLocation import BaseWrappedException_HostLocation
from .JavascriptLanguageDefinition import JavascriptLanguageDefinition
from .IntField import IntField
from .IBossBarHud import IBossBarHud
from .History_TabLines import History_TabLines
from .BaseListener import BaseListener
from .Mappings_MethodData import Mappings_MethodData
from .Profile import Profile
from .AbstractSettingContainer import AbstractSettingContainer
from .BaseEventRegistry import BaseEventRegistry
from .MacroListTopbar import MacroListTopbar
from .RenderCommon_Image import RenderCommon_Image
from .BooleanField import BooleanField
from .SelectorDropdownOverlay import SelectorDropdownOverlay
from .FileChooser_fileObj import FileChooser_fileObj
from .EnchantInventory import EnchantInventory
from .IMerchantScreen import IMerchantScreen
from .KeyMacrosScreen import KeyMacrosScreen
from .Prism_regex import Prism_regex
from .IPlayerListHud import IPlayerListHud
from .History_HistoryStep import History_HistoryStep
from .AbstractMapSettingContainer_MapSettingEntry import AbstractMapSettingContainer_MapSettingEntry
from .EventListener import EventListener
from .Prism_lua import Prism_lua
from .BaseProfile import BaseProfile
from .FileChooser_sortFile import FileChooser_sortFile
from .History_Add import History_Add
from .Scrollbar import Scrollbar
from .TPSData import TPSData
from .EventRegistry import EventRegistry
from .ScriptTrigger import ScriptTrigger
from .Websocket import Websocket
from .SynchronizedWeakHashSet import SynchronizedWeakHashSet
from .ConfirmOverlay import ConfirmOverlay
from .Draw3D_Line import Draw3D_Line
from .ConfigManager import ConfigManager
from .StringHashTrie import StringHashTrie
from .EventLockWatchdog import EventLockWatchdog
from .OverlayContainer import OverlayContainer
from .AbstractMapSettingContainer import AbstractMapSettingContainer
from .Mappings_ClassData import Mappings_ClassData
from .BaseLanguage import BaseLanguage
from .Event import Event
from .KeyListener import KeyListener
from .CategoryTreeContainer import CategoryTreeContainer
from .BeaconInventory import BeaconInventory
from .MultiElementContainer import MultiElementContainer
from .AutoCompleteSuggestion import AutoCompleteSuggestion
from .VillagerInventory import VillagerInventory
from .AnnotatedCheckBox import AnnotatedCheckBox
from .MacroContainer import MacroContainer
from .PositionCommon_Vec2D import PositionCommon_Vec2D
from .BaseWrappedException import BaseWrappedException
from .PerExecLanguageLibrary import PerExecLanguageLibrary
from .ProxyBuilder_ProxyReference import ProxyBuilder_ProxyReference
from .IChatHud import IChatHud
from .History_Replace import History_Replace
from .SettingsOverlay_SettingField import SettingsOverlay_SettingField
from .ScriptTrigger_TriggerType import ScriptTrigger_TriggerType
from .CustomClickEvent import CustomClickEvent
from .TextBuilder import TextBuilder
from .RenderCommon_RenderElement import RenderCommon_RenderElement
from .PositionCommon_Pos2D import PositionCommon_Pos2D
from .EditorScreen import EditorScreen
from .StringMapSetting_StringEntry import StringMapSetting_StringEntry
from .IContainerParent import IContainerParent
from .Sorting_SortByFileName import Sorting_SortByFileName
from .BaseWrappedException_GuestLocation import BaseWrappedException_GuestLocation
from .FileChooser import FileChooser
from .Sorting_SortByEnabled import Sorting_SortByEnabled
from .BaseScreen import BaseScreen
from .Prism_ruby import Prism_ruby
from .JsMacros import JsMacros
from .EventMacrosScreen import EventMacrosScreen
from .CoreConfigV2 import CoreConfigV2
from .Core import Core
from .SelectCursor import SelectCursor
from .History_Remove import History_Remove
from .PositionCommon_Vec3D import PositionCommon_Vec3D
from .Websocket_Disconnected import Websocket_Disconnected
from .PrimitiveSettingGroup import PrimitiveSettingGroup
from .Draw3D import Draw3D
from .Prism_javascript import Prism_javascript
from .AbstractSettingField import AbstractSettingField
from .FReflection_CombinedVariableClassLoader import FReflection_CombinedVariableClassLoader
from .PositionCommon_Pos3D import PositionCommon_Pos3D
from .TickSync import TickSync
from .EventChooser_EventObj import EventChooser_EventObj
from .StringField import StringField
from .AutoCompleteSuggestor import AutoCompleteSuggestor
from .Option import Option
from .MovementDummy import MovementDummy
from .MethodWrapper import MethodWrapper
from .Library import Library
from .Prism import Prism
from .ProfileSetting import ProfileSetting
from .FileMapSetting import FileMapSetting
from .IOverlayParent import IOverlayParent
from .FileMapSetting_FileEntry import FileMapSetting_FileEntry
from .Mappings_MappedClass import Mappings_MappedClass
from .RenderCommon_Text import RenderCommon_Text
from .FJsMacros_ScriptEventListener import FJsMacros_ScriptEventListener
from .LoomInventory import LoomInventory
from .ScriptScreen import ScriptScreen
from .IMinecraftClient import IMinecraftClient
from .Draw2D import Draw2D
from .CancelScreen import CancelScreen
from .FloatField import FloatField
from .PerExecLibrary import PerExecLibrary
from .AbstractRenderCodeCompiler import AbstractRenderCodeCompiler
from .PositionCommon import PositionCommon
from .StringMapSetting import StringMapSetting
from .FJsMacros_EventAndContext import FJsMacros_EventAndContext
from .Sorting_MacroSortMethod import Sorting_MacroSortMethod
from .CancelScreen_RTCSort import CancelScreen_RTCSort
from .ModMenuEntry import ModMenuEntry
from .AboutOverlay import AboutOverlay
from .CheckBoxContainer import CheckBoxContainer
from .DocletReplaceParams import DocletReplaceParams
from .PerLanguageLibrary import PerLanguageLibrary
from .ListContainer import ListContainer
from .MovementQueue import MovementQueue
from .BaseScriptContext import BaseScriptContext
from .EventChooser import EventChooser
from .OptionType import OptionType
from .IFWrapper import IFWrapper
from .ProxyBuilder import ProxyBuilder
from .Pair import Pair
from .IInventory import IInventory
from .IScreen import IScreen
from .EventContainer import EventContainer
from .TextPrompt import TextPrompt
from .Prism_json import Prism_json
from .BaseEvent import BaseEvent
from .TextStyleCompiler import TextStyleCompiler
from .Sorting import Sorting
from .FileHandler import FileHandler
from .ProfileSetting_ProfileEntry import ProfileSetting_ProfileEntry
from .IEventListener import IEventListener
from .Prism_clike import Prism_clike
from .Mappings import Mappings
from .BaseLibrary import BaseLibrary
from .History_ShiftLine import History_ShiftLine
from .ICategoryTreeParent import ICategoryTreeParent
from .BossBarConsumer import BossBarConsumer
from .JSScriptContext import JSScriptContext
from .ModMenuEntry_JsMacroScreen import ModMenuEntry_JsMacroScreen
from .ScriptCodeCompiler import ScriptCodeCompiler
from .CommandBuilder import CommandBuilder
from .RunningContextContainer import RunningContextContainer

File = TypeVar["java.io.File"]

