
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-21T12:03:51-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3e59abd1c642ae8c699987a82d39d3f589618b9",
 "version": "2.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
