[tool.poetry]
name = "tfa_car"
version = "0.1.0"
description = "A python implementation of tfa_car.m from the matlab package found at car-net.org."
authors = ["Ken Liao <cloudrainstar@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
numpy = "^1.21.3"
scipy = "^1.7.1"
matplotlib = "^3.4.3"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
mypy = "^0.910"
pytest = "^6.2.5"
pandas = "^1.3.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
