# Generated by Django 3.2.6 on 2021-08-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0107_alter_users_images_unique_together'),
        ('constructions', '0023_auto_20210823_0721'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fields_images',
            unique_together={('main_model', 'image', 'type', 'deleted_at')},
        ),
    ]
