# Generated by Django 3.2.7 on 2021-09-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0033_alter_stadium_zones_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stadium_zones',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='stadium_zones',
            constraint=models.UniqueConstraint(condition=models.Q(('old_league_id', None), ('old_stadium_id', None)), fields=('league', 'stadium'), name='Stadium_zones_unique_constraint_0'),
        ),
        migrations.AddConstraint(
            model_name='stadium_zones',
            constraint=models.UniqueConstraint(condition=models.Q(('old_league_id', None)), fields=('league', 'old_stadium_id', 'stadium'), name='Stadium_zones_unique_constraint_1'),
        ),
        migrations.AddConstraint(
            model_name='stadium_zones',
            constraint=models.UniqueConstraint(condition=models.Q(('old_stadium_id', None)), fields=('league', 'old_league_id', 'stadium'), name='Stadium_zones_unique_constraint_2'),
        ),
        migrations.AddConstraint(
            model_name='stadium_zones',
            constraint=models.UniqueConstraint(fields=('league', 'old_league_id', 'old_stadium_id', 'stadium'), name='Stadium_zones_unique_constraint_3'),
        ),
    ]
