# Generated by Django 3.2.8 on 2021-10-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('local', models.BooleanField()),
                ('host', models.CharField(max_length=50)),
                ('remote_url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('description_html', models.CharField(max_length=400)),
                ('description_text', models.CharField(max_length=200)),
            ],
        ),
    ]
