# coding: utf-8

"""
    Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference

    <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v6/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import yahoo_display_api
from yahoo_display_api.models.search_keyword_list_service_page import SearchKeywordListServicePage  # noqa: E501
from yahoo_display_api.rest import ApiException

class TestSearchKeywordListServicePage(unittest.TestCase):
    """SearchKeywordListServicePage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SearchKeywordListServicePage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = yahoo_display_api.models.search_keyword_list_service_page.SearchKeywordListServicePage()  # noqa: E501
        if include_optional :
            return SearchKeywordListServicePage(
                total_num_entries = 56, 
                values = [
                    yahoo_display_api.models.search_keyword_list_service_value.SearchKeywordListServiceValue(
                        errors = [
                            yahoo_display_api.models.error.Error(
                                code = '0', 
                                message = '0', 
                                details = [
                                    yahoo_display_api.models.error_detail.ErrorDetail(
                                        request_key = '0', 
                                        request_value = '0', )
                                    ], )
                            ], 
                        operation_succeeded = True, 
                        search_keyword_list = yahoo_display_api.models.search_keyword_list.SearchKeywordList(
                            account_id = 56, 
                            delivery_status = 'PAUSED', 
                            keyword_frequency = 'ONCE_OR_MORE', 
                            keyword_recency = 'WITHIN_1DAY', 
                            search_keyword = [
                                yahoo_display_api.models.search_keyword_list_service_search_keyword.SearchKeywordListServiceSearchKeyword(
                                    search_keyword_id = 56, )
                                ], 
                            search_keyword_list_description = '0', 
                            is_remove_search_keyword_list_description = 'TRUE', 
                            search_keyword_list_id = 56, 
                            search_keyword_list_name = '0', ), )
                    ]
            )
        else :
            return SearchKeywordListServicePage(
        )

    def testSearchKeywordListServicePage(self):
        """Test SearchKeywordListServicePage"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
