# coding: utf-8

"""
    Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference

    <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v6/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import yahoo_display_api
from yahoo_display_api.models.retargeting_list_service_get_upload_user_list_response import RetargetingListServiceGetUploadUserListResponse  # noqa: E501
from yahoo_display_api.rest import ApiException

class TestRetargetingListServiceGetUploadUserListResponse(unittest.TestCase):
    """RetargetingListServiceGetUploadUserListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RetargetingListServiceGetUploadUserListResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = yahoo_display_api.models.retargeting_list_service_get_upload_user_list_response.RetargetingListServiceGetUploadUserListResponse()  # noqa: E501
        if include_optional :
            return RetargetingListServiceGetUploadUserListResponse(
                errors = [
                    yahoo_display_api.models.error.Error(
                        code = '0', 
                        message = '0', 
                        details = [
                            yahoo_display_api.models.error_detail.ErrorDetail(
                                request_key = '0', 
                                request_value = '0', )
                            ], )
                    ], 
                rid = '0', 
                rval = yahoo_display_api.models.retargeting_list_service_upload_user_list_page.RetargetingListServiceUploadUserListPage(
                    total_num_entries = 56, 
                    values = [
                        yahoo_display_api.models.retargeting_list_service_upload_user_list_value.RetargetingListServiceUploadUserListValue(
                            errors = [
                                yahoo_display_api.models.error.Error(
                                    code = '0', 
                                    message = '0', 
                                    details = [
                                        yahoo_display_api.models.error_detail.ErrorDetail(
                                            request_key = '0', 
                                            request_value = '0', )
                                        ], )
                                ], 
                            operation_succeeded = True, 
                            upload_job = yahoo_display_api.models.retargeting_list_service_upload_user_list_job.RetargetingListServiceUploadUserListJob(
                                upload_job_id = '0', 
                                retargeting_tag_id = '0', 
                                target_list_id = 56, 
                                upload_type = 'IDFA', 
                                upload_submit_date = '0', 
                                received_date = '0', 
                                job_status = 'RECEIVING', ), )
                        ], )
            )
        else :
            return RetargetingListServiceGetUploadUserListResponse(
        )

    def testRetargetingListServiceGetUploadUserListResponse(self):
        """Test RetargetingListServiceGetUploadUserListResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
