# coding: utf-8

"""
    Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference

    <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v6/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import yahoo_display_api
from yahoo_display_api.models.ad_group_ad_service_text_ad import AdGroupAdServiceTextAd  # noqa: E501
from yahoo_display_api.rest import ApiException

class TestAdGroupAdServiceTextAd(unittest.TestCase):
    """AdGroupAdServiceTextAd unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AdGroupAdServiceTextAd
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = yahoo_display_api.models.ad_group_ad_service_text_ad.AdGroupAdServiceTextAd()  # noqa: E501
        if include_optional :
            return AdGroupAdServiceTextAd(
                custom_parameters = yahoo_display_api.models.ad_group_ad_service_custom_parameters.AdGroupAdServiceCustomParameters(
                    is_remove = 'TRUE', 
                    parameters = [
                        yahoo_display_api.models.ad_group_ad_service_custom_parameter.AdGroupAdServiceCustomParameter(
                            key = '0', 
                            value = '0', )
                        ], ), 
                description = '0', 
                description2 = '0', 
                display_url = '0', 
                display_url_level = 'DOMAIN', 
                final_url = '0', 
                smartphone_final_url = '0', 
                headline = '0', 
                is_remove_smartphone_final_url = 'TRUE', 
                is_remove_tracking_url = 'TRUE', 
                tracking_url = '0', 
                url = '0'
            )
        else :
            return AdGroupAdServiceTextAd(
        )

    def testAdGroupAdServiceTextAd(self):
        """Test AdGroupAdServiceTextAd"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
