# coding: utf-8

"""
    Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference

    <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v6/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import yahoo_display_api
from yahoo_display_api.models.recommendation_service_page import RecommendationServicePage  # noqa: E501
from yahoo_display_api.rest import ApiException

class TestRecommendationServicePage(unittest.TestCase):
    """RecommendationServicePage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RecommendationServicePage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = yahoo_display_api.models.recommendation_service_page.RecommendationServicePage()  # noqa: E501
        if include_optional :
            return RecommendationServicePage(
                total_num_entries = 56, 
                values = [
                    yahoo_display_api.models.recommendation_service_value.RecommendationServiceValue(
                        errors = [
                            yahoo_display_api.models.error.Error(
                                code = '0', 
                                message = '0', 
                                details = [
                                    yahoo_display_api.models.error_detail.ErrorDetail(
                                        request_key = '0', 
                                        request_value = '0', )
                                    ], )
                            ], 
                        recommendation = yahoo_display_api.models.recommendation.Recommendation(
                            type = 'DAILY_BUDGET_OVER', 
                            campaign_bidding_strategy_to_target_cpa = yahoo_display_api.models.recommendation_service_campaign_bidding_strategy_to_target_cpa.RecommendationServiceCampaignBiddingStrategyToTargetCpa(
                                campaign_bidding_strategy_to_target_cpa_campaign_list = [
                                    yahoo_display_api.models.recommendation_service_campaign_bidding_strategy_to_target_cpa_campaign.RecommendationServiceCampaignBiddingStrategyToTargetCpaCampaign(
                                        recommendation_id = 56, 
                                        campaign_id = 56, 
                                        campaign_name = '0', 
                                        current_budget = 56, 
                                        current_campaign_bidding_strategy_type = '0', 
                                        current_max_cpc_bid_value = 56, 
                                        recommended_campaign_bidding_strategy_type = '0', 
                                        recommended_target_cpa_bid_value = 56, )
                                    ], ), 
                            daily_budget_over = yahoo_display_api.models.recommendation_service_daily_budget_over.RecommendationServiceDailyBudgetOver(
                                daily_budget_over_campaign_list = [
                                    yahoo_display_api.models.recommendation_service_daily_budget_over_campaign.RecommendationServiceDailyBudgetOverCampaign(
                                        recommendation_id = 56, 
                                        campaign_id = 56, 
                                        campaign_name = '0', 
                                        current_budget = 56, )
                                    ], ), 
                            imps_share_budget_loss_over = yahoo_display_api.models.recommendation_service_imps_share_budget_loss_over.RecommendationServiceImpsShareBudgetLossOver(
                                imps_share_budget_loss_over_campaign_list = [
                                    yahoo_display_api.models.recommendation_service_imps_share_budget_loss_over_campaign.RecommendationServiceImpsShareBudgetLossOverCampaign(
                                        recommendation_id = 56, 
                                        campaign_id = 56, 
                                        campaign_name = '0', 
                                        current_budget = 56, 
                                        recommended_budget = 56, )
                                    ], ), 
                            search_keyword_idea = yahoo_display_api.models.recommendation_service_search_keyword_idea.RecommendationServiceSearchKeywordIdea(
                                search_keyword_idea_search_keyword_list = [
                                    yahoo_display_api.models.recommendation_service_search_keyword_idea_search_keyword_list.RecommendationServiceSearchKeywordIdeaSearchKeywordList(
                                        recommendation_id = 56, 
                                        current_search_keyword_list_id = 56, 
                                        current_search_keyword_list_name = '0', 
                                        current_search_keyword_recency = '0', 
                                        current_search_keyword_frequency = '0', 
                                        recommended_search_keyword_id = 56, 
                                        recommended_search_keyword = '0', 
                                        desktop_search_volume = 56, 
                                        smart_phone_search_volume = 56, 
                                        tablet_search_volume = 56, )
                                    ], ), 
                            campaigns_for_adding_ads = yahoo_display_api.models.recommendation_service_campaigns_for_adding_ads.RecommendationServiceCampaignsForAddingAds(
                                campaigns_for_adding_ads_list = [
                                    yahoo_display_api.models.recommendation_service_campaigns_for_adding_ads_campaign.RecommendationServiceCampaignsForAddingAdsCampaign(
                                        recommendation_id = 56, 
                                        campaign_id = 56, 
                                        campaign_name = '0', 
                                        recommendation_media_ad_format = [
                                            '0'
                                            ], )
                                    ], ), ), 
                        operation_succeeded = True, )
                    ]
            )
        else :
            return RecommendationServicePage(
        )

    def testRecommendationServicePage(self):
        """Test RecommendationServicePage"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
