# coding: utf-8

"""
    Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference

    <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v6/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v6
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import yahoo_display_api
from yahoo_display_api.models.brand_lift import BrandLift  # noqa: E501
from yahoo_display_api.rest import ApiException

class TestBrandLift(unittest.TestCase):
    """BrandLift unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BrandLift
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = yahoo_display_api.models.brand_lift.BrandLift()  # noqa: E501
        if include_optional :
            return BrandLift(
                account_id = 56, 
                campaign_id = 56, 
                brand_lift_id = 56, 
                questions = [
                    yahoo_display_api.models.brand_lift_service_question.BrandLiftServiceQuestion(
                        question_id = 56, 
                        goal = 'AD_RECALL', 
                        pre_approve_id = '0', 
                        question = '0', 
                        answer_option1 = '0', 
                        answer_option2 = '0', 
                        answer_option3 = '0', 
                        answer_option4 = '0', 
                        answer_option5 = '0', )
                    ], 
                approval_status = 'APPROVED', 
                disapproval_reason = '0', 
                review_complete_date = '0', 
                disapproval_reason_codes = [
                    '0'
                    ], 
                submit_date = '0', 
                campaign_start_date = '0', 
                campaign_name = '0', 
                notification_business_ids = [
                    '0'
                    ]
            )
        else :
            return BrandLift(
        )

    def testBrandLift(self):
        """Test BrandLift"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
