TIMESTAMP = 'timestamp'
ICAO = 'icao'

LAST_UPDATE = 'last_update'

SESSION = 'session'
SESSION_UUID = 'session_uuid'
HOST = 'host'
PORT = 'port'
START = 'start'
STOP = 'stop'
DURATION = 'duration'

IDENT = 'ident'
CALLSIGN = 'callsign'
TYPECODE = 'typecode'
CATEGORY = 'category'

VELOCITY = 'velocity'
SPEED = 'speed'
SPEED_TYPE = 'speed_type'
VERTICAL_SPEED = 'vertical_speed'
VERTICAL_SPEED_SRC = 'vertical_speed_src'
ANGLE = 'angle'
ANGLE_SRC = 'angle_src'

POSITION = 'position'
LATITUDE = 'latitude'
LONGITUDE = 'longitude'
ALTITUDE = 'altitude'
ALTITUDE_SRC = 'altitude_src'