from typing import Any, List

class Default: ...

DEFAULT: Any

class PasswordCard:
    version: Any
    def __init__(self, keyword_length: None, segment_length: int = ..., seed=...) -> None: ...
    def save_png(self, filename: str, font_size: int = ..., background: str = ..., font: str = ..., font_color: str = ...) -> None: ...
    def save_text(self, filename) -> None: ...
    def raw(self) -> List[List[str]]: ...
    def get_password(self, keyword: str) -> str: ...
    def __getitem__(self, row_column: None) -> None: ...
    def __eq__(self, other) -> bool: ...

def save_card(card: PasswordCard, filename: str) -> None: ...
def load_card(filename: str) -> PasswordCard: ...
