# Generated by Django 3.1.6 on 2021-02-18 13:47

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_auto_20210218_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='referees_max',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='props',
            field=bitfield.models.BitField((('active', 'active'), ('national', 'national'), ('show_league', 'show_league'), ('show_region', 'show_region'), ('up_selected', 'up_selected'), ('up2_selected', 'up2_selected'), ('down_selected', 'down_selected'), ('down_selected', 'down2_selected'), ('calendar_created', 'calendar_created'), ('show_numbers', 'show_numbers'), ('show_player_number', 'show_player_number'), ('show_stats', 'show_stats'), ('show_empty_cells', 'show_empty_cells')), db_index=True, default=1),
        ),
    ]
