# Generated by Django 3.1.6 on 2021-02-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0030_calendar_formation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='disqualification_zones',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='edited_by',
        ),
    ]
