# Generated by Django 3.1.7 on 2021-03-04 08:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20210304_0657'),
        ('common', '0023_auto_20210303_0942'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0070_auto_20210304_0816'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='club_admins',
            unique_together={('user', 'club', 'post', 'props')},
        ),
        migrations.AlterUniqueTogether(
            name='club_contacts',
            unique_together={('person', 'club', 'post', 'priority', 'props')},
        ),
        migrations.AlterUniqueTogether(
            name='clubs_clothes',
            unique_together={('clothes', 'club')},
        ),
    ]
