# Generated by Django 3.1.7 on 2021-03-05 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0040_auto_20210305_0818'),
        ('competitions', '0094_auto_20210305_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referees',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='user_ext.persons'),
        ),
    ]
