# Generated by Django 3.1.7 on 2021-03-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0103_auto_20210306_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='disqualification_condition',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='loss_points_rule',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='referees_max',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
