# Generated by Django 3.1.7 on 2021-03-06 13:55

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0115_auto_20210306_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='division',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competitions.divisions'),
        ),
    ]
