# Generated by Django 3.1.7 on 2021-03-06 15:27

import django.utils.timezone
from django.db import migrations, models

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0136_remove_tournament_members_old_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament_member_doubles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('club', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, related_name='Tournament_member_club', to='competitions.clubs')),
                ('club_double', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, related_name='Tournament_member_club_double', to='competitions.clubs')),
                ('tournament', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, related_name='Tournament_member_doubles_tournament', to='competitions.tournaments')),
                ('tournament_double', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, related_name='Tournament_member_doubles_tournament_double', to='competitions.tournaments')),
            ],
            options={
                'verbose_name': 'Списки клубов-участников турнира',
                'unique_together': {('club', 'club_double', 'tournament_double', 'tournament')},
            },
        ),
    ]
