# Generated by Django 3.1.7 on 2021-03-10 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0168_auto_20210310_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='away_shirt',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='away_shirt_keeper',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='home_shirt',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='home_shirt_keeper',
        ),
        migrations.AddField(
            model_name='calendar',
            name='division',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='competitions.divisions'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='editor',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
