# Generated by Django 3.1.7 on 2021-03-12 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0191_auto_20210311_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assists',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='assists',
            name='old_id',
        ),
    ]
