# Generated by Django 3.1.7 on 2021-03-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0204_auto_20210324_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players_text_informations',
            name='text',
            field=models.TextField(),
        ),
    ]
