# Generated by Django 3.1.7 on 2021-03-25 04:51

import django.utils.timezone
from django.db import migrations, models

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0205_auto_20210324_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='old_ids',
        ),
        migrations.CreateModel(
            name='Player_old_ids',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('old_id', models.BigIntegerField(db_index=True)),
                ('player', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.players')),
            ],
            options={
                'verbose_name': 'Ссылки на старых Players',
            },
        ),
    ]
