# Generated by Django 3.1.7 on 2021-03-25 04:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0206_auto_20210325_0451'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player_old_ids',
            unique_together={('player', 'old_id')},
        ),
    ]
