# Generated by Django 3.1.7 on 2021-03-26 09:49

from django.db import migrations

import isc_common.fields.code_field


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0216_auto_20210326_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_types',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(unique=True),
        ),
        migrations.AlterField(
            model_name='club_histories',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(unique=True),
        ),
        migrations.AlterField(
            model_name='disqualification_types',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(unique=True),
        ),
        migrations.AlterField(
            model_name='disqualification_zones',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(unique=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(unique=True),
        ),
        migrations.AlterField(
            model_name='goals_type',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(unique=True),
        ),
        migrations.AlterField(
            model_name='match_resaults',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(unique=True),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(unique=True),
        ),
        migrations.AlterField(
            model_name='matchdays',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(unique=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(unique=True),
        ),
        migrations.AlterField(
            model_name='protocol_types',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(unique=True),
        ),
        migrations.AlterField(
            model_name='referee_category',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(unique=True),
        ),
        migrations.AlterField(
            model_name='statistics_types',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(unique=True),
        ),
        migrations.AlterField(
            model_name='tournament_types',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(unique=True),
        ),
    ]
