# Generated by Django 3.1.7 on 2021-03-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0222_fouls_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepers',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='match_resaults',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='match_stats',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
