# Generated by Django 3.1.7 on 2021-03-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0224_disqualifications_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disqualifications',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
