# Generated by Django 3.2 on 2021-04-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0257_alter_players_change_history_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players_change_history',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
