# Generated by Django 3.2 on 2021-04-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0266_matchdays_old_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchdays',
            unique_together={('tournament', 'tour', 'date')},
        ),
    ]
