# Generated by Django 3.1.8 on 2021-04-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0269_auto_20210423_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdays',
            name='old_tour',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchdays',
            name='old_tournament_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
