# Generated by Django 3.1.8 on 2021-04-23 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0270_auto_20210423_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='players_change_history',
            name='date_old',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players_change_history',
            name='editor_id_old',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='players_change_history',
            name='player_id_old',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='players_change_history',
            unique_together={('date', 'editor', 'player', 'date_old', 'editor_id_old', 'player_id_old')},
        ),
    ]
