# Generated by Django 3.2.4 on 2021-06-11 05:13

import bitfield.models
from django.db import migrations, models
import django.utils.timezone
import isc_common.fields.name_field


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0283_clubs_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players_view',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('active', models.BooleanField()),
                ('debut', models.DateField(blank=True, null=True)),
                ('delayed_lockout_date', models.DateField(blank=True, null=True)),
                ('height', models.SmallIntegerField()),
                ('included', models.DateField(blank=True, null=True)),
                ('medical_admission_date', models.DateField(blank=True, null=True)),
                ('number', models.SmallIntegerField(blank=True, null=True)),
                ('size_of_photo', models.IntegerField()),
                ('weight', models.SmallIntegerField()),
                ('photo_image_src', isc_common.fields.name_field.NameField(blank=True, null=True)),
                ('photo_real_name', isc_common.fields.name_field.NameField(blank=True, null=True)),
                ('props', bitfield.models.BitField((('active', 'active'), ('shadow', 'shadow'), ('blocked', 'blocked'), ('disqualification', 'disqualification'), ('lockout', 'lockout'), ('delayed_lockout', 'delayed_lockout'), ('medical_lockout', 'medical_lockout')), db_index=True, default=1)),
            ],
            options={
                'verbose_name': 'Игроки',
                'db_table': 'competitions_players_view',
                'managed': False,
            },
        ),
    ]
