# Generated by Django 3.2.4 on 2021-06-26 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0291_remove_calendar_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='match_cast',
        ),
    ]
