# Generated by Django 3.2.4 on 2021-06-28 18:26

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0297_command_structure_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_histories',
            name='props',
            field=bitfield.models.BitField((('game_started', 'game_started'), ('substituted', 'substituted'), ('keeper', 'keeper'), ('hidden', 'Скрывать ФИО')), db_index=True, default=0),
        ),
    ]
