# Generated by Django 3.2.4 on 2021-06-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0307_command_structure_tmp_tournament'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calendar_view',
            table='competitions_calendar_view',
        ),
    ]
