# Generated by Django 3.2.4 on 2021-07-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0310_alter_tournaments_props'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Command_structure_tmp',
        ),
    ]
