# Generated by Django 3.2.4 on 2021-07-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0313_alter_player_histories_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player_histories',
            unique_together={('club', 'player', 'match')},
        ),
    ]
