# Generated by Django 3.2.6 on 2021-08-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0108_alter_users_old_images_unique_together'),
        ('competitions', '0341_alter_referees_images_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournaments_images',
            unique_together={('image', 'main_model', 'type', 'deleted_at')},
        ),
    ]
