# Generated by Django 3.2.6 on 2021-08-30 14:06

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0352_auto_20210829_1347'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='divisions',
            constraint=models.CheckConstraint(check=models.Q(('id', django.db.models.expressions.F('parent_id')), _negated=True), name='c_bfd19137_90f2_433a_94d5_72e14796b945'),
        ),
    ]
