# Generated by Django 3.2.6 on 2021-08-31 11:53

import bitfield.models
from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0357_auto_20210830_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagues',
            name='editor',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='props',
            field=bitfield.models.BitField((('active', 'active'), ('parimatch', 'parimatch'), ('submenu', 'submenu'), ('nonphoto', 'nonphoto'), ('show_in_menu', 'show_in_menu'), ('show_referee_photo_in_protocols', 'Показывать фото судей в протоколах'), ('show_stadium_photo_in_protocols', 'Показывать фото стадиона в протоколах'), ('show_shirt_in_protocols', 'Показывать майки в протоколах')), db_index=True, default=1),
        ),
    ]
