# Generated by Django 3.2.6 on 2021-08-31 22:34
import django
import isc_common
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0360_auto_20210831_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_images',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.image_types'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club_logo_history_images',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.image_types'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubs_images',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.image_types'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='divisions_images',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.image_types'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leagues_images',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.image_types'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='players_images',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.image_types'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referees_images',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.image_types'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournaments_images',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.image_types'),
            preserve_default=False,
        ),
    ]
