# Generated by Django 3.2.6 on 2021-09-01 14:12

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0070_interregion'),
        ('competitions', '0368_alter_squads_match_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='interregion1',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='region.interregion'),
        ),
    ]
