# Generated by Django 3.2.6 on 2021-09-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0370_remove_clubs_interregion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubs',
            old_name='interregion1',
            new_name='interregion',
        ),
    ]
