# Generated by Django 3.2.6 on 2021-09-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0374_delete_clubs_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='old_superclub_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
