# Generated by Django 3.2.7 on 2021-09-17 07:24

from django.db import migrations
import isc_common.fields.code_field


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0402_auto_20210916_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='squads',
            name='old_id',
            field=isc_common.fields.code_field.CodeField(blank=True, null=True, unique=True),
        ),
    ]
