# Generated by Django 3.2.7 on 2021-09-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0404_auto_20210917_0726'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='squads',
            constraint=models.UniqueConstraint(condition=models.Q(('club_id_old', None), ('player_id_old', None), ('tournament_id_old', None)), fields=('club', 'tournament', 'player'), name='Squads_unique_constraint_0'),
        ),
        migrations.AddConstraint(
            model_name='squads',
            constraint=models.UniqueConstraint(condition=models.Q(('club_id_old', None), ('player_id_old', None)), fields=('club', 'tournament', 'player', 'tournament_id_old'), name='Squads_unique_constraint_1'),
        ),
        migrations.AddConstraint(
            model_name='squads',
            constraint=models.UniqueConstraint(condition=models.Q(('club_id_old', None), ('tournament_id_old', None)), fields=('club', 'tournament', 'player', 'player_id_old'), name='Squads_unique_constraint_2'),
        ),
        migrations.AddConstraint(
            model_name='squads',
            constraint=models.UniqueConstraint(condition=models.Q(('club_id_old', None)), fields=('club', 'tournament', 'player', 'player_id_old', 'tournament_id_old'), name='Squads_unique_constraint_3'),
        ),
        migrations.AddConstraint(
            model_name='squads',
            constraint=models.UniqueConstraint(condition=models.Q(('player_id_old', None), ('tournament_id_old', None)), fields=('club', 'club_id_old', 'tournament', 'player'), name='Squads_unique_constraint_4'),
        ),
        migrations.AddConstraint(
            model_name='squads',
            constraint=models.UniqueConstraint(condition=models.Q(('player_id_old', None)), fields=('club', 'club_id_old', 'tournament', 'player', 'tournament_id_old'), name='Squads_unique_constraint_5'),
        ),
        migrations.AddConstraint(
            model_name='squads',
            constraint=models.UniqueConstraint(condition=models.Q(('tournament_id_old', None)), fields=('club', 'club_id_old', 'tournament', 'player', 'player_id_old'), name='Squads_unique_constraint_6'),
        ),
        migrations.AddConstraint(
            model_name='squads',
            constraint=models.UniqueConstraint(fields=('club', 'club_id_old', 'tournament', 'player', 'player_id_old', 'tournament_id_old'), name='Squads_unique_constraint_7'),
        ),
    ]
