
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-19T10:48:25-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed9b7f3fa89ea471eb257b13d49c2b9146c73ece",
 "version": "4.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
