[tool.poetry]
name = "opyml"
license = "MIT OR Apache-2.0"
version = "0.1.0"
description = "An OPML library for Python."
authors = ["Holllo <helllo@holllo.cc>"]

[tool.poetry.dependencies]
defusedxml = "^0.7.1"
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
mypy = "^0.910"
pdoc = "^8.0.0"
pytest = "^5.2"
pytest-cov = "^3.0.0"
pytest-snapshot = "^0.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
