[tool.poetry]
name = "django-settings-env"
version = "3.0.1"
description = "12-factor.net settings support for Django based on envex"
authors = ["David Nugent <davidn@uniquode.io>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.0"
envex = "^1.0"
django-class-settings = { version = "^0.2", optional = true }

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-pythonpath = "*"

[tool.poetry.extras]
django-class-settings = ["django-class-settings"]

[tool.pytest.ini-options]
minversion = "6.0"
python_paths = [
    "django_settings_env"
]
testpaths = [
    "tests"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
