
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-21T11:28:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "43fccb8f75bd9bd11b2da3812c020495f4c09e91",
 "version": "0.7.1.post.dev116"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
