#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['kampvie_example']

package_data = \
{'': ['*']}

setup(name='kampvie_example',
      version='0.1',
      description='This is an example of how to publish your first package to the internet community',
      author=None,
      author_email='Le Tanh Sang <sang.tanhle@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
     )
