# Generated by Django 3.2.8 on 2021-10-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_theme", "0002_theme_login_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="login_logo",
            field=models.FileField(
                max_length=300, null=True, upload_to="theme", verbose_name="LOGIN_LOGO"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="tab_logo",
            field=models.FileField(
                max_length=300, null=True, upload_to="theme", verbose_name="TAB_LOGO"
            ),
        ),
    ]
