compute_recipe:
    - "_create_setup_folders"
    - "_create_component_folders"
    - "initialize_experiment_logfile"
    - "pism_set_kv_pairs"
    - "pism_set_flags"
    - "pism_set_couplers"
    - "pism_override_file"
    - "_write_finalized_config"
    - "assemble_filelists"
    - "copy_tools_to_thisrun"
    - "_copy_preliminary_files_from_experiment_to_thisrun"
    - "_show_simulation_info"
    - "copy_files_to_thisrun"
    - "pism_assemble_command"
    - "add_batch_hostfile"
    - "copy_files_to_work"
    - "write_simple_runscript"
    - "report_missing_files"
    - "database_entry"
    - "submit"
