# Generated by Django 3.1.6 on 2021-03-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0016_remove_region_zones_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='region_zones',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
