# Generated by Django 3.1.6 on 2021-03-01 09:33

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0017_region_zones_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='regions',
            name='zone',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='region.region_zones'),
        ),
    ]
