# Generated by Django 3.1.6 on 2021-03-02 09:30

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0034_auto_20210302_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='region',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='region.regions'),
        ),
    ]
