# Generated by Django 3.1.6 on 2021-03-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20210301_1433'),
        ('region', '0036_auto_20210302_0934'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city_images',
            unique_together={('main_model', 'image')},
        ),
    ]
