# Generated by Django 3.1.7 on 2021-03-24 05:27

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('isc_common', '0088_auto_20210323_0553'),
        ('region', '0041_auto_20210315_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region_zone_images',
            name='image',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.images'),
        ),
    ]
