# Generated by Django 3.2.6 on 2021-08-29 13:47

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0063_regions_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_images',
            name='main_model',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='region.cities'),
        ),
        migrations.AlterField(
            model_name='region_images',
            name='main_model',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='region.regions'),
        ),
        migrations.AlterField(
            model_name='region_zone_images',
            name='main_model',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='region.region_zones'),
        ),
    ]
