# Generated by Django 3.2.6 on 2021-09-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0072_auto_20210901_1446'),
    ]

    operations = [
        migrations.RunSQL('update competitions_clubs set interregion_id = 1 where interregion_id is null')
    ]
