# Generated by Django 3.2.8 on 2021-10-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employeeid',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
