[tool.poetry]
name = "programmable-pomodoro"
version = "0.1.1"
description = "A programmable pomodoro timer."
authors = ["Matthew Caseres <matthewcaseres@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.7"
aioconsole = "^0.3.2"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^6.4.1"
gspread = "^4.0.1"
autopep8 = "^1.5.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
