[tool.poetry]
name = "plagdef"
version = "1.3.12"
description = "A tool which makes life hard for students who try to make theirs simple."
authors = ["Yannik Queisler"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/devWhyqueue/plagdef"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent"
]
exclude = ["*/tests"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
beautifulsoup4 = "^4.10"
click = "^8.0"
jsonpickle = "^2.0"
networkx = "^2.6"
numpy = "^1.21"
pdfplumber = "^0.5.28"
ocrmypdf = "^12.6"
pyside6 = "~=6"
python-magic = "^0.4"
sortedcontainers = "^2.3"
stanza = "^1.2"
tqdm = "^4.60"
urlextract = "^1.3"
Werkzeug = "^2.0"

[tool.poetry.dev-dependencies]
coverage = "^6.0"
flake8 = "^3.7"
fpdf2 = "^2.3"
pytest = "^6.2"
tox = "^3.14"
tox-gh-actions = "^2.4"

[tool.poetry.scripts]
plagdef = "plagdef.app:cli"
plagdef-gui = "plagdef.app:gui"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py38,py39

[gh-actions]
python =
    3.8: py38
    3.9: py39

[testenv:py38]
whitelist_externals = make
commands = make test-ci

[testenv:py39]
whitelist_externals = make
commands = make coverage-ci
"""

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
