# Generated by Django 3.1.6 on 2021-03-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0048_auto_20210301_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasons',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
