# Generated by Django 3.1.6 on 2021-03-01 16:56

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0050_auto_20210301_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagues',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='leagues',
            name='position',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='props',
            field=bitfield.models.BitField((('active', 'active'), ('parimatch', 'parimatch'), ('submenu', 'submenu'), ('nonphoto', 'nonphoto'), ('show_in_menu', 'show_in_menu'), ('show_referee_photo_in_protocols', 'show_referee_photo_in_protocols'), ('show_stadium_photo_in_protocols', 'show_stadium_photo_in_protocols'), ('show_shirt_in_protocols', 'show_shirt_in_protocols')), db_index=True, default=1),
        ),
    ]
