# Generated by Django 3.1.7 on 2021-03-03 13:40

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0061_auto_20210303_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='league',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competitions.leagues'),
        ),
    ]
