# Generated by Django 3.1.7 on 2021-03-04 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0023_auto_20210303_0942'),
        ('competitions', '0072_auto_20210304_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_contacts',
            name='post',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.posts'),
        ),
        migrations.AlterUniqueTogether(
            name='club_contacts',
            unique_together={('person', 'club', 'priority', 'props')},
        ),
    ]
