# Generated by Django 3.1.7 on 2021-03-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0081_auto_20210304_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disqualification_zones',
            old_name='number_of_yellowsOLD',
            new_name='number_of_yellowsold',
        ),
    ]
