# Generated by Django 3.1.7 on 2021-03-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0091_auto_20210305_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='referees',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
