# Generated by Django 3.1.7 on 2021-03-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0096_auto_20210305_0846'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referee_zone',
            unique_together={('referee', 'league')},
        ),
    ]
