# Generated by Django 3.1.7 on 2021-03-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0124_auto_20210306_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='disqualification_condition',
            field=models.SmallIntegerField(default=None),
        ),
    ]
