# Generated by Django 3.1.7 on 2021-03-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0133_remove_tournament_members_tournament'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournament_members',
            unique_together={('club', 'props', 'position')},
        ),
    ]
