# Generated by Django 3.1.7 on 2021-03-06 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0043_auto_20210305_1207'),
        ('competitions', '0142_auto_20210306_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='person',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='user_ext.persons'),
        ),
    ]
