# Generated by Django 3.1.7 on 2021-03-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0147_auto_20210306_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='delayed_lockout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
