# Generated by Django 3.1.7 on 2021-03-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0152_players_images_players_text_informations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players_text_informations',
            name='text',
            field=models.TextField(db_index=True),
        ),
    ]
