# Generated by Django 3.1.7 on 2021-03-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0153_auto_20210307_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='included',
            field=models.DateField(blank=True, null=True),
        ),
    ]
