# Generated by Django 3.1.7 on 2021-03-09 08:33

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0077_image_types_images_links_text_informations'),
        ('competitions', '0157_auto_20210307_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_text_informations',
            name='text',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.text_informations'),
        ),
        migrations.AlterField(
            model_name='club_logo_history_images',
            name='image',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.images'),
        ),
        migrations.AlterField(
            model_name='clubs_images',
            name='image',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.images'),
        ),
        migrations.AlterField(
            model_name='clubs_links',
            name='link',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.links'),
        ),
        migrations.AlterField(
            model_name='clubs_text_informations',
            name='text',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.text_informations'),
        ),
        migrations.AlterField(
            model_name='disqualifications_text_informations',
            name='text',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.text_informations'),
        ),
        migrations.AlterField(
            model_name='divisions_images',
            name='image',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.images'),
        ),
        migrations.AlterField(
            model_name='leagues_images',
            name='image',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.images'),
        ),
        migrations.AlterField(
            model_name='leagues_links',
            name='link',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.links'),
        ),
        migrations.AlterField(
            model_name='leagues_text_informations',
            name='text',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.text_informations'),
        ),
        migrations.AlterField(
            model_name='players_images',
            name='image',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.images'),
        ),
        migrations.AlterField(
            model_name='referees_images',
            name='image',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.images'),
        ),
        migrations.AlterField(
            model_name='tournaments_images',
            name='image',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.images'),
        ),
    ]
