# Generated by Django 3.1.7 on 2021-03-10 05:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0160_auto_20210310_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players_change_history_text_informations',
            old_name='league',
            new_name='player_change_history',
        ),
    ]
