# Generated by Django 3.1.7 on 2021-03-10 08:08

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0173_auto_20210310_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='division',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competitions.divisions'),
        ),
    ]
