# Generated by Django 3.1.7 on 2021-03-10 12:51

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0181_auto_20210310_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_resaults',
            name='match',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.calendar'),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='match',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.calendar'),
        ),
    ]
