# Generated by Django 3.1.7 on 2021-03-15 11:11

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('region', '0041_auto_20210315_1100'),
        ('competitions', '0193_auto_20210315_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='league',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='competitions.leagues'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubs',
            name='region',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='region.regions'),
            preserve_default=False,
        ),
    ]
