# Generated by Django 3.1.7 on 2021-03-23 05:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0198_auto_20210322_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='region',
        ),
    ]
