# Generated by Django 3.1.7 on 2021-03-24 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('isc_common', '0088_auto_20210323_0553'),
        ('competitions', '0200_auto_20210324_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='players',
            name='deliting',
        ),
        migrations.RemoveField(
            model_name='players',
            name='editing',
        ),
        migrations.RemoveField(
            model_name='players',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='players',
            name='id',
        ),
        migrations.RemoveField(
            model_name='players',
            name='lastmodified',
        ),
        migrations.AddField(
            model_name='players',
            name='auditmodelex_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='isc_common.auditmodelex'),
            preserve_default=False,
        ),
    ]
