# Generated by Django 3.1.7 on 2021-03-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0214_remove_calendar_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='assists',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
