# Generated by Django 3.1.7 on 2021-03-29 15:12

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0218_auto_20210326_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='match',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.calendar'),
        ),
    ]
