# Generated by Django 3.1.7 on 2021-03-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0229_auto_20210330_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fines',
            name='remove_restore_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
