# Generated by Django 3.1.7 on 2021-03-30 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('isc_common', '0090_auto_20210326_0949'),
        ('competitions', '0232_auto_20210330_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goals',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='deliting',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='editing',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='id',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='lastmodified',
        ),
        migrations.AddField(
            model_name='goals',
            name='auditmodelex_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='isc_common.auditmodelex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goals',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
