# Generated by Django 3.2 on 2021-04-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0252_auto_20210410_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_admins',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
