# Generated by Django 3.1.8 on 2021-04-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0273_alter_calendar_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_members',
            name='club_id_old',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament_members',
            name='tournament_id_old',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tournament_members',
            unique_together={('club', 'props', 'position', 'tournament_id_old', 'club_id_old')},
        ),
    ]
