# Generated by Django 3.2.4 on 2021-06-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0287_alter_player_histories_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='disqualification_zones_view',
            table='competitions_disqualification_zones_view',
        ),
    ]
