# Generated by Django 3.2.4 on 2021-06-26 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0290_alter_goals_minute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='parent',
        ),
    ]
