# Generated by Django 3.2.4 on 2021-06-28 13:28

from django.db import migrations
import isc_common.fields.code_field


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0295_player_histories_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_histories',
            name='num',
            field=isc_common.fields.code_field.CodeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='calendar_view',
            table='competitions_calendar_mview',
        ),
    ]
