# Generated by Django 3.2.4 on 2021-06-28 22:31

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0301_command_structure_tmp_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='command_structure_tmp',
            name='player',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='competitions.players'),
            preserve_default=False,
        ),
    ]
