# Generated by Django 3.2.4 on 2021-06-29 13:53

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0306_command_structure_tmp_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='command_structure_tmp',
            name='tournament',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='competitions.tournaments'),
            preserve_default=False,
        ),
    ]
