# Generated by Django 3.2.6 on 2021-08-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0322_remove_tournaments_technical_defeat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournaments',
            old_name='technic_defeat',
            new_name='technical_defeat',
        ),
    ]
