# Generated by Django 3.2.6 on 2021-08-19 14:56

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0329_auto_20210819_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='down2_selected',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='down_selected',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='up2_selected',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='up_selected',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='props',
            field=bitfield.models.BitField((('active', 'active'), ('national', 'national'), ('show_league', 'show_league'), ('show_region', 'show_region'), ('unused', 'up_selected'), ('unused1', 'up2_selected'), ('unused2', 'down_selected'), ('unused3', 'down2_selected'), ('calendar_created', 'calendar_created'), ('show_numbers', 'show_numbers'), ('show_player_number', 'show_player_number'), ('show_stats', 'show_stats'), ('show_empty_cells', 'show_empty_cells'), ('favorites', 'Избранные'), ('hidden', 'Скрывать ФИО'), ('loss_points_rule', 'Подключить расстановку команд в текущей (не итоговой таблице), в случае равенства очков, по потерянным очкам')), db_index=True, default=1),
        ),
    ]
