# Generated by Django 3.2.6 on 2021-08-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0107_alter_users_images_unique_together'),
        ('competitions', '0336_auto_20210823_0726'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendar_images',
            unique_together={('image', 'main_model', 'type', 'deleted_at')},
        ),
    ]
