# Generated by Django 3.2.7 on 2021-09-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0376_club_histories_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='size_of_photo',
        ),
    ]
