# Generated by Django 3.2.7 on 2021-09-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0388_remove_penalties_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalties',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
