# Generated by Django 3.2.7 on 2021-09-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0394_alter_player_histories_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='player_histories',
            constraint=models.UniqueConstraint(condition=models.Q(('club_id_old', None), ('match_id_old', None), ('player_id_old', None)), fields=('club', 'match', 'player'), name='Player_histories_unique_constraint_0'),
        ),
        migrations.AddConstraint(
            model_name='player_histories',
            constraint=models.UniqueConstraint(condition=models.Q(('club_id_old', None), ('player_id_old', None)), fields=('club', 'match', 'match_id_old', 'player'), name='Player_histories_unique_constraint_1'),
        ),
        migrations.AddConstraint(
            model_name='player_histories',
            constraint=models.UniqueConstraint(condition=models.Q(('club_id_old', None), ('match_id_old', None)), fields=('club', 'match', 'player', 'player_id_old'), name='Player_histories_unique_constraint_2'),
        ),
        migrations.AddConstraint(
            model_name='player_histories',
            constraint=models.UniqueConstraint(condition=models.Q(('club_id_old', None)), fields=('club', 'match', 'match_id_old', 'player', 'player_id_old'), name='Player_histories_unique_constraint_3'),
        ),
        migrations.AddConstraint(
            model_name='player_histories',
            constraint=models.UniqueConstraint(condition=models.Q(('match_id_old', None), ('player_id_old', None)), fields=('club', 'club_id_old', 'match', 'player'), name='Player_histories_unique_constraint_4'),
        ),
        migrations.AddConstraint(
            model_name='player_histories',
            constraint=models.UniqueConstraint(condition=models.Q(('player_id_old', None)), fields=('club', 'club_id_old', 'match', 'match_id_old', 'player'), name='Player_histories_unique_constraint_5'),
        ),
        migrations.AddConstraint(
            model_name='player_histories',
            constraint=models.UniqueConstraint(condition=models.Q(('match_id_old', None)), fields=('club', 'club_id_old', 'match', 'player', 'player_id_old'), name='Player_histories_unique_constraint_6'),
        ),
        migrations.AddConstraint(
            model_name='player_histories',
            constraint=models.UniqueConstraint(fields=('club', 'club_id_old', 'match', 'match_id_old', 'player', 'player_id_old'), name='Player_histories_unique_constraint_7'),
        ),
    ]
