# Generated by Django 3.2.7 on 2021-09-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0395_auto_20210915_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Протокол матча',
            },
        ),
    ]
