# Generated by Django 3.2.7 on 2021-09-16 02:51

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0397_alter_match_protocol_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_histories',
            name='props',
            field=bitfield.models.BitField((('game_started', 'game_started'), ('substituted', 'substituted'), ('keeper', 'keeper'), ('hidden', 'Скрывать ФИО'), ('syncked', 'Синхронизировано')), db_index=True, default=0),
        ),
        migrations.AlterModelTable(
            name='match_protocol',
            table='competitions_match_protocol_view',
        ),
    ]
