# Generated by Django 3.1.6 on 2021-03-02 14:12

import django.utils.timezone
from django.db import migrations, models

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0056_auto_20210302_0641'),
        ('inventory', '0004_auto_20210302_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='club',
        ),
        migrations.CreateModel(
            name='Clothes_clubs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('cloth', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='inventory.clothes')),
                ('club', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.clubs')),
            ],
            options={
                'verbose_name': 'Кросс таблица',
                'unique_together': {('club', 'cloth')},
            },
        ),
    ]
