# Generated by Django 3.1.7 on 2021-03-26 09:48

from django.db import migrations

import isc_common.fields.code_field


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0012_auto_20210309_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
        migrations.AlterField(
            model_name='clothes_type',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
    ]
