# Generated by Django 3.2.6 on 2021-08-31 22:37
import django
import isc_common
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_clothes_images_main_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes_images',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.image_types'),
            preserve_default=False,
        ),
    ]
