[build-system]
requires = [
    "cython",
    "numpy",
    "setuptools>=42",
    "setuptools_scm[toml]>=3.4",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "cwinpy/_version.py"