# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: unacast/bringyourownpoi/v1/bringyourownpoi_service.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List, Optional

import betterproto
import grpclib


@dataclass(eq=False, repr=False)
class CreateReportRequest(betterproto.Message):
    billing_context: str = betterproto.string_field(2)
    observation_period: "Period" = betterproto.message_field(3)
    metric_refs: List["MetricReference"] = betterproto.message_field(5)
    pois: List["PointOfInterest"] = betterproto.message_field(6)

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class MetricReference(betterproto.Message):
    metric_id: str = betterproto.string_field(1)

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class Period(betterproto.Message):
    start: "__unatype__.Date" = betterproto.message_field(1)
    end: "__unatype__.Date" = betterproto.message_field(2)

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class PointOfInterest(betterproto.Message):
    name: str = betterproto.string_field(1)
    polygon: "Polygon" = betterproto.message_field(4)

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class Polygon(betterproto.Message):
    coordinates: List["Coordinate"] = betterproto.message_field(1)

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class Coordinate(betterproto.Message):
    lon: float = betterproto.float_field(1)
    lat: float = betterproto.float_field(4)

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class CreateReportResponse(betterproto.Message):
    metrics_on_pois: List["MetricOnPois"] = betterproto.message_field(1)

    def __post_init__(self) -> None:
        super().__post_init__()


@dataclass(eq=False, repr=False)
class MetricOnPois(betterproto.Message):
    metric_id: str = betterproto.string_field(1)
    csv_result: str = betterproto.string_field(5)

    def __post_init__(self) -> None:
        super().__post_init__()


class BringYourOwnPoiServiceStub(betterproto.ServiceStub):
    """* This is the service for Bring Your Own POI (Point of interest)"""

    async def create_bring_your_own_poi_report(
        self,
        *,
        billing_context: str = "",
        observation_period: "Period" = None,
        metric_refs: Optional[List["MetricReference"]] = None,
        pois: Optional[List["PointOfInterest"]] = None,
    ) -> "CreateReportResponse":
        metric_refs = metric_refs or []
        pois = pois or []

        request = CreateReportRequest()
        request.billing_context = billing_context
        if observation_period is not None:
            request.observation_period = observation_period
        if metric_refs is not None:
            request.metric_refs = metric_refs
        if pois is not None:
            request.pois = pois

        return await self._unary_unary(
            "/unacast.bringyourownpoi.v1.BringYourOwnPOIService/CreateBringYourOwnPOIReport",
            request,
            CreateReportResponse,
        )


from ... import unatype as __unatype__
