# Generated by Django 3.1.7 on 2021-03-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20210303_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edited_by',
        ),
    ]
