# Generated by Django 3.1.7 on 2021-04-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0025_auto_20210309_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_lfl_images',
            name='date',
            field=models.FloatField(),
        ),
    ]
