
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-19T23:25:35+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "ad9bad2f63d5c39bbf685db3a0d0fa516741787a",
 "version": "4.0.0+73.gad9bad2.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
