
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-21T09:25:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c128320af9ea445cf52302371e27e11e7ebe5d9e",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
