
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-22T13:05:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e074114f3cd14c04c57465cc1538346165f3f02d",
 "version": "2544"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
