
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-25T16:01:42+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "080094d7e1842d85e084d43ce05d545423cf4a29",
 "version": "1.0a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
