# Generated by Django 3.1.6 on 2021-02-18 14:51

import django.db.models.deletion
from django.db import migrations, models

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0066_auditmodelex'),
        ('competitions', '0022_match_resaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assists',
            fields=[
                ('auditmodelex_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='isc_common.auditmodelex')),
                ('club', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.clubs')),
                ('match', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.matches')),
                ('player', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.players')),
                ('tournament', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.tournaments')),
            ],
            options={
                'verbose_name': 'Голевые пасы в сыгранных матчах. Другое название игрока: ассистент.',
            },
            bases=('isc_common.auditmodelex',),
        ),
    ]
