# Generated by Django 3.1.6 on 2021-03-01 08:40

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0047_auto_20210301_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='season',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.seasons'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='season',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.seasons'),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='season',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.seasons'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='season',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.seasons'),
        ),
    ]
