# Generated by Django 3.1.6 on 2021-03-02 16:14

import bitfield.models
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20210301_1433'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0056_auto_20210302_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='season',
        ),
        migrations.AddField(
            model_name='clubs',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='league',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='competitions.leagues'),
        ),
        migrations.CreateModel(
            name='Club_contacts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('priority', models.SmallIntegerField()),
                ('props', bitfield.models.BitField((('active', 'active'), ('leader', 'leader')), db_index=True, default=1)),
                ('club', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.clubs')),
                ('person', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('post', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='common.posts')),
            ],
            options={
                'verbose_name': 'Кросс-таблица',
            },
        ),
    ]
