# Generated by Django 3.1.7 on 2021-03-05 08:02

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0039_auto_20210302_1649'),
        ('competitions', '0092_referees_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referees',
            name='region',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='region.regions'),
        ),
    ]
