# Generated by Django 3.1.7 on 2021-03-06 13:42

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0013_auto_20210302_1245'),
        ('competitions', '0109_auto_20210306_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='field',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='constructions.fields'),
        ),
    ]
