# Generated by Django 3.1.7 on 2021-03-06 13:45

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0110_auto_20210306_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='referee_category',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competitions.referee_category'),
        ),
    ]
