# Generated by Django 3.1.7 on 2021-03-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0125_auto_20210306_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='number_of_players',
            field=models.SmallIntegerField(default=None),
        ),
    ]
