# Generated by Django 3.1.7 on 2021-03-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0131_auto_20210306_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_members',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
