# Generated by Django 3.1.7 on 2021-03-06 15:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0134_auto_20210306_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament_members',
            name='old_id',
        ),
        migrations.AddField(
            model_name='tournament_members',
            name='old_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=None, size=None, unique=True),
        ),
    ]
