# Generated by Django 3.1.7 on 2021-03-07 01:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0155_auto_20210307_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='old_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None, unique=True),
        ),
        migrations.AlterField(
            model_name='referees',
            name='old_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None, unique=True),
        ),
    ]
