# Generated by Django 3.1.7 on 2021-03-10 06:02

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0161_auto_20210310_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='away',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, related_name='Calendar_away', to='competitions.clubs'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='home',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, related_name='Calendar_home', to='competitions.clubs'),
        ),
    ]
