# Generated by Django 3.1.7 on 2021-03-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0162_auto_20210310_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
