# Generated by Django 3.1.7 on 2021-03-10 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0169_auto_20210310_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='match',
        ),
    ]
