# Generated by Django 3.1.7 on 2021-03-10 07:51

import django.db.models.deletion
from django.db import migrations, models

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0170_remove_calendar_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='match_cast',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='away_formation',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Calendar_away_formation', to='competitions.formation'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='home_formation',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Calendar_home_formation', to='competitions.formation'),
        ),
    ]
