# Generated by Django 3.1.7 on 2021-03-10 14:07

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('decor', '0015_news_text_informations'),
        ('competitions', '0183_auto_20210310_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='fines',
            name='kdk',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='decor.news'),
        ),
    ]
