# Generated by Django 3.1.7 on 2021-03-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0225_auto_20210330_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disqualifications',
            name='edit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
