# Generated by Django 3.1.7 on 2021-03-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0226_auto_20210330_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disqualifications',
            name='matches',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
