# Generated by Django 3.1.7 on 2021-03-31 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0233_auto_20210330_1623'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keepers',
            unique_together=set(),
        ),
    ]
