# Generated by Django 3.2 on 2021-04-09 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0247_auto_20210405_0938'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='club_contacts',
            name='Club_contacts_unique_constraint_0',
        ),
        migrations.RemoveConstraint(
            model_name='club_contacts',
            name='Club_contacts_unique_constraint_1',
        ),
    ]
