# Generated by Django 3.2 on 2021-04-09 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0026_auto_20210402_0508'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0248_auto_20210409_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_contacts',
            name='priority',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='club_contacts',
            unique_together={('club', 'person', 'post', 'priority', 'props')},
        ),
    ]
