# Generated by Django 3.2 on 2021-04-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0258_alter_players_change_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players_change_history',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
