# Generated by Django 3.2 on 2021-04-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0265_auto_20210418_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdays',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
