# Generated by Django 3.2 on 2021-04-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0271_auto_20210423_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='checked',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
