# Generated by Django 3.2.4 on 2021-06-08 09:22

import bitfield.models
from django.db import migrations, models
import django.utils.timezone
import isc_common.fields.code_field
import isc_common.fields.description_field
import isc_common.fields.name_field


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0276_alter_seasons_props'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues_view',
            fields=[
                ('old_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('name', isc_common.fields.name_field.NameField(blank=True, null=True)),
                ('description', isc_common.fields.description_field.DescriptionField()),
                ('active', models.BooleanField()),
                ('add_slideshow_tabs', models.CharField(blank=True, max_length=255, null=True)),
                ('code', isc_common.fields.code_field.CodeField(blank=True, null=True)),
                ('contacts', models.TextField(blank=True, null=True)),
                ('header_image_src', isc_common.fields.name_field.NameField(blank=True, null=True)),
                ('header_real_name', isc_common.fields.name_field.NameField(blank=True, null=True)),
                ('logo_image_src', isc_common.fields.name_field.NameField(blank=True, null=True)),
                ('logo_real_name', isc_common.fields.name_field.NameField(blank=True, null=True)),
                ('position', models.SmallIntegerField(default=1)),
                ('referees_max', models.SmallIntegerField(default=1)),
                ('slideshow_title', models.CharField(blank=True, max_length=255, null=True)),
                ('props', bitfield.models.BitField((('active', 'active'), ('parimatch', 'parimatch'), ('submenu', 'submenu'), ('nonphoto', 'nonphoto'), ('show_in_menu', 'show_in_menu'), ('show_referee_photo_in_protocols', 'show_referee_photo_in_protocols'), ('show_stadium_photo_in_protocols', 'show_stadium_photo_in_protocols'), ('show_shirt_in_protocols', 'show_shirt_in_protocols')), db_index=True, default=1)),
            ],
            options={
                'verbose_name': 'Лиги',
                'db_table': 'competitions_leagues_view',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='leagues',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='tournaments',
            name='parent',
        ),
        migrations.AlterField(
            model_name='leagues',
            name='code',
            field=isc_common.fields.code_field.CodeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='code',
            field=isc_common.fields.code_field.CodeField(blank=True, null=True),
        ),
    ]
