# Generated by Django 3.2.4 on 2021-06-26 22:14

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0292_remove_calendar_match_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='next_match',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competitions.calendar'),
        ),
    ]
