# Generated by Django 3.2.4 on 2021-06-28 20:56

from django.db import migrations
import isc_common.fields.name_field


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0299_command_structure_tmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='command_structure_tmp',
            name='first_name',
            field=isc_common.fields.name_field.NameField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='command_structure_tmp',
            name='last_name',
            field=isc_common.fields.name_field.NameField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='command_structure_tmp',
            name='middle_name',
            field=isc_common.fields.name_field.NameField(blank=True, null=True),
        ),
    ]
