# Generated by Django 3.2.6 on 2021-08-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0335_auto_20210823_0721'),
    ]

    operations = [
        # migrations.RunPython(fill_image_type)
    ]
