# Generated by Django 3.2.6 on 2021-08-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0107_alter_users_images_unique_together'),
        ('competitions', '0337_alter_calendar_images_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='club_logo_history_images',
            unique_together={('image', 'main_model', 'type', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='clubs_images',
            unique_together={('image', 'main_model', 'type', 'deleted_at')},
        ),
    ]
