# Generated by Django 3.2.6 on 2021-08-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0110_alter_images_unique_together'),
        ('competitions', '0343_alter_referees_images_unique_together'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='referees_images',
        #     unique_together={('image', 'main_model', 'type', 'deleted_at')},
        # ),
    ]
