# Generated by Django 3.2.6 on 2021-08-27 11:24

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0348_alter_divisions_number_of_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisions',
            name='disqualification_condition',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competitions.disqualification_condition'),
        ),
    ]
