# Generated by Django 3.2.6 on 2021-09-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0364_squads_text_informations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squads',
            name='editor',
        ),
    ]
