# Generated by Django 3.2.7 on 2021-09-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0389_penalties_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepers',
            name='match_id_old',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='keepers',
            name='player_id_old',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='keepers',
            name='tournament_id_old',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='keepers',
            unique_together={('match', 'tournament', 'player')},
        ),
        migrations.RemoveField(
            model_name='keepers',
            name='old_id',
        ),
    ]
