# Generated by Django 3.2.7 on 2021-09-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0396_match_protocol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match_protocol',
            options={'managed': False, 'verbose_name': 'Протокол матча'},
        ),
    ]
