[tool.poetry]
name = "sandsldahelper"
version = "0.1.6"
description = "This python package is meant to make creating, testing and creating useful output files for LDA or PT topic modeling much easier. This package uses Tomotopy for topic modeling."
authors = ["Levi Sands <ldsands@outlook.com>"]
license = "MIT License"
packages = [
  {include = "sandsldahelper", from = "src"},
]

[tool.poetry.dependencies]
# python = "^3.9"
python = ">=3.9,<3.11"
wheel = "^0.37.0"
flake8 = "^3.9.2"
pretty-errors = "^1.2.24"
isort = "^5.9.3"
numpy = "^1.21.2"
pandas = "^1.3.3"
pyarrow = "^5.0.0"
vaex = "^4.5.0"
zstandard = "^0.15.2"
openpyxl = "^3.0.8"
tqdm = "^4.62.2"
nltk = "^3.6.2"
spacy = "^3.1.2"
msgpack = "^1.0.2"
tomotopy = "^0.12.2"
pyLDAvis = "^3.3.1"
sandspythonfunctions = "^0.1.0"

[tool.poetry.dev-dependencies]
# here you put any packages that would be used in development of the package such as packages used in testing

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.1.10"]
