name: publish

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    name: Check commit message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check commit message
        uses: adityaa30/check-commit@master
        with:
          max-header-length: 255

  test:
    name: Run pytest
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Run mypy
        run: mypy . --ignore-missing-imports
      - name: Run Black
        run: black --check --diff --config pyproject.toml tests flaky_tests_detection
      - name: Run tests
        run: pytest --cov=.

  build-and-run-docker-image:
    name: Docker build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run: |
          docker build . -t flaky-docker
          docker run flaky-docker --test-history-csv=test.csv --grouping-option=runs --window-size=2 --window-count=5 --top-n=5 --heatmap

  release:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    name: Publish
    needs: build-and-run-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          git config user.email "semantic-release"
          git config user.name "semantic-release"
          make publish
