# Generated by Django 3.1.6 on 2021-03-01 06:58

import bitfield.models
import django.db.models.deletion
from django.db import migrations, models

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0012_city_regions'),
        ('decor', '0004_remove_banners_edited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='number',
        ),
        migrations.AddField(
            model_name='banners',
            name='padding_top',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banners',
            name='region',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='region.regions'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='position',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='banners',
            name='props',
            field=bitfield.models.BitField((('active', 'active'), ('overlap', 'overlap')), db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='banners',
            name='rotate',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
