# Generated by Django 3.1.6 on 2021-03-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0005_auto_20210301_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
