# Generated by Django 3.1.7 on 2021-03-11 06:10

import bitfield.models
import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('region', '0040_auto_20210309_0833'),
        ('competitions', '0186_calendar_links'),
        ('decor', '0016_auto_20210310_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='fixed_position',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='news',
            name='disable_editor',
        ),
        migrations.AddField(
            model_name='news',
            name='league',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='competitions.leagues'),
        ),
        migrations.AddField(
            model_name='news',
            name='match',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='competitions.calendar'),
        ),
        migrations.AddField(
            model_name='news',
            name='region',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='region.regions'),
        ),
        migrations.AddField(
            model_name='news',
            name='tournament',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='competitions.tournaments'),
        ),
        migrations.AlterField(
            model_name='news',
            name='props',
            field=bitfield.models.BitField((('active', 'active'), ('disable_editor', 'disable_editor'), ('fixed_position', 'fixed_position'), ('in_bottom', 'in_bottom'), ('in_middle', 'in_middle'), ('in_top', 'in_top')), db_index=True, default=1),
        ),
    ]
