# Generated by Django 3.2.7 on 2021-09-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0034_newsquantity_byurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsquantity_byurl',
            name='quantity',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsquantity_byurl',
            name='url',
            field=models.URLField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
