# Generated by Django 3.2.7 on 2021-09-22 17:48

from django.db import migrations, models
import isc_common.fields.code_field


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0051_news_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='old_image_big_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='old_image_small_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='old_toutr',
            field=isc_common.fields.code_field.CodeField(blank=True, null=True),
        ),
    ]
