# Generated by Django 3.2.7 on 2021-09-23 00:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import isc_common.fields.code_field
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0134_alter_text_informations_text'),
        ('decor', '0057_news_favorites_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_start_block_tournament',
            name='old_image_big_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='news_start_block_tournament',
            name='old_image_small_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='News_start_block_tournament_links',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('code', isc_common.fields.code_field.CodeStrictField()),
                ('block', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='decor.news_start_block_tournament')),
                ('link', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.links')),
            ],
            options={
                'verbose_name': 'Кросс таблица',
                'unique_together': {('link', 'block', 'code')},
            },
        ),
    ]
