# Generated by Django 3.1.6 on 2021-02-19 09:14

import django.utils.timezone
from django.db import migrations, models

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0045_squads_match'),
        ('constructions', '0004_stadium_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium_rating',
            name='league',
        ),
        migrations.RemoveField(
            model_name='stadium_rating',
            name='stadium',
        ),
        migrations.CreateModel(
            name='Stadium_zones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('league', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.leagues')),
                ('stadium', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='constructions.stadiums')),
            ],
            options={
                'verbose_name': 'Сортировка стадионов',
            },
        ),
        migrations.AddField(
            model_name='stadium_rating',
            name='stadium_zone',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='constructions.stadium_zones'),
        ),
    ]
