# Generated by Django 3.2.6 on 2021-08-25 11:26

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0026_auto_20210823_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields_images',
            name='main_model',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='constructions.fields'),
        ),
        migrations.AlterField(
            model_name='stadiums_images',
            name='main_model',
            field=isc_common.fields.related.ForeignKeyCascade(on_delete=django.db.models.deletion.CASCADE, to='constructions.stadiums'),
        ),
    ]
