import json
import setuptools

kwargs = json.loads(
    """
{
    "name": "cdktf-cdktf-provider-aws",
    "version": "2.0.13",
    "description": "Prebuilt aws Provider for Terraform CDK (cdktf)",
    "license": "MPL-2.0",
    "url": "https://github.com/hashicorp/cdktf-provider-aws.git",
    "long_description_content_type": "text/markdown",
    "author": "HashiCorp",
    "bdist_wheel": {
        "universal": true
    },
    "project_urls": {
        "Source": "https://github.com/hashicorp/cdktf-provider-aws.git"
    },
    "package_dir": {
        "": "src"
    },
    "packages": [
        "cdktf_cdktf_provider_aws",
        "cdktf_cdktf_provider_aws._jsii",
        "cdktf_cdktf_provider_aws.access_analyzer",
        "cdktf_cdktf_provider_aws.acm",
        "cdktf_cdktf_provider_aws.amplify",
        "cdktf_cdktf_provider_aws.api_gateway",
        "cdktf_cdktf_provider_aws.api_gateway_v2",
        "cdktf_cdktf_provider_aws.app_auto_scaling",
        "cdktf_cdktf_provider_aws.app_config",
        "cdktf_cdktf_provider_aws.app_mesh",
        "cdktf_cdktf_provider_aws.app_runner",
        "cdktf_cdktf_provider_aws.app_stream",
        "cdktf_cdktf_provider_aws.app_sync",
        "cdktf_cdktf_provider_aws.athena",
        "cdktf_cdktf_provider_aws.auto_scaling",
        "cdktf_cdktf_provider_aws.auto_scaling_plans",
        "cdktf_cdktf_provider_aws.backup",
        "cdktf_cdktf_provider_aws.batch",
        "cdktf_cdktf_provider_aws.budgets",
        "cdktf_cdktf_provider_aws.chime",
        "cdktf_cdktf_provider_aws.cloud_formation",
        "cdktf_cdktf_provider_aws.cloud_front",
        "cdktf_cdktf_provider_aws.cloud_hsm",
        "cdktf_cdktf_provider_aws.cloud_trail",
        "cdktf_cdktf_provider_aws.cloud_watch",
        "cdktf_cdktf_provider_aws.cloud_watch_event_bridge",
        "cdktf_cdktf_provider_aws.cloud9",
        "cdktf_cdktf_provider_aws.code_artifact",
        "cdktf_cdktf_provider_aws.code_build",
        "cdktf_cdktf_provider_aws.code_commit",
        "cdktf_cdktf_provider_aws.code_deploy",
        "cdktf_cdktf_provider_aws.code_pipeline",
        "cdktf_cdktf_provider_aws.code_star",
        "cdktf_cdktf_provider_aws.cognito",
        "cdktf_cdktf_provider_aws.config",
        "cdktf_cdktf_provider_aws.connect",
        "cdktf_cdktf_provider_aws.cur",
        "cdktf_cdktf_provider_aws.data_pipeline",
        "cdktf_cdktf_provider_aws.data_sources",
        "cdktf_cdktf_provider_aws.data_sync",
        "cdktf_cdktf_provider_aws.dax",
        "cdktf_cdktf_provider_aws.device_farm",
        "cdktf_cdktf_provider_aws.direct_connect",
        "cdktf_cdktf_provider_aws.directory_service",
        "cdktf_cdktf_provider_aws.dlm",
        "cdktf_cdktf_provider_aws.dms",
        "cdktf_cdktf_provider_aws.document_db",
        "cdktf_cdktf_provider_aws.dynamo_db",
        "cdktf_cdktf_provider_aws.ec2",
        "cdktf_cdktf_provider_aws.ecr",
        "cdktf_cdktf_provider_aws.ecs",
        "cdktf_cdktf_provider_aws.efs",
        "cdktf_cdktf_provider_aws.eks",
        "cdktf_cdktf_provider_aws.elasti_cache",
        "cdktf_cdktf_provider_aws.elastic_beanstalk",
        "cdktf_cdktf_provider_aws.elastic_search",
        "cdktf_cdktf_provider_aws.elastic_transcoder",
        "cdktf_cdktf_provider_aws.elb",
        "cdktf_cdktf_provider_aws.emr",
        "cdktf_cdktf_provider_aws.event_bridge_schemas",
        "cdktf_cdktf_provider_aws.f_sx",
        "cdktf_cdktf_provider_aws.fms",
        "cdktf_cdktf_provider_aws.game_lift",
        "cdktf_cdktf_provider_aws.glacier",
        "cdktf_cdktf_provider_aws.global_accelerator",
        "cdktf_cdktf_provider_aws.glue",
        "cdktf_cdktf_provider_aws.guard_duty",
        "cdktf_cdktf_provider_aws.iam",
        "cdktf_cdktf_provider_aws.image_builder",
        "cdktf_cdktf_provider_aws.inspector",
        "cdktf_cdktf_provider_aws.io_t",
        "cdktf_cdktf_provider_aws.kinesis",
        "cdktf_cdktf_provider_aws.kms",
        "cdktf_cdktf_provider_aws.lake_formation",
        "cdktf_cdktf_provider_aws.lambda_function",
        "cdktf_cdktf_provider_aws.lex",
        "cdktf_cdktf_provider_aws.license_manager",
        "cdktf_cdktf_provider_aws.lightsail",
        "cdktf_cdktf_provider_aws.macie",
        "cdktf_cdktf_provider_aws.macie2",
        "cdktf_cdktf_provider_aws.media_convert",
        "cdktf_cdktf_provider_aws.media_package",
        "cdktf_cdktf_provider_aws.media_store",
        "cdktf_cdktf_provider_aws.mq",
        "cdktf_cdktf_provider_aws.msk",
        "cdktf_cdktf_provider_aws.mwaa",
        "cdktf_cdktf_provider_aws.neptune",
        "cdktf_cdktf_provider_aws.network_firewall",
        "cdktf_cdktf_provider_aws.ops_works",
        "cdktf_cdktf_provider_aws.organizations",
        "cdktf_cdktf_provider_aws.outposts",
        "cdktf_cdktf_provider_aws.pinpoint",
        "cdktf_cdktf_provider_aws.pricing",
        "cdktf_cdktf_provider_aws.prometheus",
        "cdktf_cdktf_provider_aws.qldb",
        "cdktf_cdktf_provider_aws.quick_sight",
        "cdktf_cdktf_provider_aws.ram",
        "cdktf_cdktf_provider_aws.rds",
        "cdktf_cdktf_provider_aws.redshift",
        "cdktf_cdktf_provider_aws.resource_groups",
        "cdktf_cdktf_provider_aws.route53",
        "cdktf_cdktf_provider_aws.s3",
        "cdktf_cdktf_provider_aws.sage_maker",
        "cdktf_cdktf_provider_aws.secrets_manager",
        "cdktf_cdktf_provider_aws.security_hub",
        "cdktf_cdktf_provider_aws.serverless_application_repository",
        "cdktf_cdktf_provider_aws.service_catalog",
        "cdktf_cdktf_provider_aws.service_discovery",
        "cdktf_cdktf_provider_aws.service_quotas",
        "cdktf_cdktf_provider_aws.ses",
        "cdktf_cdktf_provider_aws.sfn",
        "cdktf_cdktf_provider_aws.shield",
        "cdktf_cdktf_provider_aws.signer",
        "cdktf_cdktf_provider_aws.simple_db",
        "cdktf_cdktf_provider_aws.sns",
        "cdktf_cdktf_provider_aws.sqs",
        "cdktf_cdktf_provider_aws.ssm",
        "cdktf_cdktf_provider_aws.sso_admin",
        "cdktf_cdktf_provider_aws.storage_gateway",
        "cdktf_cdktf_provider_aws.swf",
        "cdktf_cdktf_provider_aws.synthetics",
        "cdktf_cdktf_provider_aws.timestream_write",
        "cdktf_cdktf_provider_aws.transfer",
        "cdktf_cdktf_provider_aws.vpc",
        "cdktf_cdktf_provider_aws.waf",
        "cdktf_cdktf_provider_aws.waf_regional",
        "cdktf_cdktf_provider_aws.wafv2",
        "cdktf_cdktf_provider_aws.work_link",
        "cdktf_cdktf_provider_aws.workspaces",
        "cdktf_cdktf_provider_aws.x_ray"
    ],
    "package_data": {
        "cdktf_cdktf_provider_aws._jsii": [
            "provider-aws@2.0.13.jsii.tgz"
        ],
        "cdktf_cdktf_provider_aws": [
            "py.typed"
        ]
    },
    "python_requires": ">=3.6",
    "install_requires": [
        "cdktf>=0.7.0, <0.8.0",
        "constructs>=10.0.0, <11.0.0",
        "jsii>=1.34.0, <2.0.0",
        "publication>=0.0.3"
    ],
    "classifiers": [
        "Intended Audience :: Developers",
        "Operating System :: OS Independent",
        "Programming Language :: JavaScript",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Typing :: Typed",
        "Development Status :: 5 - Production/Stable",
        "License :: OSI Approved"
    ],
    "scripts": []
}
"""
)

with open("README.md", encoding="utf8") as fp:
    kwargs["long_description"] = fp.read()


setuptools.setup(**kwargs)
