# Generated by Django 3.1.6 on 2021-03-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0007_auto_20210301_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
