# Generated by Django 3.1.7 on 2021-03-11 06:10

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0186_calendar_links'),
        ('region', '0040_auto_20210309_0833'),
        ('decor', '0017_auto_20210311_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='league',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.leagues'),
        ),
        migrations.AlterField(
            model_name='news',
            name='match',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.calendar'),
        ),
        migrations.AlterField(
            model_name='news',
            name='region',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='region.regions'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tournament',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.tournaments'),
        ),
    ]
