# Generated by Django 3.1.7 on 2021-03-26 09:48

from django.db import migrations

import isc_common.fields.code_field


class Migration(migrations.Migration):
    dependencies = [
        ('decor', '0024_auto_20210311_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners_type',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
        migrations.AlterField(
            model_name='menu_type',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
        migrations.AlterField(
            model_name='menus',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
        migrations.AlterField(
            model_name='news_type',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
    ]
