# Generated by Django 3.2.7 on 2021-09-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0038_menus_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='old_id',
        ),
        migrations.AddField(
            model_name='bottom_menu',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
