# Generated by Django 3.2.7 on 2021-09-22 12:53

import bitfield.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0039_auto_20210922_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_items',
            fields=[
                ('menus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='decor.menus')),
                ('old_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('props', bitfield.models.BitField((('active', 'active'), ('target', 'target')), db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Главное меню',
            },
            bases=('decor.menus', models.Model),
        ),
    ]
