# Generated by Django 3.2.7 on 2021-09-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0043_menu_item_leagues'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item_leagues',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
