# Generated by Django 3.2.7 on 2021-09-22 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decor', '0054_news_action_types_news_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_actions',
            name='dt',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news_actions',
            name='from_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_actions',
            name='from_tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_actions',
            name='new',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='decor.news'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news_actions',
            name='to_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_actions',
            name='to_tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_actions',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='decor.news_action_types'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news_actions',
            name='user',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.user'),
            preserve_default=False,
        ),
    ]
