# Generated by Django 3.2.7 on 2021-09-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0055_auto_20210922_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_actions',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
