[tool.poetry]
name = "cfaudit"
version = "0.3"
description = "The CityFibre AWS security group analyzer"
authors = ["Sergii Reznichenko <srezni@softserveinc.com>"]
license = "Apache-2.0"
keywords = [
    "cfaudit", "aws", "security", "analysis",
]

[tool.poetry.dependencies]
python = "^3.7"
boto3 = "^1.14"
click = "^7.1"
colorama = "^0.4.3"
PyYAML = "^5.3"
Jinja2 = "^2.11"

[tool.poetry.dev-dependencies]
moto = "^1.3"
pytest = "^6.0"

[tool.poetry.scripts]
cfaudit = "cfaudit.sg_audit:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"