# Generated by Django 3.1.6 on 2021-02-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_edited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edited_by',
            name='edited_by',
        ),
    ]
