# Generated by Django 3.2 on 2021-04-20 14:38

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20210402_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='props',
            field=bitfield.models.BitField((('administrator', 'administrator'),), db_index=True, default=0),
        ),
    ]
