[tool.poetry]
name = "Simyan"
version = "0.6.1"
description = "A Python wrapper for the Comicvine API."
license = "GPL-3.0-or-later"
authors = ["Buried-In-Code <BuriedInCode@tuta.io>"]
maintainers = ["Buried-In-Code <BuriedInCode@tuta.io>"]
readme = "README.md"
repository = "https://github.com/Buried-In-Code/Simyan"
documentation = "https://simyan.readthedocs.io/en/latest/"
packages = [
	{ include = "simyan" }
]
include = [
    { path = "tests", format = "sdist" }
]
classifiers = [
	"Development Status :: 4 - Beta",
	"Environment :: Console",
	"Intended Audience :: Developers",
	"License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
	"Natural Language :: English",
	"Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
	"Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Internet",
	"Typing :: Typed"
]
keywords=["comics", "comic", "metadata"]

[tool.poetry.dependencies]
python = "^3.7"
marshmallow = "^3.14.0"
requests = "^2.26.0"
ratelimit = "^2.2.1"
deprecation = "^2.1.0"

# Optional dependencies
sphinxcontrib-napoleon = {version = "^0.7", optional = true}
sphinx-rtd-theme = {version = "^1.0.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
tox = "^3.24.4"
pre-commit = "^2.15.0"
pyupgrade = "^2.29.0"
black = "^21.9b0"
flake8 = "^4.0.1"
flake8-docstrings = "^1.6.0"
flake8-builtins = "^1.5.3"
flake8-rst-docstrings = "^0.2.3"
isort = "^5.9.3"
seed-isort-config = "^2.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Issue Tracker" = "https://github.com/Buried-In-Code/Simyan/issues"

[tool.black]
line-length = 120
target-version = ['py37']

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
default_section = "THIRDPARTY"
known_first_party = []
known_third_party = ["deprecation", "marshmallow", "pytest", "ratelimit", "requests"]

[tool.poetry.extras]
docs = ["sphinx-rtd-theme", "sphinxcontrib-napoleon"]

[tool.coverage.run]
source = ["simyan"]

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
addopts = ["--cov", "-x"]
