[tool.poetry]
name = "chamredb"
version = "0.2.0"
description = ""
authors = ["Anthony Underwood <anthony.underwood@cgps.group>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
networkx = "^2.6"
pandas = "^1.3"
rich = "^10.12"
pronto = "2.4.3"
seaborn = "^0.11"
numpy = "^1.21"

[tool.poetry.dev-dependencies]
twine = "^1.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
