[tool.poetry]
name = "verbcl-graph4nlp-cpu"
version = "0.1.0"
description = "Fork of Graph4NLP specific for VerbCL Graph on CPU"
authors = ["Julien ROSSI <j.rossi@uva.nl>"]
packages = [
    { include="graph4nlp"}
]

[tool.poetry.dependencies]
python = "^3.9"
pythonds = "^1.2.1"
nltk = ">=3.5"
stanfordcorenlp = "^3.9.1"
scipy = ">=1.5.2"
scikit-learn = ">=0.23.2"
networkx = ">=2.5"
ogb = "^1.3.2"
tqdm = ">=4.29.0"
PyYAML = "^6.0"
transformers = "^4.11.3"
dgl = "^0.6.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
