[tool.poetry]
name = "ohcg"
version = "0.1.2"
description = "OpenAPI3 HTTP client generator"
authors = ["Pylakey <pylakey@protonmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/pylakey/ohcg"
repository = "https://github.com/pylakey/ohcg"
packages = [
    { include = "ohcg" },
]
include = [
    "README.md",
]
classifiers = [
    "Framework :: AsyncIO",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.19.0"
jinja2 = "^3.0.1"
pydantic = { extras = ["email"], version = "^1.8.2" }
pydash = "^5.0.2"
typer = { extras = ["all"], version = "^0.4.0" }

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
ohcg = "ohcg.main:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
