# Generated by Django 3.1.6 on 2021-02-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0012_delete_old_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrators',
            name='old_id',
            field=models.BigIntegerField(default=None),
        ),
    ]
