# Generated by Django 3.1.7 on 2021-03-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0041_users_images_props'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='users_images',
            unique_together=set(),
        ),
    ]
