# Generated by Django 3.1.7 on 2021-03-15 13:47

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('region', '0041_auto_20210315_1100'),
        ('user_ext', '0050_auto_20210315_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='region',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='region.regions'),
            preserve_default=False,
        ),
    ]
