# Generated by Django 3.2.3 on 2021-05-14 15:21

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0097_auto_20210422_0001'),
        ('user_ext', '0069_remove_administrators_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person_club_photos',
            name='users_image',
        ),
        migrations.AddField(
            model_name='person_club_photos',
            name='image',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person_club_photos',
            name='main_model',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='user_ext.persons'),
            preserve_default=False,
        ),
    ]
