# Generated by Django 3.2.3 on 2021-05-14 15:49

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0275_tournament_member_doubles_old_id'),
        ('user_ext', '0070_auto_20210514_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_club_photos',
            name='club',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.clubs'),
        ),
    ]
