# Generated by Django 3.2.4 on 2021-06-28 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_ext', '0075_users_hidden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users_hidden',
        ),
    ]
