[tool.poetry]
name = "iterable-data-import"
version = "0.1.0"
description = "A library for ad-hoc bulk imports to Iterable"
authors = ["julianmclain <julianrmclain@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
coverage = "^5.5"
pytest-cov = "^2.12.1"
python-dotenv = "^0.19.1"
iterablepythonwrapper = "^1.1"
Faker = "^9.3.1"
pytest-mock = "^3.6.1"
flake8-bugbear = "^21.9.2"
tox-gh-actions = "^2.8.1"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["iterable_data_import"]

[tool.coverage.report]
fail_under = 70
show_missing = true

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "ERROR"
log_cli_format = "[%(levelname)s] - %(asctime)s - %(name)s - %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

[build-system]
requires = ["poetry>=1.1.10"]
build-backend = "poetry.masonry.api"
