[tool.poetry]
name = "venvarium"
version = "0.1.0"
description = "Object-based interaction with a Python virtual environment."
authors = ["Maximillian Strand <maximillian.strand@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
entry-points-txt = "^0.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
