# Generated by Django 3.2 on 2021-10-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailagenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylocation',
            old_name='zip',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='activitylocation',
            name='street',
        ),
        migrations.AddField(
            model_name='activitylocation',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='street name'),
        ),
    ]
