$schema: https://componentsdk.azureedge.net/jsonschema/CommandComponent.json
name: microsoft.com.azureml.samples.sweep_train
version: 0.0.4
display_name: Tune
type: CommandComponent
description: A dummy train component
tags: {category: Component Tutorial, contact: amldesigner@microsoft.com}
inputs:
  training_data:
    type: path
    description: Training data organized in the torchvision format/structure
    optional: false
  max_epochs:
    type: Integer
    description: Maximum number of epochs for the training
    optional: false
  learning_rate:
    type: Float
    description: learning_rate
    min: 0.001
    max: 0.1
    optional: false
  subsample:
    type: Float
    description: learning_rate
    min: 0.1
    max: 0.5
    optional: false
outputs:
  saved_model:
    type: path
  other_output:
    type: path
environment:
    name: AzureML-Minimal
command: >-
        python train.py --training_data {inputs.training_data} --max_epochs {inputs.max_epochs}
        --learning_rate {inputs.learning_rate} --subsample {inputs.subsample}