# Generated by Django 3.1.6 on 2021-02-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_region_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regions',
            name='double_logo',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='header',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='right_logo',
        ),
    ]
