# Generated by Django 3.1.6 on 2021-02-18 07:05

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0063_auto_20210217_1443'),
        ('region', '0006_auto_20210218_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='color',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.standard_colors'),
        ),
    ]
