# Generated by Django 3.1.6 on 2021-03-01 12:32

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0049_seasons_old_id'),
        ('region', '0028_regions_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='season',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.seasons'),
        ),
    ]
