# Generated by Django 3.1.6 on 2021-03-01 14:39

from django.db import migrations

import isc_common.fields.code_field


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0029_auto_20210301_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='region_links',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
    ]
