# Generated by Django 3.1.6 on 2021-03-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0035_auto_20210302_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city_images',
            old_name='city',
            new_name='main_model',
        ),
        migrations.AlterUniqueTogether(
            name='city_images',
            unique_together=set(),
        ),
    ]
