# Generated by Django 3.1.6 on 2021-03-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20210301_1433'),
        ('region', '0038_remove_cities_region'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='region_links',
            unique_together={('link', 'region', 'code')},
        ),
    ]
