# Generated by Django 3.2.4 on 2021-06-04 07:32

from django.db import migrations, models
import django.utils.timezone
import isc_common.fields.code_field
import isc_common.fields.description_field
import isc_common.fields.name_field


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0048_auto_20210604_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region_zones_view',
            fields=[
                ('old_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('code', isc_common.fields.code_field.CodeStrictField()),
                ('name', isc_common.fields.name_field.NameField(blank=True, null=True)),
                ('description', isc_common.fields.description_field.DescriptionField()),
            ],
            options={
                'verbose_name': 'Зоны регионов',
                'db_table': 'region_region_zones_view',
                'managed': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='region_zone_phones',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='region_zone_phones',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='region_zone_phones',
            name='zone',
        ),
        migrations.DeleteModel(
            name='Region_zone_e_mails',
        ),
        migrations.DeleteModel(
            name='Region_zone_phones',
        ),
    ]
