# Generated by Django 3.2.6 on 2021-08-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0107_alter_users_images_unique_together'),
        ('region', '0056_alter_city_images_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='region_images',
            unique_together={('main_model', 'image', 'type', 'deleted_at')},
        ),
        migrations.AlterUniqueTogether(
            name='region_zone_images',
            unique_together={('main_model', 'image', 'type', 'deleted_at')},
        ),
    ]
