# Generated by Django 3.2.6 on 2021-08-23 12:21

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0110_alter_images_unique_together'),
        ('region', '0057_auto_20210823_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_images',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='isc_common.image_types'),
        ),
        migrations.AlterUniqueTogether(
            name='city_images',
            unique_together={('main_model', 'image', 'type', 'lastmodified')},
        ),
    ]
