# Generated by Django 3.2.6 on 2021-08-31 22:30
import django
import isc_common
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0068_alter_regions_props'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region_images',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.image_types'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region_zone_images',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.image_types'),
            preserve_default=False,
        ),
    ]
