# Generated by Django 3.2.4 on 2021-06-17 20:45

import django.utils.timezone
from django.db import migrations, models

import isc_common.fields.code_field
import isc_common.fields.name_field
import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0290_alter_goals_minute'),
        ('statistic', '0009_remove_raiting_of_players_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raiting_of_players_view',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('FIO', isc_common.fields.name_field.NameField(blank=True, null=True)),
                ('KF', isc_common.fields.code_field.CodeField(blank=True, null=True)),
                ('kf_bombar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kf_not_wins', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kf_opyt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kf_plus_minus', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kf_propusch_com', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kf_wins', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kf_zabito_com', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mid_propusch_com', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mid_zabito_com', models.DecimalField(decimal_places=2, max_digits=5)),
                ('not_win_cnt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pays', models.SmallIntegerField()),
                ('pers_not_wins', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pers_wins', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo_image_src', isc_common.fields.name_field.NameField(blank=True, null=True)),
                ('photo_real_name', isc_common.fields.name_field.NameField(blank=True, null=True)),
                ('plus_minus', models.DecimalField(decimal_places=2, max_digits=5)),
                ('propusch_com', models.DecimalField(decimal_places=2, max_digits=5)),
                ('raiting', models.DecimalField(decimal_places=2, max_digits=5)),
                ('standoff_cnt', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ничьих')),
                ('win_cnt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('zabito_com', models.DecimalField(decimal_places=2, max_digits=5)),
                ('zabito_play', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Рейтинг футболистов',
                'db_table': 'statistic_raiting_of_players_view',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='raiting_of_players_tournamet',
            name='division',
        ),
        migrations.CreateModel(
            name='Raiting_of_players_division',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('division', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.divisions')),
            ],
            options={
                'verbose_name': 'Кросс таблица',
            },
        ),
    ]
