# Generated by Django 3.2.4 on 2021-06-28 22:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0016_import_command_stuctures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import_command_stuctures_log',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('log', models.TextField()),
                ('imports', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='statistic.import_command_stuctures')),
            ],
            options={
                'verbose_name': 'Лог импорта составов',
            },
        ),
    ]
