# Generated by Django 3.2.8 on 2021-10-20 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotide_luna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('username', models.CharField(max_length=50, unique=True)),
                ('local', models.BooleanField()),
                ('host', models.CharField(max_length=50)),
                ('remote_url', models.CharField(max_length=100)),
                ('is_bot', models.BooleanField()),
                ('suspended', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='description_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='description_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('remote_url', models.URLField()),
                ('href', models.CharField(blank=True, max_length=100)),
                ('content_text', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('created', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('sticky', models.BooleanField()),
                ('content_markdown', models.TextField(blank=True)),
                ('approved', models.BooleanField()),
                ('local', models.BooleanField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lotide_luna.user')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotide_luna.community')),
            ],
        ),
    ]
