import setuptools
import os

def package_files(directory):
    paths = []
    for (path, directories, filenames) in os.walk(directory):
        for filename in filenames:
            paths.append(os.path.join('..', path, filename))
    return paths

extra_files = package_files('example/assets/components')

setuptools.setup(
    name='example-assets',
    version='0.0.1',
    author='Example Author',
    author_email='author@example.com',
    description='Component package generated by azure-ml-component. '
                'Learn more on reference doc site: https://aka.ms/azure-ml-component-reference.',
    classifiers=[
        "Intended Audience :: Developers",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
    ],
    install_requires=['azure-ml-component'],
    packages=setuptools.find_packages(),
    python_requires='>=3.6',
    include_package_data=True,
    package_data={'': extra_files},
)
