[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sqc"
authors = [{name = "Anexen"}]
readme = "README.md"
version = "0.1.0"
description = "SQL queries to collections"

classifiers = [
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Code Generators",
    "Programming Language :: SQL",
    "Programming Language :: Python :: 3",
]

dependencies = [
    "convtools",
    "sqloxide",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]

[project.urls]
Home = "https://github.com/Anexen/sqc"
