# Generated by Django 3.2.4 on 2021-06-18 05:24

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('statistic', '0012_alter_raiting_of_players_plays'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiting_of_players_division',
            name='raiting',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='statistic.raiting_of_players'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raiting_of_players_tournamet',
            name='raiting',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='statistic.raiting_of_players'),
            preserve_default=False,
        ),
    ]
