# Generated by Django 3.2.4 on 2021-06-29 00:21

from django.db import migrations
import isc_common.fields.name_field


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0018_auto_20210629_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_command_stuctures',
            name='path',
            field=isc_common.fields.name_field.NameField(blank=True, null=True),
        ),
    ]
