# Generated by Django 3.1.7 on 2021-03-09 08:33

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0077_image_types_images_links_text_informations'),
        ('inventory', '0011_auto_20210304_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes_images',
            name='image',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.images'),
        ),
    ]
