# Generated by Django 3.1.6 on 2021-02-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_site_lfl_images_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_lfl_images',
            name='date',
            field=models.BigIntegerField(default=None),
        ),
    ]
