# Generated by Django 3.1.6 on 2021-02-18 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_types',
            name='sizes',
        ),
        migrations.AddField(
            model_name='images',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, null=True, size=None),
        ),
    ]
