# Generated by Django 3.1.6 on 2021-02-19 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20210218_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menus',
        ),
    ]
