# Generated by Django 3.1.7 on 2021-03-09 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0024_delete_edited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_types',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image_type',
        ),
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.DeleteModel(
            name='Text_informations',
        ),
        migrations.DeleteModel(
            name='Image_types',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
