
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-19T13:15:11-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "de0efc858e7c8dad87e7b20c0c9bf3b73f3710ee",
 "version": "0.1.0a42"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
