# Generated by Django 3.1.6 on 2021-03-01 11:38

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0022_auto_20210301_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region_zone_images',
            name='image',
        ),
        migrations.AddField(
            model_name='region_zone_images',
            name='region',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='region.regions'),
        ),
    ]
