# Generated by Django 3.1.7 on 2021-03-26 09:48

from django.db import migrations

import isc_common.fields.code_field


class Migration(migrations.Migration):
    dependencies = [
        ('region', '0042_auto_20210324_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
        migrations.AlterField(
            model_name='region_zones',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
        migrations.AlterField(
            model_name='regions',
            name='code',
            field=isc_common.fields.code_field.CodeStrictField(),
        ),
    ]
