# Generated by Django 3.2.6 on 2021-08-30 15:24

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0067_auto_20210830_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='props',
            field=bitfield.models.BitField((('active', 'Актуальность'), ('select_division', 'Блокировать регион'), ('parimatch', 'parimatch'), ('submenu', 'Убрать submenu'), ('leagues_menu', 'Отключить выбор дивизиона')), db_index=True, default=1),
        ),
    ]
