# Generated by Django 3.2.4 on 2021-06-17 09:09

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0290_alter_goals_minute'),
        ('statistic', '0002_auto_20210617_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiting_of_players',
            name='formation',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='competitions.formation'),
            preserve_default=False,
        ),
    ]
