# Generated by Django 3.2.4 on 2021-06-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0005_raiting_of_players_not_win_cnt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raiting_of_players',
            old_name='stand_off_cnt',
            new_name='standoff_cnt',
        ),
    ]
