# Generated by Django 3.2.4 on 2021-06-18 03:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('statistic', '0010_auto_20210617_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raiting_of_players',
            old_name='pays',
            new_name='plays',
        ),
    ]
