# Generated by Django 3.2.4 on 2021-06-25 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('statistic', '0014_auto_20210618_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiting_of_players',
            name='formation',
        ),
    ]
