# Generated by Django 3.2.4 on 2021-06-29 14:09

from django.db import migrations
import isc_common.fields.code_field


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0021_alter_import_command_stuctures_log_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiting_of_players',
            name='num',
            field=isc_common.fields.code_field.CodeField(blank=True, null=True),
        ),
    ]
