
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-21T23:12:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "61e7d1aa3e728a35aa16f7463c43ee2e7bce2221",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
