
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-22T12:30:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "04249466f84368ca519c58dcc20245bebe3da37e",
 "version": "v0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
