project_urls:
    Source Code: https://sylvainprigent.github.io/napari-stracking
    Project Site: https://sylvainprigent.github.io/napari-stracking/
    Documentation: https://sylvainprigent.github.io/napari-stracking/description.html
    Bug Tracker: https://github.com/sylvainprigent/napari-stracking/issues
    User Support: https://github.com/sylvainprigent/napari-stracking/issues
    Twitter: https://twitter.com/SylvainPrigent2