# Generated by Django 3.1.6 on 2021-03-02 11:35

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0038_remove_cities_region'),
        ('constructions', '0009_auto_20210302_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadiums',
            name='city',
        ),
        migrations.AddField(
            model_name='stadiums',
            name='region',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='region.regions'),
        ),
    ]
