# Generated by Django 3.1.6 on 2021-03-02 12:44

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0056_auto_20210302_0641'),
        ('constructions', '0011_auto_20210302_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium_rating',
            name='stadium_zone',
        ),
        migrations.AddField(
            model_name='stadium_rating',
            name='league',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='competitions.leagues'),
        ),
        migrations.AddField(
            model_name='stadium_rating',
            name='stadium',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='constructions.stadiums'),
        ),
    ]
