# Generated by Django 3.1.6 on 2021-03-02 12:45

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0056_auto_20210302_0641'),
        ('constructions', '0012_auto_20210302_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium_rating',
            name='league',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='competitions.leagues'),
        ),
        migrations.AlterField(
            model_name='stadium_rating',
            name='stadium',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='constructions.stadiums'),
        ),
    ]
