# Generated by Django 3.2.6 on 2021-08-31 22:36
import django
import isc_common
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0029_auto_20210829_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields_images',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.image_types'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stadiums_images',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='isc_common.image_types'),
            preserve_default=False,
        ),
    ]
