# Generated by Django 3.2.7 on 2021-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0031_stadiums_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium_zones',
            name='old_id',
        ),
        migrations.AddField(
            model_name='stadium_zones',
            name='old_league_id',
            field=models.BigIntegerField(db_index=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium_zones',
            name='old_stadium_id',
            field=models.BigIntegerField(db_index=True, default=None),
            preserve_default=False,
        ),
    ]
