[tool.poetry]
name = "flex_plot"
version = "0.1.0"
description = ""
authors = ["Ilyas Kuhlemann <ilyasp.ku@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
toml = "^0.10.2"
matplotlib = "^3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
flex-plot-run = "flex_plot.cli.run:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
