
################################################################################
[register.plain_dummy_reg]

mode = "r_w"
description = "A plain **dummy** register."

[register.plain_dummy_reg.bit.plain_bit_a]

description = "Bit A"
default_value = "0"

[register.plain_dummy_reg.bit.plain_bit_b]

description = "Bit B"
default_value = "1"

[register.plain_dummy_reg.bit_vector.plain_bit_vector]

description = "Bit **vector**"
width = 4
default_value = "0011"


################################################################################
[register_array.dummy_regs]

array_length = 3
description = "An **array** with some dummy regs"

# ------------------------------------------------------------------------------
[register_array.dummy_regs.register.array_dummy_reg]

mode = "r_w"
description = "The first register in the array."

[register_array.dummy_regs.register.array_dummy_reg.bit.array_bit_a]

description = "Array register bit A"
default_value = "1"

[register_array.dummy_regs.register.array_dummy_reg.bit.array_bit_b]

description = "Array register bit B"
default_value = "0"

[register_array.dummy_regs.register.array_dummy_reg.bit_vector.array_bit_vector]

description = "Array register bit vector"
width = 5
default_value = "01100"


# ------------------------------------------------------------------------------
[register_array.dummy_regs.register.second_array_dummy_reg]

description = "The second register in the array."
mode = "r"


################################################################################
[register_array.further_regs]

array_length = 1

# ------------------------------------------------------------------------------
[register_array.further_regs.register.dummy_reg]

mode = "r_w"
description = "A register in a second register array"
