# Generated by Django 3.1.6 on 2021-03-02 06:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20210301_1433'),
        ('competitions', '0056_auto_20210302_0641'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_ext', '0017_auto_20210302_0627'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='users_images',
            unique_together={('main_model', 'image', 'club')},
        ),
    ]
