# Generated by Django 3.1.7 on 2021-03-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0023_auto_20210303_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrators',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
