# Generated by Django 3.1.7 on 2021-03-03 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_ext', '0027_auto_20210303_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='user',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
