# Generated by Django 3.1.7 on 2021-03-15 09:22

import django.db.models.deletion
from django.db import migrations

import isc_common.fields.related


class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0193_auto_20210315_0922'),
        ('user_ext', '0046_delete_users_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='club',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='competitions.clubs'),
            preserve_default=False,
        ),
    ]
