# Generated by Django 3.1.7 on 2021-03-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_ext', '0047_auto_20210315_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='old_ids',
        ),
        migrations.AddField(
            model_name='persons',
            name='old_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
