# Generated by Django 3.2.6 on 2021-08-25 11:30

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0077_alter_person_club_photos_main_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_club_photos',
            name='main_model',
            field=isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='user_ext.persons'),
        ),
    ]
